### ISSUE TITLE
Unknown scheduler: DDIM_tiled

### ISSUE THREAD

**Issue by cheezecrisp** [kijai/ComfyUI-CogVideoXWrapper#129]
When 'temporal_tiling' is selected in context options, the cogvideoxfun sampler gives following error:

Temporal tiling enabled, changing scheduler to DDIM_tiled
!!! Exception during processing !!! Unknown scheduler: DDIM_tiled
Traceback (most recent call last):
  File "D:\AI\ComfyUI_windows_portable\ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\AI\ComfyUI_windows_portable\ComfyUI\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\AI\ComfyUI_windows_portable\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "D:\AI\ComfyUI_windows_portable\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-CogVideoXWrapper\nodes.py", line 1051, in process
    raise ValueError(f"Unknown scheduler: {scheduler}")
ValueError: Unknown scheduler: DDIM_tiled

**Comment by cheezecrisp** [comment]
BTW, in the webui of[ cogvideox-fun](github.com/aigc-apps/CogVideoX-Fun) we can generate i2v video with frames longer than 49, the result is quite smooth. I guess it is temporal_tiling or something like it to work

**Comment by kijai** [comment]
That was a mistake I made when refactoring the context options, should be fixed now. 

Fun models can do up to 73 frames without any tiling or contexting, after that it starts to loop from beginning. It's the same with these nodes. It's just the official I2V model which can't do anything but 49 frames.

**Comment by cheezecrisp** [comment]
> That was a mistake I made when refactoring the context options, should be fixed now.
> 
> Fun models can do up to 73 frames without any tiling or contexting, after that it starts to loop from beginning. It's the same with these nodes. It's just the official I2V model which can't do anything but 49 frames.

thank you, but there is another error now😂

Temporal tiling enabled, changing scheduler to CogVideoXDDIM
!!! Exception during processing !!! 'CogVideoX_Fun_Pipeline_Inpaint' object has no attribute '_gaussian_weights'
Traceback (most recent call last):
  File "D:\AI\ComfyUI_windows_portable\ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\AI\ComfyUI_windows_portable\ComfyUI\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\AI\ComfyUI_windows_portable\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "D:\AI\ComfyUI_windows_portable\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-CogVideoXWrapper\nodes.py", line 1075, in process
    latents = pipe(
              ^^^^^
  File "D:\AI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-CogVideoXWrapper\cogvideox_fun\pipeline_cogvideox_inpaint.py", line 863, in __call__
    t_tile_weights = self._gaussian_weights(t_tile_length=t_tile_length, t_batch_size=1).to(latents.device).to(self.vae.dtype)
                     ^^^^^^^^^^^^^^^^^^^^^^
  File "D:\AI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\diffusers\configuration_utils.py", line 143, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'CogVideoX_Fun_Pipeline_Inpaint' object has no attribute '_gaussian_weights'

**Comment by kijai** [comment]
Right, I never actually tried the temporal tiling as I was working on mostly adding the context scheduling, which is a far better method, albeit slower, this should be fixed now though.

**Comment by cheezecrisp** [comment]
> Right, I never actually tried the temporal tiling as I was working on mostly adding the context scheduling, which is a far better method, albeit slower, this should be fixed now though.

Great work, it works now!
