### ISSUE TITLE
CogVideoSampler producing "int is not subscriptable" error

### ISSUE THREAD

**Issue by mwoody450** [kijai/ComfyUI-CogVideoXWrapper#132]
Starting this morning, workflows for image2video generation no longer function.  They first complain that the "DDIM" scheduler no longer exists, and selecting any other option, they error out with "int is not subscriptable".  Full error below.

```
got prompt

!!! Exception during processing !!! 'int' object is not subscriptable
Traceback (most recent call last):
  File "G:\AI\ComfyUI_windows_portable\ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\AI\ComfyUI_windows_portable\ComfyUI\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\AI\ComfyUI_windows_portable\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "G:\AI\ComfyUI_windows_portable\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-CogVideoXWrapper\nodes.py", line 889, in process
    context_frames = context_options["context_frames"] // 4
                     ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
TypeError: 'int' object is not subscriptable

Prompt executed in 0.07 seconds
```

I've changed everything I can think to change, including CLIP model, weight, etc.

Screenshot of relevant portion of workflow:
![image](https://github.com/user-attachments/assets/7b6c3eee-a524-4e06-8bfd-c6a2facc60f2)

**Comment by kijai** [comment]
Remake the sampler node or set each widget again, there were some bigger changes to it, old workflows get confused and assign the widgets wrong.
