### ISSUE TITLE
'AutoencoderKLCogVideoX' object has no attribute '_clear_fake_context_parallel_cache'

### ISSUE THREAD

**Issue by p80ric** [kijai/ComfyUI-CogVideoXWrapper#146]
Hi, upfront I just wanted to say you are doing an awesome job! 
Unfortunately i have some issue withe the cogvideox_I2V_example_01 worklfow. 
I get the following error with the recent version:

# ComfyUI Error Report
## Error Details
- **Node Type:** CogVideoImageEncode
- **Exception Type:** AttributeError
- **Exception Message:** 'AutoencoderKLCogVideoX' object has no attribute '_clear_fake_context_parallel_cache'
## Stack Trace
```
  File "E:\ComfyUI\ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "E:\ComfyUI\ComfyUI\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "E:\ComfyUI\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)

  File "E:\ComfyUI\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "E:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-CogVideoXWrapper\nodes.py", line 839, in encode
    vae._clear_fake_context_parallel_cache()
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "E:\miniconda3\envs\comfy\Lib\site-packages\diffusers\models\modeling_utils.py", line 148, in __getattr__
    return super().__getattr__(name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^

  File "E:\miniconda3\envs\comfy\Lib\site-packages\torch\nn\modules\module.py", line 1695, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")

```
## System Information
- **ComfyUI Version:** v0.2.3-1-g1b80895
- **Arguments:** main.py
- **OS:** nt
- **Python Version:** 3.11.6 | packaged by conda-forge | (main, Oct  3 2023, 10:29:11) [MSC v.1935 64 bit (AMD64)]
- **Embedded Python:** false
- **PyTorch Version:** 2.1.0+cu121
## Devices

- **Name:** cuda:0 NVIDIA GeForce RTX 4090 : cudaMallocAsync
  - **Type:** cuda
  - **VRAM Total:** 25756696576
  - **VRAM Free:** 23667205818
  - **Torch VRAM Total:** 436207616
  - **Torch VRAM Free:** 5039802

## Logs
```
2024-10-13 21:54:12,270 - root - INFO - Total VRAM 24564 MB, total RAM 32598 MB
2024-10-13 21:54:12,270 - root - INFO - pytorch version: 2.1.0+cu121
2024-10-13 21:54:12,289 - root - INFO - xformers version: 0.0.22.post7
2024-10-13 21:54:12,290 - root - INFO - Set vram state to: NORMAL_VRAM
2024-10-13 21:54:12,290 - root - INFO - Device: cuda:0 NVIDIA GeForce RTX 4090 : cudaMallocAsync
2024-10-13 21:54:12,837 - root - INFO - Using xformers cross attention
2024-10-13 21:54:13,258 - root - INFO - [Prompt Server] web root: E:\ComfyUI\ComfyUI\web
2024-10-13 21:54:13,260 - root - INFO - Adding extra search path checkpoints E:\StableDiffusion\Models\SD
2024-10-13 21:54:13,260 - root - INFO - Adding extra search path configs path/to/stable-diffusion-webui/models/Stable-diffusion
2024-10-13 21:54:13,260 - root - INFO - Adding extra search path vae E:\StableDiffusion\Models\Vae
2024-10-13 21:54:13,260 - root - INFO - Adding extra search path loras E:\StableDiffusion\Models\Lora
2024-10-13 21:54:13,260 - root - INFO - Adding extra search path upscale_models path/to/stable-diffusion-webui/models/ESRGAN
2024-10-13 21:54:13,260 - root - INFO - Adding extra search path upscale_models path/to/stable-diffusion-webui/models/RealESRGAN
2024-10-13 21:54:13,261 - root - INFO - Adding extra search path upscale_models path/to/stable-diffusion-webui/models/SwinIR
2024-10-13 21:54:13,261 - root - INFO - Adding extra search path embeddings path/to/stable-diffusion-webui/embeddings
2024-10-13 21:54:13,261 - root - INFO - Adding extra search path hypernetworks path/to/stable-diffusion-webui/models/hypernetworks
2024-10-13 21:54:13,261 - root - INFO - Adding extra search path controlnet E:\StableDiffusion\Models\ControlNet
2024-10-13 21:54:13,261 - root - INFO - Adding extra search path AnimateDiffEvolved_Models E:\StableDiffusion\Models\Animatediff
2024-10-13 21:54:13,261 - root - INFO - Adding extra search path svd E:\StableDiffusion\Models\SD\Video
2024-10-13 21:54:13,261 - root - INFO - Adding extra search path unet E:\StableDiffusion\Models\SD\Flux
2024-10-13 21:54:13,767 - ComfyUI-CogVideoXWrapper.custom_cogvideox_transformer_3d - INFO - sageattn not found, using sdpa
2024-10-13 21:54:13,776 - ComfyUI-CogVideoXWrapper.cogvideox_fun.transformer_3d - INFO - sageattn not found, using sdpa
2024-10-13 21:54:13,778 - ComfyUI-CogVideoXWrapper.cogvideox_fun.fun_pab_transformer_3d - INFO - sageattn not found, using sdpa
2024-10-13 21:54:14,555 - root - INFO - Total VRAM 24564 MB, total RAM 32598 MB
2024-10-13 21:54:14,555 - root - INFO - pytorch version: 2.1.0+cu121
2024-10-13 21:54:14,555 - root - INFO - xformers version: 0.0.22.post7
2024-10-13 21:54:14,555 - root - INFO - Set vram state to: NORMAL_VRAM
2024-10-13 21:54:14,555 - root - INFO - Device: cuda:0 NVIDIA GeForce RTX 4090 : cudaMallocAsync
2024-10-13 21:54:16,149 - root - INFO - 
Import times for custom nodes:
2024-10-13 21:54:16,149 - root - INFO -    0.0 seconds: E:\ComfyUI\ComfyUI\custom_nodes\websocket_image_save.py
2024-10-13 21:54:16,149 - root - INFO -    0.0 seconds: E:\ComfyUI\ComfyUI\custom_nodes\image-resize-comfyui
2024-10-13 21:54:16,149 - root - INFO -    0.0 seconds: E:\ComfyUI\ComfyUI\custom_nodes\stability-ComfyUI-nodes
2024-10-13 21:54:16,149 - root - INFO -    0.0 seconds: E:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Logic
2024-10-13 21:54:16,149 - root - INFO -    0.0 seconds: E:\ComfyUI\ComfyUI\custom_nodes\masquerade-nodes-comfyui
2024-10-13 21:54:16,149 - root - INFO -    0.0 seconds: E:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-SuperBeasts
2024-10-13 21:54:16,149 - root - INFO -    0.0 seconds: E:\ComfyUI\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus
2024-10-13 21:54:16,149 - root - INFO -    0.0 seconds: E:\ComfyUI\ComfyUI\custom_nodes\comfyui-tooling-nodes
2024-10-13 21:54:16,149 - root - INFO -    0.0 seconds: E:\ComfyUI\ComfyUI\custom_nodes\ComfyMath
2024-10-13 21:54:16,149 - root - INFO -    0.0 seconds: E:\ComfyUI\ComfyUI\custom_nodes\save-image-extended-comfyui
2024-10-13 21:54:16,149 - root - INFO -    0.0 seconds: E:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Advanced-ControlNet
2024-10-13 21:54:16,149 - root - INFO -    0.0 seconds: E:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-GGUF
2024-10-13 21:54:16,149 - root - INFO -    0.0 seconds: E:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Frame-Interpolation
2024-10-13 21:54:16,149 - root - INFO -    0.0 seconds: E:\ComfyUI\ComfyUI\custom_nodes\rgthree-comfy
2024-10-13 21:54:16,149 - root - INFO -    0.0 seconds: E:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-MimicMotionWrapper
2024-10-13 21:54:16,149 - root - INFO -    0.0 seconds: E:\ComfyUI\ComfyUI\custom_nodes\ComfyUI_essentials
2024-10-13 21:54:16,149 - root - INFO -    0.0 seconds: E:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-AnimateDiff-Evolved
2024-10-13 21:54:16,149 - root - INFO -    0.0 seconds: E:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-KJNodes
2024-10-13 21:54:16,149 - root - INFO -    0.0 seconds: E:\ComfyUI\ComfyUI\custom_nodes\comfyui_controlnet_aux
2024-10-13 21:54:16,149 - root - INFO -    0.0 seconds: E:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Inspire-Pack
2024-10-13 21:54:16,150 - root - INFO -    0.1 seconds: E:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Manager
2024-10-13 21:54:16,150 - root - INFO -    0.1 seconds: E:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-PyramidFlowWrapper
2024-10-13 21:54:16,150 - root - INFO -    0.2 seconds: E:\ComfyUI\ComfyUI\custom_nodes\ComfyUI_FizzNodes
2024-10-13 21:54:16,150 - root - INFO -    0.2 seconds: E:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-VideoHelperSuite
2024-10-13 21:54:16,150 - root - INFO -    0.3 seconds: E:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-CogVideoXWrapper
2024-10-13 21:54:16,150 - root - INFO -    0.4 seconds: E:\ComfyUI\ComfyUI\custom_nodes\comfyui-reactor-node
2024-10-13 21:54:16,150 - root - INFO -    0.5 seconds: E:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-SUPIR
2024-10-13 21:54:16,150 - root - INFO -    0.7 seconds: E:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Impact-Pack
2024-10-13 21:54:16,150 - root - INFO - 
2024-10-13 21:54:16,157 - root - INFO - Starting server

2024-10-13 21:54:16,157 - root - INFO - To see the GUI go to: http://127.0.0.1:8188
2024-10-13 21:54:17,756 - root - INFO - got prompt
2024-10-13 21:54:25,721 - root - ERROR - !!! Exception during processing !!! 'AutoencoderKLCogVideoX' object has no attribute '_clear_fake_context_parallel_cache'
2024-10-13 21:54:25,724 - root - ERROR - Traceback (most recent call last):
  File "E:\ComfyUI\ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ComfyUI\ComfyUI\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ComfyUI\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "E:\ComfyUI\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-CogVideoXWrapper\nodes.py", line 839, in encode
    vae._clear_fake_context_parallel_cache()
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\miniconda3\envs\comfy\Lib\site-packages\diffusers\models\modeling_utils.py", line 148, in __getattr__
    return super().__getattr__(name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\miniconda3\envs\comfy\Lib\site-packages\torch\nn\modules\module.py", line 1695, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'AutoencoderKLCogVideoX' object has no attribute '_clear_fake_context_parallel_cache'

2024-10-13 21:54:25,725 - root - INFO - Prompt executed in 7.94 seconds
2024-10-13 21:57:05,591 - root - INFO - got prompt
2024-10-13 21:57:17,096 - root - ERROR - !!! Exception during processing !!! 'AutoencoderKLCogVideoX' object has no attribute '_clear_fake_context_parallel_cache'
2024-10-13 21:57:17,097 - root - ERROR - Traceback (most recent call last):
  File "E:\ComfyUI\ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ComfyUI\ComfyUI\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ComfyUI\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "E:\ComfyUI\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-CogVideoXWrapper\nodes.py", line 839, in encode
    vae._clear_fake_context_parallel_cache()
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\miniconda3\envs\comfy\Lib\site-packages\diffusers\models\modeling_utils.py", line 148, in __getattr__
    return super().__getattr__(name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\miniconda3\envs\comfy\Lib\site-packages\torch\nn\modules\module.py", line 1695, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'AutoencoderKLCogVideoX' object has no attribute '_clear_fake_context_parallel_cache'

2024-10-13 21:57:17,098 - root - INFO - Prompt executed in 11.45 seconds
```
## Attached Workflow
Please make sure that workflow does not contain any sensitive information such as API keys or passwords.
```
{"last_node_id":58,"last_link_id":129,"nodes":[{"id":31,"type":"CogVideoTextEncode","pos":{"0":497,"1":520},"size":{"0":463.01251220703125,"1":124},"flags":{},"order":5,"mode":0,"inputs":[{"name":"clip","type":"CLIP","link":56}],"outputs":[{"name":"conditioning","type":"CONDITIONING","links":[123],"slot_index":0,"shape":3}],"properties":{"Node name for S&R":"CogVideoTextEncode"},"widgets_values":["The video is not of a high quality, it has a low resolution. Watermark present in each frame. Strange motion trajectory. ",1,true]},{"id":44,"type":"VHS_VideoCombine","pos":{"0":1927,"1":146},"size":[605.3909912109375,310],"flags":{},"order":9,"mode":0,"inputs":[{"name":"images","type":"IMAGE","link":118},{"name":"audio","type":"AUDIO","link":null,"shape":7},{"name":"meta_batch","type":"VHS_BatchManager","link":null,"shape":7},{"name":"vae","type":"VAE","link":null,"shape":7}],"outputs":[{"name":"Filenames","type":"VHS_FILENAMES","links":null,"shape":3}],"properties":{"Node name for S&R":"VHS_VideoCombine"},"widgets_values":{"frame_rate":8,"loop_count":0,"filename_prefix":"CogVideoX-I2V","format":"video/h264-mp4","pix_fmt":"yuv420p","crf":19,"save_metadata":true,"pingpong":false,"save_output":false,"videopreview":{"hidden":false,"paused":false,"params":{"filename":"CogVideoX-I2V_00001.mp4","subfolder":"","type":"temp","format":"video/h264-mp4","frame_rate":8},"muted":false}}},{"id":36,"type":"LoadImage","pos":{"0":365,"1":685},"size":{"0":402.06353759765625,"1":396.6225891113281},"flags":{},"order":0,"mode":0,"inputs":[],"outputs":[{"name":"IMAGE","type":"IMAGE","links":[71],"slot_index":0,"shape":3},{"name":"MASK","type":"MASK","links":null,"shape":3}],"properties":{"Node name for S&R":"LoadImage"},"widgets_values":["00002-3190249334.png","image"]},{"id":20,"type":"CLIPLoader","pos":{"0":-26,"1":400},"size":{"0":451.30548095703125,"1":82},"flags":{},"order":1,"mode":0,"inputs":[],"outputs":[{"name":"CLIP","type":"CLIP","links":[54,56],"slot_index":0,"shape":3}],"properties":{"Node name for S&R":"CLIPLoader"},"widgets_values":["flux_t5xxl_fp8_e4m3fn.safetensors","sd3"]},{"id":56,"type":"CogVideoDecode","pos":{"0":1581,"1":148},"size":{"0":300.396484375,"1":198},"flags":{},"order":8,"mode":0,"inputs":[{"name":"pipeline","type":"COGVIDEOPIPE","link":128},{"name":"samples","type":"LATENT","link":127}],"outputs":[{"name":"images","type":"IMAGE","links":[118],"slot_index":0,"shape":3}],"properties":{"Node name for S&R":"CogVideoDecode"},"widgets_values":[true,240,360,0.2,0.2,true]},{"id":57,"type":"CogVideoSampler","pos":{"0":1138,"1":150},"size":{"0":399.8780822753906,"1":370},"flags":{},"order":7,"mode":0,"inputs":[{"name":"pipeline","type":"COGVIDEOPIPE","link":121},{"name":"positive","type":"CONDITIONING","link":122},{"name":"negative","type":"CONDITIONING","link":123},{"name":"samples","type":"LATENT","link":null,"shape":7},{"name":"image_cond_latents","type":"LATENT","link":129,"shape":7},{"name":"context_options","type":"COGCONTEXT","link":null,"shape":7},{"name":"controlnet","type":"COGVIDECONTROLNET","link":null,"shape":7}],"outputs":[{"name":"cogvideo_pipe","type":"COGVIDEOPIPE","links":[128],"slot_index":0,"shape":3},{"name":"samples","type":"LATENT","links":[127],"shape":3}],"properties":{"Node name for S&R":"CogVideoSampler"},"widgets_values":[480,720,49,20,6,65334758276105,"fixed","DPM++",1]},{"id":37,"type":"ImageResizeKJ","pos":{"0":796,"1":724},"size":{"0":315,"1":266},"flags":{},"order":3,"mode":0,"inputs":[{"name":"image","type":"IMAGE","link":71},{"name":"get_image_size","type":"IMAGE","link":null,"shape":7},{"name":"width_input","type":"INT","link":null,"widget":{"name":"width_input"}},{"name":"height_input","type":"INT","link":null,"widget":{"name":"height_input"}}],"outputs":[{"name":"IMAGE","type":"IMAGE","links":[125],"slot_index":0,"shape":3},{"name":"width","type":"INT","links":null,"shape":3},{"name":"height","type":"INT","links":null,"shape":3}],"properties":{"Node name for S&R":"ImageResizeKJ"},"widgets_values":[720,480,"lanczos",false,16,0,0,"disabled"]},{"id":30,"type":"CogVideoTextEncode","pos":{"0":493,"1":303},"size":{"0":471.90142822265625,"1":168.08047485351562},"flags":{},"order":4,"mode":0,"inputs":[{"name":"clip","type":"CLIP","link":54}],"outputs":[{"name":"conditioning","type":"CONDITIONING","links":[122],"slot_index":0,"shape":3}],"properties":{"Node name for S&R":"CogVideoTextEncode"},"widgets_values":["a majestic stag is grazing in",1,true]},{"id":1,"type":"DownloadAndLoadCogVideoModel","pos":{"0":633,"1":44},"size":{"0":337.8885192871094,"1":194},"flags":{},"order":2,"mode":0,"inputs":[{"name":"pab_config","type":"PAB_CONFIG","link":null,"shape":7},{"name":"block_edit","type":"TRANSFORMERBLOCKS","link":null,"shape":7},{"name":"lora","type":"COGLORA","link":null,"shape":7}],"outputs":[{"name":"cogvideo_pipe","type":"COGVIDEOPIPE","links":[121,124],"slot_index":0,"shape":3}],"properties":{"Node name for S&R":"DownloadAndLoadCogVideoModel"},"widgets_values":["THUDM/CogVideoX-5b-I2V","bf16","disabled","disabled",false]},{"id":58,"type":"CogVideoImageEncode","pos":{"0":1156,"1":650},"size":{"0":315,"1":122},"flags":{},"order":6,"mode":0,"inputs":[{"name":"pipeline","type":"COGVIDEOPIPE","link":124},{"name":"image","type":"IMAGE","link":125},{"name":"mask","type":"MASK","link":null,"shape":7}],"outputs":[{"name":"samples","type":"LATENT","links":[129],"slot_index":0,"shape":3}],"properties":{"Node name for S&R":"CogVideoImageEncode"},"widgets_values":[16,true]}],"links":[[54,20,0,30,0,"CLIP"],[56,20,0,31,0,"CLIP"],[71,36,0,37,0,"IMAGE"],[118,56,0,44,0,"IMAGE"],[121,1,0,57,0,"COGVIDEOPIPE"],[122,30,0,57,1,"CONDITIONING"],[123,31,0,57,2,"CONDITIONING"],[124,1,0,58,0,"COGVIDEOPIPE"],[125,37,0,58,1,"IMAGE"],[127,57,1,56,1,"LATENT"],[128,57,0,56,0,"COGVIDEOPIPE"],[129,58,0,57,4,"LATENT"]],"groups":[],"config":{},"extra":{"ds":{"scale":0.8264462809917356,"offset":[-266.09951976772555,81.1257176819945]}},"version":0.4}
```

## Additional Context
(Please add any additional context or steps to reproduce the error here)

**Comment by kijai** [comment]
Your diffusers probably needs to be updated, should be 0.30.3 for latest CogVideoX support.

**Comment by p80ric** [comment]
Thank you very much, with 0.30.3 it works well :) .

**Comment by kijai** [comment]
Good to know!

**Comment by smengle** [comment]
Stupid question. but which package is the diffuser and how to update them?
