### ISSUE TITLE
Help......can't import the node after updata today.

### ISSUE THREAD

**Issue by K-O-N-B** [kijai/ComfyUI-CogVideoXWrapper#147]
Traceback (most recent call last):
  File "H:\ComfyUI-qiuye\ComfyUI\nodes.py", line 2001, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "H:\ComfyUI-qiuye\ComfyUI\custom_nodes\ComfyUI-CogVideoXWrapper\__init__.py", line 1, in <module>
    from .nodes import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "H:\ComfyUI-qiuye\ComfyUI\custom_nodes\ComfyUI-CogVideoXWrapper\nodes.py", line 18, in <module>
    from diffusers.schedulers import (
ImportError: cannot import name 'CogVideoXDDIMScheduler' from 'diffusers.schedulers' (H:\ComfyUI-qiuye\ComfyUI\.ext\Lib\site-packages\diffusers\schedulers\__init__.py)

Cannot import H:\ComfyUI-qiuye\ComfyUI\custom_nodes\ComfyUI-CogVideoXWrapper module for custom nodes: cannot import name 'CogVideoXDDIMScheduler' from 'diffusers.schedulers' (H:\ComfyUI-qiuye\ComfyUI\.ext\Lib\site-packages\diffusers\schedulers\__init__.py)

**Comment by kijai** [comment]
After what update? That error suggests your diffusers version is too old.
