### ISSUE TITLE
Unsupported scalar type

### ISSUE THREAD

**Issue by thanga-v2** [kijai/ComfyUI-CogVideoXWrapper#148]
!!! Exception during processing!!! unsupported scalarType
Traceback (most recent call last):
  File "/Users/thangaraj/Documents/projects/comfyUI/ComfyUI/execution.py", line 152, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/thangaraj/Documents/projects/comfyUI/ComfyUI/execution.py", line 82, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/thangaraj/Documents/projects/comfyUI/ComfyUI/execution.py", line 75, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/thangaraj/Documents/projects/comfyUI/ComfyUI/custom_nodes/ComfyUI-CogVideoXWrapper/nodes.py", line 950, in process
    autocast_context = torch.autocast(mm.get_autocast_device(device)) if autocastcondition else nullcontext()
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/thangaraj/miniconda3/lib/python3.12/site-packages/torch/amp/autocast_mode.py", line 229, in __init__
    dtype = torch.get_autocast_dtype(device_type)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: unsupported scalarType
![Screenshot 2024-10-14 at 2 19 11 PM](https://github.com/user-attachments/assets/c1022a8f-8bb4-4bef-9838-99ce754bf98c)

**Comment by kijai** [comment]
Never seen that before, but I'd guess you are using old torch version?

**Comment by thanga-v2** [comment]
> Never seen that before, but I'd guess you are using old torch version?

No, Im using the latest one. @kijai 

Name: torch
Version: 2.4.1
Summary: Tensors and Dynamic neural networks in Python with strong GPU acceleration
Home-page: https://pytorch.org/
Author: PyTorch Team
Author-email: packages@pytorch.org
License: BSD-3
Location: /Users/thangaraj/miniconda3/lib/python3.12/site-packages

**Comment by kijai** [comment]
Which GPU?

**Comment by thanga-v2** [comment]
Mac silicon.

**Comment by thanga-v2** [comment]
> Which GPU?

Mac silicon. @kijai

**Comment by kijai** [comment]
> > Which GPU?
> 
> Mac silicon. @kijai

Ah, well I don't know anyone who has gotten CogVideoX in general to run on Mac, sorry :/

**Comment by thanga-v2** [comment]
which model can I choose to run for text to video ?

**Comment by thanga-v2** [comment]
I am using 
![Screenshot 2024-10-14 at 5 22 17 PM](https://github.com/user-attachments/assets/89dffb9b-bcab-4705-8f80-70e79ff547f7)

**Comment by kijai** [comment]
It just won't work on Mac, you can read about people trying to get it to work here, haven't seen anyone that has gotten it to work on Mac, and I mean the original code too, not just the nodes:

https://github.com/kijai/ComfyUI-CogVideoXWrapper/issues/59

https://github.com/THUDM/CogVideo/issues/222

I don't have access to any Mac device so nothing I can do about it.

**Comment by cchance27** [comment]
Yes it will, its just that AMP is not supported on mac in 2.4.x, it's being added in 2.5.x pytorch, the nightlies are just a mess currently so don't recommend using them as they break a lot of things.

#152
