### ISSUE TITLE
THUDM/CogVideoX-5b-I2V

### ISSUE THREAD

**Issue by KimKyanghyun** [kijai/ComfyUI-CogVideoXWrapper#149]
It is currently not possible to generate videos at a different resolution that the defaults. This should only be the case with 'THUDM/CogVideoX-5b-I2V'.If you think this is incorrect, please open an issue at https://github.com/huggingface/diffusers/issues.

What am I doing wrong when it comes up like this?
I want to convert the image to 1080*1344 resolution.

Encoded latents shape: torch.Size([1, 1, 16, 90, 60])
The config attributes {'snr_shift_scale': 1.0} were passed to EulerDiscreteScheduler, but are not expected and will be ignored. Please verify your scheduler_config.json configuration file.
Temporal tiling and context schedule disabled
  0%|                                                                                           | 0/25 [00:00<?, ?it/s]
!!! Exception during processing !!! It is currently not possible to generate videos at a different resolution that the defaults. This should only be the case with 'THUDM/CogVideoX-5b-I2V'.If you think this is incorrect, please open an issue at https://github.com/huggingface/diffusers/issues.
Traceback (most recent call last):
  File "C:\1111\ComfyUI_windows_portable\ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\1111\ComfyUI_windows_portable\ComfyUI\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\1111\ComfyUI_windows_portable\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "C:\1111\ComfyUI_windows_portable\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\1111\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-CogVideoXWrapper\nodes.py", line 953, in process
    latents = pipeline["pipe"](
              ^^^^^^^^^^^^^^^^^
  File "C:\1111\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\utils\_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\1111\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-CogVideoX-MZ\pipeline_cogvideox.py", line 835, in __call__
    noise_pred = self.transformer(
                 ^^^^^^^^^^^^^^^^^
  File "C:\1111\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\1111\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\1111\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-CogVideoX-MZ\custom_cogvideox_transformer_3d.py", line 588, in forward
    hidden_states = self.patch_embed(encoder_hidden_states, hidden_states)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\1111\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\1111\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\1111\ComfyUI_windows_portable\python_embeded\Lib\site-packages\diffusers\models\embeddings.py", line 423, in forward
    raise ValueError(
ValueError: It is currently not possible to generate videos at a different resolution that the defaults. This should only be the case with 'THUDM/CogVideoX-5b-I2V'.If you think this is incorrect, please open an issue at https://github.com/huggingface/diffusers/issues.

Prompt executed in 2.12 seconds
got prompt
The config attributes {'snr_shift_scale': 1.0} were passed to EulerDiscreteScheduler, but are not expected and will be ignored. Please verify your scheduler_config.json configuration file.
Temporal tiling and context schedule disabled
  0%|                                                                                           | 0/25 [00:00<?, ?it/s]
!!! Exception during processing !!! It is currently not possible to generate videos at a different resolution that the defaults. This should only be the case with 'THUDM/CogVideoX-5b-I2V'.If you think this is incorrect, please open an issue at https://github.com/huggingface/diffusers/issues.
Traceback (most recent call last):
  File "C:\1111\ComfyUI_windows_portable\ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\1111\ComfyUI_windows_portable\ComfyUI\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\1111\ComfyUI_windows_portable\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "C:\1111\ComfyUI_windows_portable\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\1111\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-CogVideoXWrapper\nodes.py", line 953, in process
    latents = pipeline["pipe"](
              ^^^^^^^^^^^^^^^^^
  File "C:\1111\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\utils\_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\1111\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-CogVideoX-MZ\pipeline_cogvideox.py", line 835, in __call__
    noise_pred = self.transformer(
                 ^^^^^^^^^^^^^^^^^
  File "C:\1111\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\1111\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\1111\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-CogVideoX-MZ\custom_cogvideox_transformer_3d.py", line 588, in forward
    hidden_states = self.patch_embed(encoder_hidden_states, hidden_states)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\1111\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\1111\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\1111\ComfyUI_windows_portable\python_embeded\Lib\site-packages\diffusers\models\embeddings.py", line 423, in forward
    raise ValueError(
ValueError: It is currently not possible to generate videos at a different resolution that the defaults. This should only be the case with 'THUDM/CogVideoX-5b-I2V'.If you think this is incorrect, please open an issue at https://github.com/huggingface/diffusers/issues.

Prompt executed in 0.40 seconds

**Comment by KrakeyMTL** [comment]
I saw somewhere that the resolution max was 1280 so possibly that off the top of my head? I can't remember what blurb I saw that info for the sizing in however sorry.

**Comment by littleyeson** [comment]
Use 720*480 Image. Only suppost one resolution.

**Comment by KrakeyMTL** [comment]
> Use 720*480 Image. Only support one resolution.

This is false actually sorry, I've personally done 1280x1280 on a H100 gpu 80gb vram 120gb sys ram. You just need enough vram and swap to pull it off. (takes 14min on a h100 as well, absurd long time not good or beneficial right now. better to do lower and upscale the video itself afterwards.)

BUT the modified workflow for doing this stops at 1280x1280, hence my first comment,

I know it's possible - just a absolute pig to accomplish at the moment for terrible result to price

**Comment by kijai** [comment]
> > Use 720*480 Image. Only support one resolution.
> 
> This is false actually sorry, I've personally done 1280x1280 on a H100 gpu 80gb vram 120gb sys ram. You just need enough vram and swap to pull it off. (takes 14min on a h100 as well, absurd long time not good or beneficial right now. better to do lower and upscale the video itself afterwards.)
> 
> BUT the modified workflow for doing this stops at 1280x1280, hence my first comment,
> 
> I know it's possible - just a absolute pig to accomplish at the moment for terrible result to price

With the original I2V model it's not possible, it simply doesn't work outside it's default resolution, which is what he was referring to. The CogVideoX-Fun version does however, which is probably what you are talking about.

**Comment by KrakeyMTL** [comment]
Kijai whoop you are probably correct, so many damn models my bad. 

Weren't you the one that made the modified template for 1280 anyways? lol

**Comment by kijai** [comment]
> Kijai whoop you are probably correct, so many damn models my bad.
> 
> Weren't you the one that made the modified template for 1280 anyways? lol

I don't think so, I've tried up to 1024 myself with it before though. It really has gotten complex with all the available models and their variations, it's getting hard to keep track of what works with what indeed...
