### ISSUE TITLE
TypeError: not all arguments converted during string formatting

### ISSUE THREAD

**Issue by mr-bob-chang** [kijai/ComfyUI-CogVideoXWrapper#162]
I will encounter the following error with the node CogVideo Sampler when using the cogvideox_interpolation_example_01.json workflow, how can I solve it? 

Prompt executed in 0.17 seconds
Error handling request
Traceback (most recent call last):
  File "E:\ComfyUI_windows_portable-b\python_embeded\Lib\site-packages\aiohttp\web_protocol.py", line 452, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ComfyUI_windows_portable-b\python_embeded\Lib\site-packages\aiohttp\web_app.py", line 543, in _handle
    resp = await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ComfyUI_windows_portable-b\python_embeded\Lib\site-packages\aiohttp\web_middlewares.py", line 114, in impl
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ComfyUI_windows_portable-b\ComfyUI\server.py", line 63, in cache_control
    response: web.Response = await handler(request)
                             ^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ComfyUI_windows_portable-b\ComfyUI\server.py", line 141, in origin_only_middleware
    response = await handler(request)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ComfyUI_windows_portable-b\ComfyUI\server.py", line 75, in cors_middleware
    response = await handler(request)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ComfyUI_windows_portable-b\python_embeded\Lib\site-packages\aiohttp\web_middlewares.py", line 114, in impl
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ComfyUI_windows_portable-b\ComfyUI\api_server\routes\internal\internal_routes.py", line 37, in get_logs
    return web.json_response(app.logger.get_logs())
                             ^^^^^^^^^^^^^^^^^^^^^
  File "E:\ComfyUI_windows_portable-b\ComfyUI\app\logger.py", line 10, in get_logs
    return "\n".join([formatter.format(x) for x in logs])
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ComfyUI_windows_portable-b\ComfyUI\app\logger.py", line 10, in <listcomp>
    return "\n".join([formatter.format(x) for x in logs])
                      ^^^^^^^^^^^^^^^^^^^
  File "logging\__init__.py", line 687, in format
  File "logging\__init__.py", line 377, in getMessage
TypeError: not all arguments converted during string formatting

**Comment by kijai** [comment]
It's been fixed, just update the nodes.
