### ISSUE TITLE
CogVideoXFun vid2vid sampler node error

### ISSUE THREAD

**Issue by dariiboi** [kijai/ComfyUI-CogVideoXWrapper#174]
Getting this error using the cogvideo-fun-5b inP model and the V2V sampler am I missing context window settings?
the other Vid2Vid workflow with the non-fun model works fine.
Has anyone else gotten this node to work?

got prompt Applying FreeNoise !!! Exception during processing !!! unsupported operand type(s) for -: 'NoneType' and 'NoneType' Traceback (most recent call last): File "C:\Users\User\Desktop\ComfyUI_windows_portable\ComfyUI\execution.py", line 323, in execute output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "C:\Users\User\Desktop\ComfyUI_windows_portable\ComfyUI\execution.py", line 198, in get_output_data return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "C:\Users\User\Desktop\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-0246\utils.py", line 353, in new_func res_value = old_func(*final_args, **kwargs) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "C:\Users\User\Desktop\ComfyUI_windows_portable\ComfyUI\execution.py", line 169, in _map_node_over_list process_inputs(input_dict, i) File "C:\Users\User\Desktop\ComfyUI_windows_portable\ComfyUI\execution.py", line 158, in process_inputs results.append(getattr(obj, func)(**inputs)) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "C:\Users\User\Desktop\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-CogVideoXWrapper\nodes.py", line 1529, in process latents = pipe( ^^^^^ File "C:\Users\User\Desktop\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context return func(*args, **kwargs) ^^^^^^^^^^^^^^^^^^^^^ File "C:\Users\User\Desktop\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-CogVideoXWrapper\cogvideox_fun\pipeline_cogvideox_inpaint.py", line 762, in __call__ latents_outputs = self.prepare_latents( ^^^^^^^^^^^^^^^^^^^^^ File "C:\Users\User\Desktop\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-CogVideoXWrapper\cogvideox_fun\pipeline_cogvideox_inpaint.py", line 320, in prepare_latents delta = context_size - context_overlap ~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~ TypeError: unsupported operand type(s) for -: 'NoneType' and 'NoneType'

**Comment by iEddie-cmd** [comment]
Same. Did you find a solution?

**Comment by kijai** [comment]
Probably old workflow, try remaking the sampler node.

**Comment by iEddie-cmd** [comment]
#186 opened 4 days ago by [magicwang1111](https://github.com/kijai/ComfyUI-CogVideoXWrapper/issues?q=is%3Apr+is%3Aopen+author%3Amagicwang1111) solved the issue
