### ISSUE TITLE
 The size of tensor a (45) must match the size of tensor b (44) at non-singleton dimension 4

### ISSUE THREAD

**Issue by gladmustang** [kijai/ComfyUI-CogVideoXWrapper#177]
The size of tensor a (45) must match the size of tensor b (44) at non-singleton dimension 4

I run the sample text to video workflow and get this error, I also reduce the prompt length, but it does not work.

Any reason for this ?

**Comment by kijai** [comment]
Full error?

**Comment by gladmustang** [comment]
Below is the full error:
Temporal tiling and context schedule disabled
  0%|                                                                                           | 0/50 [00:07<?, ?it/s]
!!! Exception during processing !!! The size of tensor a (45) must match the size of tensor b (44) at non-singleton dimension 4
Traceback (most recent call last):
  File "E:\tools\ComfyUI_windows_portable\ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\tools\ComfyUI_windows_portable\ComfyUI\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\tools\ComfyUI_windows_portable\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "E:\tools\ComfyUI_windows_portable\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\tools\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-CogVideoXWrapper\nodes.py", line 1311, in process
    latents = pipeline["pipe"](
              ^^^^^^^^^^^^^^^^^
  File "E:\tools\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\utils\_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "E:\tools\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-CogVideoXWrapper\pipeline_cogvideox.py", line 891, in __call__
    latents = self.scheduler.step(noise_pred, t, latents.to(self.vae.dtype), **extra_step_kwargs, return_dict=False)[0]
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\tools\ComfyUI_windows_portable\python_embeded\Lib\site-packages\diffusers\schedulers\scheduling_dpmsolver_multistep.py", line 972, in step
    model_output = self.convert_model_output(model_output, sample=sample)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\tools\ComfyUI_windows_portable\python_embeded\Lib\site-packages\diffusers\schedulers\scheduling_dpmsolver_multistep.py", line 569, in convert_model_output
    x0_pred = alpha_t * sample - sigma_t * model_output
              ~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~
RuntimeError: The size of tensor a (45) must match the size of tensor b (44) at non-singleton dimension 4

**Comment by kijai** [comment]
The current I2V models does not support anything but 49 x 720x480, only the "Fun" version does, which then does not support Tora, I know it's messy right now with all the different models and their variations coming out every other week.

**Comment by Kallamamran** [comment]
I'm using the current I2V and 49 x 720 x 480 and I still get this error 🤔

```
got prompt
Merging rank 256 LoRA weights from Q:\ComfyUI\models\CogVideo\loras\orbit_left_lora_weights.safetensors with strength 1.0
Encoded latents shape: torch.Size([1, 1, 16, 60, 90])
!!! Exception during processing !!! The size of tensor a (14) must match the size of tensor b (13) at non-singleton dimension 1
Traceback (most recent call last):
  File "Q:\ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "Q:\ComfyUI\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "Q:\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "Q:\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
  File "Q:\ComfyUI\custom_nodes\ComfyUI-CogVideoXWrapper\nodes.py", line 866, in process
    latents = pipeline["pipe"](
  File "Q:\ComfyUI\venv\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "Q:\ComfyUI\custom_nodes\ComfyUI-CogVideoXWrapper\pipeline_cogvideox.py", line 485, in __call__
    latents, timesteps, noise = self.prepare_latents(
  File "Q:\ComfyUI\custom_nodes\ComfyUI-CogVideoXWrapper\pipeline_cogvideox.py", line 239, in prepare_latents
    latents = self.scheduler.add_noise(latents, noise, latent_timestep)
  File "Q:\ComfyUI\venv\lib\site-packages\diffusers\schedulers\scheduling_dpm_cogvideox.py", line 465, in add_noise
    noisy_samples = sqrt_alpha_prod * original_samples + sqrt_one_minus_alpha_prod * noise
RuntimeError: The size of tensor a (14) must match the size of tensor b (13) at non-singleton dimension 1
```

![image](https://github.com/user-attachments/assets/28a820a1-096f-40e6-b56f-43da888e0391)

**Comment by kijai** [comment]
> I'm using the current I2V and 49 x 720 x 480 and I still get this error 🤔
> 
> ```
> got prompt
> Merging rank 256 LoRA weights from Q:\ComfyUI\models\CogVideo\loras\orbit_left_lora_weights.safetensors with strength 1.0
> Encoded latents shape: torch.Size([1, 1, 16, 60, 90])
> !!! Exception during processing !!! The size of tensor a (14) must match the size of tensor b (13) at non-singleton dimension 1
> Traceback (most recent call last):
>   File "Q:\ComfyUI\execution.py", line 323, in execute
>     output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
>   File "Q:\ComfyUI\execution.py", line 198, in get_output_data
>     return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
>   File "Q:\ComfyUI\execution.py", line 169, in _map_node_over_list
>     process_inputs(input_dict, i)
>   File "Q:\ComfyUI\execution.py", line 158, in process_inputs
>     results.append(getattr(obj, func)(**inputs))
>   File "Q:\ComfyUI\custom_nodes\ComfyUI-CogVideoXWrapper\nodes.py", line 866, in process
>     latents = pipeline["pipe"](
>   File "Q:\ComfyUI\venv\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
>     return func(*args, **kwargs)
>   File "Q:\ComfyUI\custom_nodes\ComfyUI-CogVideoXWrapper\pipeline_cogvideox.py", line 485, in __call__
>     latents, timesteps, noise = self.prepare_latents(
>   File "Q:\ComfyUI\custom_nodes\ComfyUI-CogVideoXWrapper\pipeline_cogvideox.py", line 239, in prepare_latents
>     latents = self.scheduler.add_noise(latents, noise, latent_timestep)
>   File "Q:\ComfyUI\venv\lib\site-packages\diffusers\schedulers\scheduling_dpm_cogvideox.py", line 465, in add_noise
>     noisy_samples = sqrt_alpha_prod * original_samples + sqrt_one_minus_alpha_prod * noise
> RuntimeError: The size of tensor a (14) must match the size of tensor b (13) at non-singleton dimension 1
> ```
> 
> ![image](https://private-user-images.githubusercontent.com/25354644/384975504-28a820a1-096f-40e6-b56f-43da888e0391.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEzNDA5MTQsIm5iZiI6MTczMTM0MDYxNCwicGF0aCI6Ii8yNTM1NDY0NC8zODQ5NzU1MDQtMjhhODIwYTEtMDk2Zi00MGU2LWI1NmYtNDNkYTg4OGUwMzkxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTExVDE1NTY1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZlZmFkNWYyZWE1NTJiMzUzMWM4NGNjNzk2MDg4NTI4MWIzNjE2ODgzOTY5ODQ0YjVkOTVlMDQ2OTBmZDRmNzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.QtFEApiUkpsyMCrHRJfTP-6OdBIqzqDnVy8XgMfK2T0)

Condition image, the one you use for I2V models, goes in the other input, not samples. Samples is for doing vid2vid.
