### ISSUE TITLE
Hello, does tora image to video workflow support tora GGUF model?

### ISSUE THREAD

**Issue by leetraman822** [kijai/ComfyUI-CogVideoXWrapper#181]

**Comment by kijai** [comment]
Yes? Is there a problem with that?

**Comment by leetraman822** [comment]
> Yes? Is there a problem with that?

Hey, thanks for creating this project. Yes, I've encountered an error while using GGUF. For the past few days, I’ve been using the default model provided by this workflow, “cogvideox_5b_Tora_I2V_testing_01” (THUDM/CogVideoX-5b-I2V and kijai/CogVideoX-5b-Tora). 
When I tried to replace THUDM/CogVideoX-5b-I2V with CogVideoX_5b_Tora_GGUF_Q4_0.safetensors, I got the following error at the sampler stage: “RuntimeError: Given groups=1, weight of size [3072, 16, 2, 2], expected input[26, 32, 60, 90] to have 16 channels, but got 32 channels instead.” 
I’m not sure what caused this error. Could it be that I set something incorrectly somewhere? My graphics card is an RTX 3060 12GB.

**Comment by leetraman822** [comment]
This is full log.


To see the GUI go to: http://127.0.0.1:8188
FETCH DATA from: E:\StableDiffusion\ComfyUI\custom_nodes\ComfyUI-Manager\extension-node-map.json [DONE]
got prompt
Downloading model to: E:\StableDiffusion\ComfyUI\models\CogVideo\GGUF\CogVideoX_5b_Tora_GGUF_Q4_0.safetensors
Fetching 1 files: 100%|█████████████████████████████████████████████████████████████████| 1/1 [08:23<00:00, 503.74s/it]
received 1 trajectorie(s)
torch.Size([49, 480, 720, 3])
video_flow shape: torch.Size([1, 16, 13, 60, 90])
Encoded latents shape: torch.Size([1, 1, 16, 60, 90])
Requested to load SD3ClipModel_
Loading 1 new model
loaded partially 931.5735252380371 925.693359375 0
loaded partially 1817.266884613037 1805.693359375 0
Only one image conditioning frame received, img2vid
Temporal tiling and context schedule disabled
  0%|                                                                                           | 0/20 [00:04<?, ?it/s]
!!! Exception during processing !!! Given groups=1, weight of size [3072, 16, 2, 2], expected input[26, 32, 60, 90] to have 16 channels, but got 32 channels instead
Traceback (most recent call last):
  File "E:\StableDiffusion\ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\StableDiffusion\ComfyUI\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\StableDiffusion\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "E:\StableDiffusion\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\StableDiffusion\ComfyUI\custom_nodes\ComfyUI-CogVideoXWrapper\nodes.py", line 1310, in process
    latents = pipeline["pipe"](
              ^^^^^^^^^^^^^^^^^
  File "E:\ENV\envs\comfyui\Lib\site-packages\torch\utils\_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "E:\StableDiffusion\ComfyUI\custom_nodes\ComfyUI-CogVideoXWrapper\pipeline_cogvideox.py", line 867, in __call__
    noise_pred = self.transformer(
                 ^^^^^^^^^^^^^^^^^
  File "E:\ENV\envs\comfyui\Lib\site-packages\torch\nn\modules\module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ENV\envs\comfyui\Lib\site-packages\torch\nn\modules\module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ENV\envs\comfyui\Lib\site-packages\accelerate\hooks.py", line 170, in new_forward
    output = module._old_forward(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\StableDiffusion\ComfyUI\custom_nodes\ComfyUI-CogVideoXWrapper\custom_cogvideox_transformer_3d.py", line 603, in forward
    hidden_states = self.patch_embed(encoder_hidden_states, hidden_states)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ENV\envs\comfyui\Lib\site-packages\torch\nn\modules\module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ENV\envs\comfyui\Lib\site-packages\torch\nn\modules\module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ENV\envs\comfyui\Lib\site-packages\diffusers\models\embeddings.py", line 412, in forward
    image_embeds = self.proj(image_embeds)
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ENV\envs\comfyui\Lib\site-packages\torch\nn\modules\module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ENV\envs\comfyui\Lib\site-packages\torch\nn\modules\module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ENV\envs\comfyui\Lib\site-packages\accelerate\hooks.py", line 170, in new_forward
    output = module._old_forward(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ENV\envs\comfyui\Lib\site-packages\torch\nn\modules\conv.py", line 458, in forward
    return self._conv_forward(input, self.weight, self.bias)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ENV\envs\comfyui\Lib\site-packages\torch\nn\modules\conv.py", line 454, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Given groups=1, weight of size [3072, 16, 2, 2], expected input[26, 32, 60, 90] to have 16 channels, but got 32 channels instead

Prompt executed in 804.80 seconds

**Comment by leetraman822** [comment]
![微信截图_20241025193213](https://github.com/user-attachments/assets/38e5b18e-5143-43a0-aff9-ddf030914788)

**Comment by kijai** [comment]
The Tora 5b model is only for text2video, it can't be used in the image2video workflow. Only way to use Tora with image2video is with the original I2V model.
