### ISSUE TITLE
Error SyntaxError: f-string: unmatched '['

### ISSUE THREAD

**Issue by mikheys** [kijai/ComfyUI-CogVideoXWrapper#203]
Traceback (most recent call last):
  File "G:\ComfyUI\ComfyUI\nodes.py", line 2018, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "G:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-CogVideoXWrapper\__init__.py", line 2, in <module>
    from .model_loading import NODE_CLASS_MAPPINGS as MODEL_CLASS, NODE_DISPLAY_NAME_MAPPINGS as MODEL_DISPLAY
  File "G:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-CogVideoXWrapper\model_loading.py", line 18, in <module>
    from .cogvideox_fun.pipeline_cogvideox_inpaint import CogVideoX_Fun_Pipeline_Inpaint
  File "G:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-CogVideoXWrapper\cogvideox_fun\pipeline_cogvideox_inpaint.py", line 897
    logger.info(f"Tora trajectory shape: {tora["video_flow_features"].shape}")
                                                ^^^^^^^^^^^^^^^^^^^
SyntaxError: f-string: unmatched '['

**Comment by mvdberk** [comment]
got the same error after updating the wrapper

**Comment by kijai** [comment]
Odd that it didn't error out for me... the line is indeed wrong though, fixed that. Also make sure to remake the FunSampler -node if you had it in existing workflow, or use the new examples, as that node inputs have now changed a lot.
