### ISSUE TITLE
Error when the CogVideoXFUN sampler uses the PAB

### ISSUE THREAD

**Issue by cheezecrisp** [kijai/ComfyUI-CogVideoXWrapper#213]
I think this is a new issue with some recent update, as it was running fine before.
BTW, it's no problem with CogVideo Sampler.

Init Pyramid Attention Broadcast. steps: 50. spatial broadcast: True, spatial range: 2, spatial threshold: [100, 850]. temporal broadcast: False, temporal range: 4, temporal_threshold: [100, 850]. cross broadcast: False, cross range: 6, cross threshold: [100, 850]. mlp broadcast: False.
Temporal tiling and context schedule disabled
  0%|                                                                                           | 0/20 [00:01<?, ?it/s]
!!! Exception during processing !!! CogVideoXTransformer3DModel.forward() got an unexpected keyword argument 'video_flow_features'
Traceback (most recent call last):
  File "D:\AI\ComfyUI_windows_portable\ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\AI\ComfyUI_windows_portable\ComfyUI\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\AI\ComfyUI_windows_portable\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "D:\AI\ComfyUI_windows_portable\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-CogVideoXWrapper\nodes.py", line 1154, in process
    latents = pipe(
              ^^^^^
  File "D:\AI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\utils\_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-CogVideoXWrapper\cogvideox_fun\pipeline_cogvideox_inpaint.py", line 1092, in __call__
    noise_pred = self.transformer(
                 ^^^^^^^^^^^^^^^^^
  File "D:\AI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\AI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\AI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\accelerate\hooks.py", line 169, in new_forward
    output = module._old_forward(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: CogVideoXTransformer3DModel.forward() got an unexpected keyword argument 'video_flow_features'

Prompt executed in 26.90 seconds

**Comment by kijai** [comment]
I'm actually aware of this yes, what I'm considering at this point however is dropping PAB altogether in favour of FasterCache, which seems to do same thing but...well, faster.

**Comment by cheezecrisp** [comment]
> I'm actually aware of this yes, what I'm considering at this point however is dropping PAB altogether in favour of FasterCache, which seems to do same thing but...well, faster.

I guess the FasterCache is useful for 50 steps, but how to set proper paramters for as low as 20 steps?

**Comment by kijai** [comment]
> > I'm actually aware of this yes, what I'm considering at this point however is dropping PAB altogether in favour of FasterCache, which seems to do same thing but...well, faster.
> 
> I guess the FasterCache is useful for 50 steps, but how to set proper paramters for as low as 20 steps?

Don't know the exact math, but something like start at step 5-7, HF to around middle and LF near end, like with the 50 step defaults.
