### ISSUE TITLE
can't use lora in cogvideox sample

### ISSUE THREAD

**Issue by magicwang1111** [kijai/ComfyUI-CogVideoXWrapper#221]
2024-11-12T03:20:25.969941 - got prompt
2024-11-12T03:20:26.452049 - [{'path': '/mnt/data/wangxi/ComfyUI/models/CogVideo/loras/ExVideo-CogVideoX-LoRA-129f-v1.safetensors', 'strength': 1.0, 'name': 'ExVideo-CogVideoX-LoRA-129f-v1', 'fuse_lora': False}]2024-11-12T03:20:26.452114 - 
2024-11-12T03:20:30.730722 - Merging rank 64 LoRA weights from /mnt/data/wangxi/ComfyUI/models/CogVideo/loras/ExVideo-CogVideoX-LoRA-129f-v1.safetensors with strength 1.0
2024-11-12T03:20:30.751220 - !!! Exception during processing !!! Adapter name(s) {'ExVideo-CogVideoX-LoRA-129f-v1'} not in the list of present adapters: set().
2024-11-12T03:20:30.752381 - Traceback (most recent call last):
  File "/mnt/data/wangxi/ComfyUI/execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/data/wangxi/ComfyUI/execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/data/wangxi/ComfyUI/execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "/mnt/data/wangxi/ComfyUI/execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/data/wangxi/ComfyUI/custom_nodes/ComfyUI-CogVideoXWrapper/model_loading.py", line 231, in loadmodel
    pipe.set_adapters(adapter_list, adapter_weights=adapter_weights)
  File "/mnt/data/wangxi/miniconda3/envs/comfyuimain/lib/python3.11/site-packages/diffusers/loaders/lora_base.py", line 539, in set_adapters
    raise ValueError(
ValueError: Adapter name(s) {'ExVideo-CogVideoX-LoRA-129f-v1'} not in the list of present adapters: set().

2024-11-12T03:20:30.753348 - Prompt executed in 4.67 seconds

**Comment by DmytroSokhach** [comment]
ExVideo related. Looks similar to #280  LoRA issue "not in the list of present adapters: set()"
