### ISSUE TITLE
DownloadAndLoadCogVideoModel error for I2V model

### ISSUE THREAD

**Issue by ffhelly** [kijai/ComfyUI-CogVideoXWrapper#222]
DownloadAndLoadCogVideoModel
Error while deserializing header: HeaderTooSmall

# ComfyUI Error Report
## Error Details
- **Node Type:** DownloadAndLoadCogVideoModel
- **Exception Type:** safetensors_rust.SafetensorError
- **Exception Message:** Error while deserializing header: HeaderTooSmall
## Stack Trace
```
  File "/kiwi/helly/images/comfyui/comfyTest/ComfyUI-Main/execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)

  File "/kiwi/helly/images/comfyui/comfyTest/ComfyUI-Main/execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)

  File "/kiwi/helly/images/comfyui/comfyTest/ComfyUI-Main/execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)

  File "/kiwi/helly/images/comfyui/comfyTest/ComfyUI-Main/execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))

  File "/kiwi/helly/images/comfyui/comfyTest/ComfyUI-Main/custom_nodes/ComfyUI-CogVideoXWrapper/model_loading.py", line 179, in loadmodel
    transformer = CogVideoXTransformer3DModel.from_pretrained(base_path, subfolder="transformer")

  File "/root/miniconda3/envs/comfyui/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)

  File "/root/miniconda3/envs/comfyui/lib/python3.10/site-packages/diffusers/models/modeling_utils.py", line 886, in from_pretrained
    accelerate.load_checkpoint_and_dispatch(

  File "/root/miniconda3/envs/comfyui/lib/python3.10/site-packages/accelerate/big_modeling.py", line 613, in load_checkpoint_and_dispatch
    load_checkpoint_in_model(

  File "/root/miniconda3/envs/comfyui/lib/python3.10/site-packages/accelerate/utils/modeling.py", line 1815, in load_checkpoint_in_model
    loaded_checkpoint = load_state_dict(checkpoint_file, device_map=device_map)

  File "/root/miniconda3/envs/comfyui/lib/python3.10/site-packages/accelerate/utils/modeling.py", line 1509, in load_state_dict
    with safe_open(checkpoint_file, framework="pt") as f:

```
## System Information
- **ComfyUI Version:** v0.2.2-61-g2d810b0
- **Arguments:** main.py
- **OS:** posix
- **Python Version:** 3.10.14 (main, May  6 2024, 19:42:50) [GCC 11.2.0]
- **Embedded Python:** false
- **PyTorch Version:** 2.3.1+cu121
## Devices

- **Name:** cuda:0 NVIDIA GeForce RTX 4090 : cudaMallocAsync
  - **Type:** cuda
  - **VRAM Total:** 25393692672
  - **VRAM Free:** 24577703936
  - **Torch VRAM Total:** 0
  - **Torch VRAM Free:** 0

## Logs
```
2024-11-12 14:21:06,257 - root - INFO - Total VRAM 24217 MB, total RAM 1031770 MB
2024-11-12 14:21:06,258 - root - INFO - pytorch version: 2.3.1+cu121
2024-11-12 14:21:07,993 - root - INFO - xformers version: 0.0.26.post1
2024-11-12 14:21:07,994 - root - INFO - Set vram state to: NORMAL_VRAM
2024-11-12 14:21:07,994 - root - INFO - Device: cuda:0 NVIDIA GeForce RTX 4090 : cudaMallocAsync
2024-11-12 14:21:08,125 - root - INFO - Using xformers cross attention
2024-11-12 14:21:09,010 - root - INFO - [Prompt Server] web root: /kiwi/helly/images/comfyui/comfyTest/ComfyUI-Main/web
2024-11-12 14:21:13,915 - albumentations.check_version - ERROR - Error fetching version info
Traceback (most recent call last):
  File "/root/miniconda3/envs/comfyui/lib/python3.10/urllib/request.py", line 1348, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/root/miniconda3/envs/comfyui/lib/python3.10/http/client.py", line 1283, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/root/miniconda3/envs/comfyui/lib/python3.10/http/client.py", line 1329, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/root/miniconda3/envs/comfyui/lib/python3.10/http/client.py", line 1278, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/root/miniconda3/envs/comfyui/lib/python3.10/http/client.py", line 1038, in _send_output
    self.send(msg)
  File "/root/miniconda3/envs/comfyui/lib/python3.10/http/client.py", line 976, in send
    self.connect()
  File "/root/miniconda3/envs/comfyui/lib/python3.10/http/client.py", line 1455, in connect
    self.sock = self._context.wrap_socket(self.sock,
  File "/root/miniconda3/envs/comfyui/lib/python3.10/ssl.py", line 513, in wrap_socket
    return self.sslsocket_class._create(
  File "/root/miniconda3/envs/comfyui/lib/python3.10/ssl.py", line 1104, in _create
    self.do_handshake()
  File "/root/miniconda3/envs/comfyui/lib/python3.10/ssl.py", line 1375, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1007)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/miniconda3/envs/comfyui/lib/python3.10/site-packages/albumentations/check_version.py", line 29, in fetch_version_info
    with opener.open(url, timeout=2) as response:
  File "/root/miniconda3/envs/comfyui/lib/python3.10/urllib/request.py", line 519, in open
    response = self._open(req, data)
  File "/root/miniconda3/envs/comfyui/lib/python3.10/urllib/request.py", line 536, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/root/miniconda3/envs/comfyui/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/root/miniconda3/envs/comfyui/lib/python3.10/urllib/request.py", line 1391, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "/root/miniconda3/envs/comfyui/lib/python3.10/urllib/request.py", line 1351, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1007)>
2024-11-12 14:21:14,727 - numexpr.utils - INFO - Note: detected 144 virtual cores but NumExpr set to maximum of 64, check "NUMEXPR_MAX_THREADS" environment variable.
2024-11-12 14:21:14,727 - numexpr.utils - INFO - Note: NumExpr detected 144 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.
2024-11-12 14:21:14,727 - numexpr.utils - INFO - NumExpr defaulting to 8 threads.
2024-11-12 14:21:32,077 - root - INFO - Total VRAM 24217 MB, total RAM 1031770 MB
2024-11-12 14:21:32,078 - root - INFO - pytorch version: 2.3.1+cu121
2024-11-12 14:21:32,078 - root - INFO - xformers version: 0.0.26.post1
2024-11-12 14:21:32,078 - root - INFO - Set vram state to: NORMAL_VRAM
2024-11-12 14:21:32,078 - root - INFO - Device: cuda:0 NVIDIA GeForce RTX 4090 : cudaMallocAsync
2024-11-12 14:21:35,587 - OpenGL.acceleratesupport - INFO - No OpenGL_accelerate module loaded: No module named 'OpenGL_accelerate'
2024-11-12 14:21:36,107 - root - INFO - --------------
2024-11-12 14:21:36,107 - root - INFO - [91m ### Mixlab Nodes: [93mLoaded
2024-11-12 14:21:36,108 - root - INFO - ChatGPT.available True
2024-11-12 14:21:36,108 - root - INFO - edit_mask.available True
2024-11-12 14:21:36,110 - root - INFO - LaMaInpainting.available True
2024-11-12 14:21:36,257 - root - INFO - ClipInterrogator.available True
2024-11-12 14:21:36,258 - root - INFO - PromptGenerate.available True
2024-11-12 14:21:36,258 - root - INFO - ChinesePrompt.available True
2024-11-12 14:21:36,258 - root - INFO - RembgNode_.available True
2024-11-12 14:21:36,512 - root - INFO - TripoSR.available
2024-11-12 14:21:36,513 - root - INFO - MiniCPMNode.available
2024-11-12 14:21:36,613 - root - INFO - Scenedetect.available
2024-11-12 14:21:36,718 - root - INFO - FishSpeech.available
2024-11-12 14:21:36,719 - root - INFO - [93m -------------- [0m
2024-11-12 14:21:37,002 - ComfyUI-CogVideoXWrapper.custom_cogvideox_transformer_3d - INFO - sageattn not found, using sdpa
2024-11-12 14:21:37,042 - ComfyUI-CogVideoXWrapper.cogvideox_fun.transformer_3d - INFO - sageattn not found, using sdpa
2024-11-12 14:21:37,051 - ComfyUI-CogVideoXWrapper.cogvideox_fun.fun_pab_transformer_3d - INFO - sageattn not found, using sdpa
2024-11-12 14:21:47,192 - root - INFO - 


2024-11-12 14:22:19,658 - root - ERROR - !!! Exception during processing !!! Error while deserializing header: HeaderTooSmall
2024-11-12 14:22:19,659 - root - ERROR - Traceback (most recent call last):
  File "/kiwi/helly/images/comfyui/comfyTest/ComfyUI-Main/execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "/kiwi/helly/images/comfyui/comfyTest/ComfyUI-Main/execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "/kiwi/helly/images/comfyui/comfyTest/ComfyUI-Main/execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "/kiwi/helly/images/comfyui/comfyTest/ComfyUI-Main/execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
  File "/kiwi/helly/images/comfyui/comfyTest/ComfyUI-Main/custom_nodes/ComfyUI-CogVideoXWrapper/model_loading.py", line 179, in loadmodel
    transformer = CogVideoXTransformer3DModel.from_pretrained(base_path, subfolder="transformer")
  File "/root/miniconda3/envs/comfyui/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
  File "/root/miniconda3/envs/comfyui/lib/python3.10/site-packages/diffusers/models/modeling_utils.py", line 886, in from_pretrained
    accelerate.load_checkpoint_and_dispatch(
  File "/root/miniconda3/envs/comfyui/lib/python3.10/site-packages/accelerate/big_modeling.py", line 613, in load_checkpoint_and_dispatch
    load_checkpoint_in_model(
  File "/root/miniconda3/envs/comfyui/lib/python3.10/site-packages/accelerate/utils/modeling.py", line 1815, in load_checkpoint_in_model
    loaded_checkpoint = load_state_dict(checkpoint_file, device_map=device_map)
  File "/root/miniconda3/envs/comfyui/lib/python3.10/site-packages/accelerate/utils/modeling.py", line 1509, in load_state_dict
    with safe_open(checkpoint_file, framework="pt") as f:
safetensors_rust.SafetensorError: Error while deserializing header: HeaderTooSmall

2024-11-12 14:22:19,660 - root - INFO - Prompt executed in 1.07 seconds
```
## Attached Workflow
Please make sure that workflow does not contain any sensitive information such as API keys or passwords.
```
{"last_node_id":63,"last_link_id":139,"nodes":[{"id":48,"type":"CogVideoXFasterCache","pos":{"0":233,"1":96},"size":{"0":315,"1":130},"flags":{},"order":0,"mode":0,"inputs":[],"outputs":[{"name":"fastercache","type":"FASTERCACHEARGS","links":[122],"label":"fastercache"}],"properties":{"Node name for S&R":"CogVideoXFasterCache"},"widgets_values":[15,30,40,"main_device"]},{"id":54,"type":"CogVideoSampler","pos":{"0":1029,"1":272},"size":{"0":405.5999755859375,"1":410},"flags":{},"order":10,"mode":0,"inputs":[{"name":"pipeline","type":"COGVIDEOPIPE","link":119,"label":"CogVideo"},{"name":"positive","type":"CONDITIONING","link":120,"label":"正面条件"},{"name":"negative","type":"CONDITIONING","link":121,"label":"负面条件"},{"name":"samples","type":"LATENT","link":null,"shape":7,"label":"Latent"},{"name":"image_cond_latents","type":"LATENT","link":127,"shape":7},{"name":"context_options","type":"COGCONTEXT","link":null,"shape":7},{"name":"controlnet","type":"COGVIDECONTROLNET","link":null,"shape":7},{"name":"tora_trajectory","type":"TORAFEATURES","link":null,"shape":7},{"name":"fastercache","type":"FASTERCACHEARGS","link":122,"shape":7}],"outputs":[{"name":"cogvideo_pipe","type":"COGVIDEOPIPE","links":[130],"slot_index":0,"label":"CogVideo"},{"name":"samples","type":"LATENT","links":[129],"slot_index":1,"label":"Latent"}],"properties":{"Node name for S&R":"CogVideoSampler"},"widgets_values":[480,720,49,50,6,1060577469460445,"fixed","CogVideoXDDIM",1]},{"id":11,"type":"CogVideoDecode","pos":{"0":1499,"1":269},"size":{"0":300.396484375,"1":198},"flags":{},"order":11,"mode":0,"inputs":[{"name":"pipeline","type":"COGVIDEOPIPE","link":130,"label":"CogVideo"},{"name":"samples","type":"LATENT","link":129,"label":"Latent"}],"outputs":[{"name":"images","type":"IMAGE","links":[136],"slot_index":0,"shape":3,"label":"图像"}],"properties":{"Node name for S&R":"CogVideoDecode"},"widgets_values":[false,240,360,0.2,0.2,true]},{"id":44,"type":"VHS_VideoCombine","pos":{"0":1875,"1":266},"size":[605.3909912109375,310],"flags":{},"order":12,"mode":0,"inputs":[{"name":"images","type":"IMAGE","link":136,"label":"图像"},{"name":"audio","type":"VHS_AUDIO","link":null,"shape":7,"label":"音频"},{"name":"meta_batch","type":"VHS_BatchManager","link":null,"shape":7,"label":"批次管理"},{"name":"vae","type":"VAE","link":null,"shape":7}],"outputs":[{"name":"Filenames","type":"VHS_FILENAMES","links":null,"shape":3,"label":"文件名"}],"properties":{"Node name for S&R":"VHS_VideoCombine"},"widgets_values":{"frame_rate":30,"loop_count":0,"filename_prefix":"CogVideoX_Fun","format":"video/h264-mp4","pix_fmt":"yuv420p","crf":19,"save_metadata":true,"pingpong":false,"save_output":true,"videopreview":{"hidden":false,"paused":false,"params":{"filename":"CogVideoX_Fun_00001.mp4","subfolder":"","type":"output","format":"video/h264-mp4","frame_rate":30},"muted":false}}},{"id":57,"type":"CogVideoImageEncode","pos":{"0":661,"1":679},"size":{"0":315,"1":122},"flags":{},"order":8,"mode":0,"inputs":[{"name":"pipeline","type":"COGVIDEOPIPE","link":128,"label":"CogVideo"},{"name":"image","type":"IMAGE","link":126,"label":"图像"},{"name":"mask","type":"MASK","link":null,"shape":7}],"outputs":[{"name":"samples","type":"LATENT","links":[127],"slot_index":0,"label":"Latent"}],"properties":{"Node name for S&R":"CogVideoImageEncode"},"widgets_values":[16,false]},{"id":62,"type":"PreviewImage","pos":{"0":680,"1":894},"size":{"0":294.0993347167969,"1":246},"flags":{},"order":9,"mode":0,"inputs":[{"name":"images","type":"IMAGE","link":137,"label":"图像"}],"outputs":[],"properties":{"Node name for S&R":"PreviewImage"}},{"id":49,"type":"CogVideoLoraSelect","pos":{"0":-275,"1":-141},"size":{"0":315,"1":106},"flags":{},"order":1,"mode":0,"inputs":[{"name":"prev_lora","type":"COGLORA","link":null,"shape":7,"label":"prev_lora"}],"outputs":[{"name":"lora","type":"COGLORA","links":[118],"slot_index":0,"label":"lora"}],"properties":{"Node name for S&R":"CogVideoLoraSelect"},"widgets_values":["orbit_left_lora_weights.safetensors",0.5,false]},{"id":37,"type":"ImageResizeKJ","pos":{"0":188,"1":857},"size":{"0":315,"1":266},"flags":{},"order":7,"mode":0,"inputs":[{"name":"image","type":"IMAGE","link":138,"label":"图像"},{"name":"get_image_size","type":"IMAGE","link":null,"shape":7,"label":"参考图像"},{"name":"width_input","type":"INT","link":null,"widget":{"name":"width_input"},"label":"宽度"},{"name":"height_input","type":"INT","link":null,"widget":{"name":"height_input"},"label":"高度"}],"outputs":[{"name":"IMAGE","type":"IMAGE","links":[126,137],"slot_index":0,"shape":3,"label":"图像"},{"name":"width","type":"INT","links":null,"shape":3,"label":"宽度"},{"name":"height","type":"INT","links":null,"shape":3,"label":"高度"}],"properties":{"Node name for S&R":"ImageResizeKJ"},"widgets_values":[720,480,"lanczos",false,2,0,0,"center"]},{"id":30,"type":"CogVideoTextEncode","pos":{"0":-38,"1":273},"size":{"0":552.3121337890625,"1":221.82293701171875},"flags":{},"order":5,"mode":0,"inputs":[{"name":"clip","type":"CLIP","link":54,"label":"CLIP"}],"outputs":[{"name":"conditioning","type":"CONDITIONING","links":[120],"slot_index":0,"shape":3,"label":"条件"},{"name":"clip","type":"CLIP","links":[],"slot_index":1}],"properties":{"Node name for S&R":"CogVideoTextEncode"},"widgets_values":["camera orbiting left around a a fit, attractive, bearded man with wavy hair, wearing an open white robe, revealing a toned, muscular chest, standing on a beach at sunset. The video is of high quality, and the view is very clear. High quality, masterpiece, best quality, highres, ultra-detailed, fantastic.",1,false,true]},{"id":20,"type":"CLIPLoader","pos":{"0":-647,"1":260},"size":{"0":451.30548095703125,"1":82},"flags":{},"order":2,"mode":0,"inputs":[],"outputs":[{"name":"CLIP","type":"CLIP","links":[54,139],"slot_index":0,"shape":3,"label":"CLIP"}],"properties":{"Node name for S&R":"CLIPLoader"},"widgets_values":["sd3/t5xxl_fp8_e4m3fn.safetensors","sd3"]},{"id":31,"type":"CogVideoTextEncode","pos":{"0":20,"1":553},"size":{"0":463.01251220703125,"1":149},"flags":{},"order":6,"mode":0,"inputs":[{"name":"clip","type":"CLIP","link":139,"label":"CLIP"}],"outputs":[{"name":"conditioning","type":"CONDITIONING","links":[121],"slot_index":0,"shape":3,"label":"条件"},{"name":"clip","type":"CLIP","links":null}],"properties":{"Node name for S&R":"CogVideoTextEncode"},"widgets_values":["The video is not of a high quality, it has a low resolution. Watermark present in each frame. Strange motion trajectory. ",1,true,true]},{"id":63,"type":"LoadImage","pos":{"0":-329,"1":795},"size":{"0":315,"1":314},"flags":{},"order":3,"mode":0,"inputs":[],"outputs":[{"name":"IMAGE","type":"IMAGE","links":[138],"label":"图像"},{"name":"MASK","type":"MASK","links":null,"label":"遮罩"}],"properties":{"Node name for S&R":"LoadImage"},"widgets_values":["a9fd10413b208491fc66d341f2e250b3.jpeg","image"]},{"id":50,"type":"DownloadAndLoadCogVideoModel","pos":{"0":204,"1":-180},"size":{"0":337.8885192871094,"1":214},"flags":{},"order":4,"mode":0,"inputs":[{"name":"pab_config","type":"PAB_CONFIG","link":null,"shape":7},{"name":"block_edit","type":"TRANSFORMERBLOCKS","link":null,"shape":7},{"name":"lora","type":"COGLORA","link":118,"shape":7},{"name":"compile_args","type":"COMPILEARGS","link":null,"shape":7}],"outputs":[{"name":"cogvideo_pipe","type":"COGVIDEOPIPE","links":[119,128],"slot_index":0,"label":"CogVideo"}],"properties":{"Node name for S&R":"DownloadAndLoadCogVideoModel"},"widgets_values":["THUDM/CogVideoX-5b-I2V","bf16","enabled","disabled",false]}],"links":[[54,20,0,30,0,"CLIP"],[118,49,0,50,2,"COGLORA"],[119,50,0,54,0,"COGVIDEOPIPE"],[120,30,0,54,1,"CONDITIONING"],[121,31,0,54,2,"CONDITIONING"],[122,48,0,54,8,"FASTERCACHEARGS"],[126,37,0,57,1,"IMAGE"],[127,57,0,54,4,"LATENT"],[128,50,0,57,0,"COGVIDEOPIPE"],[129,54,1,11,1,"LATENT"],[130,54,0,11,0,"COGVIDEOPIPE"],[136,11,0,44,0,"IMAGE"],[137,37,0,62,0,"IMAGE"],[138,63,0,37,0,"IMAGE"],[139,20,0,31,0,"CLIP"]],"groups":[],"config":{},"extra":{"ds":{"scale":0.7972024500000005,"offset":[741.7159670863884,193.62865585558745]},"workspace_info":{"id":"hgsjYn7tx2bus7lf3hEBP"}},"version":0.4}
```

## Additional Context
(Please add any additional context or steps to reproduce the error here)

I downloaded the 5B I2V model and encountered this error while running. I am requesting assistance.

@kijai

**Comment by kijai** [comment]
`HeaderTooSmall `suggests some of the files either didn't finish downloading or got corrupted.

**Comment by ffhelly** [comment]
> `HeaderTooSmall `suggests some of the files either didn't finish downloading or got corrupted.

The download address I provided is“ https://hf-mirror.com/THUDM/CogVideoX-5b-I2V/tree/main ”This model. Is it because of this? I have downloaded it twice already. Do I need to re download from another channel?
