### ISSUE TITLE
AttributeError: module 'torch' has no attribute 'compiler'

### ISSUE THREAD

**Issue by AllanBlackwater** [kijai/ComfyUI-CogVideoXWrapper#232]
Hello,  I'm receiving this error trying to install this custom node using ComfyUI Manager.

sageattn not found, using sdpa
Traceback (most recent call last):
  File "F:\Standard Diffusion Base Folder\ComfyUI_windows_portable\ComfyUI\nodes.py", line 2022, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "F:\Standard Diffusion Base Folder\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-CogVideoXWrapper\__init__.py", line 2, in <module>
    from .model_loading import NODE_CLASS_MAPPINGS as MODEL_CLASS, NODE_DISPLAY_NAME_MAPPINGS as MODEL_DISPLAY
  File "F:\Standard Diffusion Base Folder\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-CogVideoXWrapper\model_loading.py", line 12, in <module>
    from .custom_cogvideox_transformer_3d import CogVideoXTransformer3DModel
  File "F:\Standard Diffusion Base Folder\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-CogVideoXWrapper\custom_cogvideox_transformer_3d.py", line 64, in <module>
    class CogVideoXAttnProcessor2_0:
  File "F:\Standard Diffusion Base Folder\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-CogVideoXWrapper\custom_cogvideox_transformer_3d.py", line 73, in CogVideoXAttnProcessor2_0
    @torch.compiler.disable()
AttributeError: module 'torch' has no attribute 'compiler'

Cannot import F:\Standard Diffusion Base Folder\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-CogVideoXWrapper module for custom nodes: module 'torch' has no attribute 'compiler'

**Comment by kijai** [comment]
Your torch version must be really old, definitely in need of an update.

**Comment by AllanBlackwater** [comment]
I ran update_comfyui_and_python_dependencies.bat to update it before posting this issue, thinking it updated that, but yeah looks like it's using

pytorch version: 2.0.1+cu118

I'll work on figuring out why that's not updating.
