### ISSUE TITLE
Manual Download Links for Models

### ISSUE THREAD

**Issue by MushroomFleet** [kijai/ComfyUI-CogVideoXWrapper#242]
I love the auto downloader and it usually works great, but every now and then the huggingface is just plain bad.
It didn't even try to download the file properly, then complained it was a partial download. 

As you see here, we did 38% and just give up.

I know this is beyond your control, but is there a way you can point me to a manual URL, I would guess, but then i'm not sure where they need to be placed inside comfyUI.

is it here ?
`ComfyUI_windows_portable\ComfyUI\models\CogVideo` 

Big Thanks

```
Downloading model to: I:\MACHINES3\ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\models\CogVideo\CogVideoX-Fun-5b-InP
Fetching 24 files:  38%|████████████████████████                                        | 9/24 [01:32<02:33, 10.25s/it]
!!! Exception during processing !!! Consistency check failed: file should be of size 3387912120 but has size 338360005 (diffusion_pytorch_model.safetensors).
We are sorry for the inconvenience. Please retry with `force_download=True`.
If the issue persists, please let us know by opening an issue on https://github.com/huggingface/huggingface_hub.
Traceback (most recent call last):
  File "I:\MACHINES3\ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "I:\MACHINES3\ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "I:\MACHINES3\ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "I:\MACHINES3\ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "I:\MACHINES3\ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-CogVideoXWrapper\model_loading.py", line 162, in loadmodel
    snapshot_download(
  File "I:\MACHINES3\ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\python_embeded\Lib\site-packages\huggingface_hub\utils\_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "I:\MACHINES3\ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\python_embeded\Lib\site-packages\huggingface_hub\_snapshot_download.py", line 293, in snapshot_download
    thread_map(
  File "I:\MACHINES3\ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\python_embeded\Lib\site-packages\tqdm\contrib\concurrent.py", line 69, in thread_map
    return _executor_map(ThreadPoolExecutor, fn, *iterables, **tqdm_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "I:\MACHINES3\ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\python_embeded\Lib\site-packages\tqdm\contrib\concurrent.py", line 51, in _executor_map
    return list(tqdm_class(ex.map(fn, *iterables, chunksize=chunksize), **kwargs))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "I:\MACHINES3\ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\python_embeded\Lib\site-packages\tqdm\std.py", line 1181, in __iter__
    for obj in iterable:
  File "concurrent\futures\_base.py", line 619, in result_iterator
  File "concurrent\futures\_base.py", line 317, in _result_or_cancel
  File "concurrent\futures\_base.py", line 456, in result
  File "concurrent\futures\_base.py", line 401, in __get_result
  File "concurrent\futures\thread.py", line 58, in run
  File "I:\MACHINES3\ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\python_embeded\Lib\site-packages\huggingface_hub\_snapshot_download.py", line 267, in _inner_hf_hub_download
    return hf_hub_download(
           ^^^^^^^^^^^^^^^^
  File "I:\MACHINES3\ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\python_embeded\Lib\site-packages\huggingface_hub\utils\_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "I:\MACHINES3\ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\python_embeded\Lib\site-packages\huggingface_hub\file_download.py", line 842, in hf_hub_download
    return _hf_hub_download_to_local_dir(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "I:\MACHINES3\ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\python_embeded\Lib\site-packages\huggingface_hub\file_download.py", line 1138, in _hf_hub_download_to_local_dir
    _download_to_tmp_and_move(
  File "I:\MACHINES3\ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\python_embeded\Lib\site-packages\huggingface_hub\file_download.py", line 1545, in _download_to_tmp_and_move
    http_get(
  File "I:\MACHINES3\ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\python_embeded\Lib\site-packages\huggingface_hub\file_download.py", line 483, in http_get
    raise EnvironmentError(
OSError: Consistency check failed: file should be of size 3387912120 but has size 338360005 (diffusion_pytorch_model.safetensors).
We are sorry for the inconvenience. Please retry with `force_download=True`.
If the issue persists, please let us know by opening an issue on https://github.com/huggingface/huggingface_hub.
```

I did try to delete the .cache and other folders, but then it fails with different errors:

```
Continuing without setting permissions.
Fetching 24 files:   4%|██▋                                                             | 1/24 [00:00<00:08,  2.60it/s]
Could not set the permissions on the file 'I:\MACHINES3\ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\models\CogVideo\.cache\huggingface\download\CogVideoX-Fun-2b-InP\transformer\config.json.5fb378f6066a5ccd90aeacc1fd28a86f352b7d82.incomplete'. Error: [Errno 2] No such file or directory: 'I:\\MACHINES3\\ComfyUI_windows_portable_nvidia_cu121_or_cpu\\ComfyUI_windows_portable\\ComfyUI\\models\\CogVideo\\CogVideoX-Fun-2b-InP\\tmp_9ab3909a-4093-44b6-85f4-e13e1f8e82c7'.
Continuing without setting permissions.
```

Any advice is golden, thanks again

**Comment by kijai** [comment]
Yes the folder is ComfyUI\models\CogVideo, problem is just that you need most of the files so it's really annoying to manually download, but it's possible of course, you just replicate the huggingface repo in a folder with same name as the repo, for example: 

![image](https://github.com/user-attachments/assets/f34643a2-4f31-4653-af66-f4e3019a7f6b)

I have been working on just single file model loader, there are so many models to convert though by now that I keep procrastinating it.

**Comment by zazoum-art** [comment]
https://github.com/kijai/ComfyUI-CogVideoXWrapper/issues/241

**Comment by MushroomFleet** [comment]
> Yes the folder is ComfyUI\models\CogVideo, problem is just that you need most of the files so it's really annoying to manually download, but it's possible of course, you just replicate the huggingface repo in a folder with same name as the repo, for example:
> 
> ![image](https://private-user-images.githubusercontent.com/40791699/387020364-f34643a2-4f31-4653-af66-f4e3019a7f6b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE5MTc5OTEsIm5iZiI6MTczMTkxNzY5MSwicGF0aCI6Ii80MDc5MTY5OS8zODcwMjAzNjQtZjM0NjQzYTItNGYzMS00NjUzLWFmNjYtZjRlMzAxOWE3ZjZiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE4VDA4MTQ1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQzN2I5Y2ZlMzZhM2MxNmFiNmRiMzU3YjViN2MwOWM0NTg1OGM5NWNhNjlmZjViYjBmNTdhOWQ5NmM3OWY1ODImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Li9ygXXHNF0S8gKZO6CSEPNzJF6NUX_r-hOW6MM7G-M)
> 
> I have been working on just single file model loader, there are so many models to convert though by now that I keep procrastinating it.

That's perfect, I get it now - thanks ! 
big thanks again as always !!

you gave me some ideas too, for alternate automations on this front.
I deal mostly with portable comfyui, but i might have a solution.

I think the problem is actually huggingface, i have a great connection, so i'm guessing some times of the day they struggle with the load lately. I might have more to contribute on this, so i'll leave it open for now - if that's ok

**Comment by MushroomFleet** [comment]
You inspired me to create this: [Huggingface Downloader](https://github.com/MushroomFleet/HF-Downloader)

so i can queue up the Repo's i need and not have this problem in comfy. 
Thanks !!
