### ISSUE TITLE
Getting the Sizes of tensors must match error on the 1.5 test branch for image to video on new 1.5 model

### ISSUE THREAD

**Issue by tcla75** [kijai/ComfyUI-CogVideoXWrapper#250]
got prompt
Only one image conditioning frame received, img2vid
!!! Exception during processing !!! Sizes of tensors must match except in dimension 1. Expected size 60 but got size 170 for tensor number 1 in the list.
Traceback (most recent call last):
  File "C:\SD\ComfyUI2\New\ComfyUI_windows_portable\ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\SD\ComfyUI2\New\ComfyUI_windows_portable\ComfyUI\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\SD\ComfyUI2\New\ComfyUI_windows_portable\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "C:\SD\ComfyUI2\New\ComfyUI_windows_portable\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\SD\ComfyUI2\New\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-CogVideoXWrapper\nodes.py", line 875, in process
    latents = pipeline["pipe"](
              ^^^^^^^^^^^^^^^^^
  File "C:\SD\ComfyUI2\New\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\utils\_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\SD\ComfyUI2\New\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-CogVideoXWrapper\pipeline_cogvideox.py", line 525, in __call__
    image_cond_latents = torch.cat([image_cond_latents, latent_padding], dim=1)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Sizes of tensors must match except in dimension 1. Expected size 60 but got size 170 for tensor number 1 in the list.

**Comment by kijai** [comment]
This was probably due to me changing the nodes, lots of stuff has changed so this issue as it is becomes redundant.
