### ISSUE TITLE
ERREUR CogVideoSampler Given groups=1, weight of size [3072, 16, 2, 2], expected input[26, 32, 60, 90] to have 16 channels, but got 32 channels instead

### ISSUE THREAD

**Issue by ABIA2024** [kijai/ComfyUI-CogVideoXWrapper#262]
le LOG;
Prompt executed in 7.72 seconds
got prompt
WARNING: [Errno 2] No such file or directory: 'C:\\Users\\Ben\\Desktop\\CogVideoX5B + DimensionX\\images\\wukong_222.webp'
Downloading model to: D:\PINOKIO2\ComfyUI_windows_portable\ComfyUI\models\CogVideo\CogVideoX-5b-Tora
Fetching 10 files: 100%|████████████████████████████████████████████████████████████| 10/10 [2:26:42<00:00, 880.22s/it]
Merging rank 256 LoRA weights from D:\PINOKIO2\ComfyUI_windows_portable\ComfyUI\models\CogVideo\loras\orbit_left_lora_weights.safetensors with strength 0.5
Encoded latents shape: torch.Size([1, 1, 16, 60, 90])
Requested to load SD3ClipModel_
Loading 1 new model
loaded partially 64.0 32.38671875 0
Unloading models for lowram load.
1 models unloaded.
Loading 1 new model
loaded partially 5203.500290679932 5195.38671875 0
Only one image conditioning frame received, img2vid
Temporal tiling and context schedule disabled
  0%|                                                                                           | 0/50 [00:00<?, ?it/s]
!!! Exception during processing !!! Given groups=1, weight of size [3072, 16, 2, 2], expected input[26, 32, 60, 90] to have 16 channels, but got 32 channels instead
Traceback (most recent call last):
  File "D:\PINOKIO2\ComfyUI_windows_portable\ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PINOKIO2\ComfyUI_windows_portable\ComfyUI\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PINOKIO2\ComfyUI_windows_portable\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "D:\PINOKIO2\ComfyUI_windows_portable\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PINOKIO2\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-CogVideoXWrapper\nodes.py", line 866, in process
    latents = pipeline["pipe"](
              ^^^^^^^^^^^^^^^^^
  File "D:\PINOKIO2\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\utils\_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\PINOKIO2\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-CogVideoXWrapper\pipeline_cogvideox.py", line 875, in __call__
    noise_pred = self.transformer(
                 ^^^^^^^^^^^^^^^^^
  File "D:\PINOKIO2\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PINOKIO2\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PINOKIO2\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-CogVideoXWrapper\custom_cogvideox_transformer_3d.py", line 650, in forward
    hidden_states = self.patch_embed(encoder_hidden_states, hidden_states)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PINOKIO2\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PINOKIO2\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PINOKIO2\ComfyUI_windows_portable\python_embeded\Lib\site-packages\diffusers\models\embeddings.py", line 412, in forward
    image_embeds = self.proj(image_embeds)
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PINOKIO2\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PINOKIO2\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PINOKIO2\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\nn\modules\conv.py", line 554, in forward
    return self._conv_forward(input, self.weight, self.bias)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PINOKIO2\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\nn\modules\conv.py", line 549, in _conv_forward
    return F.conv2d(
           ^^^^^^^^^
RuntimeError: Given groups=1, weight of size [3072, 16, 2, 2], expected input[26, 32, 60, 90] to have 16 channels, but got 32 channels instead

**Comment by kijai** [comment]
That error would mean you are trying to use image input on text2vid model. The Tora 5b model is only text2vid. Tora trajectories can still be used with the other image2vid models, except 1.5 version won't work.

**Comment by ABIA2024** [comment]
Thank you for yout answer BUT 👍 
What can I do to be able to execute this json correctly (which works perfectly on the video of its creator (which works!): [Galaxy S24 Ultra: zoom in for more details, quite simply](https://www.youtube.com/watch?v=IhYR-F33dek)
ComfyUI CogVideoX 5B With Dimension X An Image To Video Generation - 3D/4D Video With 1 Image )
here's the json :
{
“last_node_id: 59,
“last_link_id": 128,
“nodes": [
{
“id": 37,
“type": ‘ImageResizeKJ’,
“pos": {
“0": 618.209228515625,
“1": 1097.7996826171875
},
“size": {
“0": 315,
“1": 266
},
“flags": {},
“order": 6,
“mode": 0,
“inputs": [
{
“name": ‘image’,
“type": ‘IMAGE’,
“link": 124,
“label": ”image”
},
{
“name": ‘get_image_size’,
“type": ‘IMAGE’,
“link": null,
“shape": 7,
“label": ”get_image_size”
},
{
“name": ‘width_input’,
“type": ‘INT’,
“link": null,
“widget": {
“name": ”width_input”
},
“label": ”width_input”
},
{
“name": ‘height_input’,
“type": ‘INT’,
“link": null,
“widget": {
“name": ”height_input”
},
“label": ”height_input”
}
],
“outputs": [
{
“name": ‘IMAGE’,
“type": ‘IMAGE’,
“links": [
119
],
“slot

Translated with [DeepL.com](https://www.deepl.com/?utm_campaign=product&utm_source=web_translator&utm_medium=web&utm_content=copy_free_translation) (free version)

**Comment by ABIA2024** [comment]
here is my copy screen
![screenshot 648](https://github.com/user-attachments/assets/b72a6e59-f62a-41f8-9235-145a195bca1f)

**Comment by kijai** [comment]
> here is my copy screen ![screenshot 648](https://private-user-images.githubusercontent.com/179321600/388079385-b72a6e59-f62a-41f8-9235-145a195bca1f.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIxMDM3MjAsIm5iZiI6MTczMjEwMzQyMCwicGF0aCI6Ii8xNzkzMjE2MDAvMzg4MDc5Mzg1LWI3MmE2ZTU5LWY2MmEtNDFmOC05MjM1LTE0NWExOTViY2ExZi5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyMFQxMTUwMjBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zOTMwYWMwMTJlOWMzY2ZhMmI5MjMzYWM4NDFkYjhjZDQyMGQ5YmY2ZmYyZTQ5ZjFlYzRjZDFjMjg5ZDRlOWIzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.S2YmejEeUPpbUTb91swXImV50ed7VmUBUijb_ofv6Fg)

There is nothing in that workflow that's different to my example workflow included with the nodes, since the last big update all old workflows would need updating, in this case you can just use my example `cogvideox_1_0_5b_I2V_02.json`

**Comment by ABIA2024** [comment]
HIddrdddd

HI! And now and here is happening when i use the model 2B (copy screen); i never thougt that it was so neccesary to learn python and other isntruments! to use COMFY UI, that' horrible, in despite i was programmer 10 years a long ago..Please how can i work this workflow? it works on Future thinker mentionned on the issues website.

DownloadAndLoadCogVideoModel

Error no file named diffusion_pytorch_model.bin found in directory D:\PINOKIO2\ComfyUI_windows_portable\ComfyUI\models\CogVideo\CogVideoX-Fun-2b-InP.



    Le mercredi 20 novembre 2024 à 11:07:17 UTC+1, Jukka Seppänen ***@***.***> a écrit :  
 
 


Cette erreur signifierait que vous essayez d'utiliser l'entrée d'image sur le modèle text2vid. Le modèle Tora 5b est seulement text2vid. Les trajectoires tora peuvent toujours être utilisées avec les autres modèles image2vid, sauf que la version 1.5 ne fonctionnera pas.

—
Répondez directement à cet email voir sur GitHub, ou désinscrire.
Vous recevez ceci parce que vous avez écrit le thread.ID du message: ***@***.***>
  

|  | Sans virus.www.avast.com |

**Comment by ABIA2024** [comment]
thank you but your copy doesn't work
Cette page du site private-user-images.githubusercontent.com est introuvable

Aucune page Web trouvée à l'adresse :https://private-user-images.githubusercontent.com/179321600/388079385-b72a6e59-f62a-41f8-9235-145a195bca1f.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIxMDM3MjAsIm5iZiI6MTczMjEwMzQyMCwicGF0aCI6Ii8xNzkzMjE2MDAvMzg4MDc5Mzg1LWI3MmE2ZTU5LWY2MmEtNDFmOC05MjM1LTE0NWExOTViY2ExZi5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyMFQxMTUwMjBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zOTMwYWMwMTJlOWMzY2ZhMmI5MjMzYWM4NDFkYjhjZDQyMGQ5YmY2ZmYyZTQ5ZjFlYzRjZDFjMjg5ZDRlOWIzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.S2YmejEeUPpbUTb91swXImV50ed7VmUBUijb_ofv6Fg
HTTP ERROR 404
Can you join me a fine file please?, and after i can test your json, thanks
    Le mercredi 20 novembre 2024 à 12:53:13 UTC+1, Jukka Seppänen ***@***.***> a écrit :  
 
 



voici mon écran de copie 


Il n'y a rien dans ce flux de travail qui soit différent de mon exemple de flux de travail inclus avec les nœuds, car la dernière grande mise à jour tous les anciens flux de travail nécessiteraient une mise à jour, dans ce cas, vous pouvez simplement utiliser mon exemple cogvideox_1_0_5b_I2V_02.json

—
Répondez directement à cet email voir sur GitHub, ou désinscrire.
Vous recevez ceci parce que vous avez écrit le thread.ID du message: ***@***.***>
  

|  | Sans virus.www.avast.com |
