### ISSUE TITLE
Can it be used with 5B ControlNet?

### ISSUE THREAD

**Issue by njzxj** [kijai/ComfyUI-CogVideoXWrapper#302]
Hello,

When I replaced the 2B model in cogvideox_1_0_2b_controlnet_02.json with the 5B model, I encountered the following error:

File "/root/code/ComfyUI/custom_nodes/ComfyUI-CogVideoXWrapper/cogvideo_controlnet.py", line 164, in forward
    hidden_states = torch.cat([hidden_states, controlnet_states], dim=2)
RuntimeError: Sizes of tensors must match except in dimension 2. Expected size 14 but got size 13 for tensor number 1 in the list.

Is the current version not compatible with the 5B ControlNet model?
![企业微信截图_17327890946880](https://github.com/user-attachments/assets/bfd7c72a-fb4e-4bf4-aef3-bd7f7d6b5577)

**Comment by drfenixlinghu** [comment]
same question here, tried 5b, 5b-1.5, 5b-fun-control, no luck whatsoever,

**Comment by kijai** [comment]
Can't reproduce this issue, this is not any useful result, but just to check it's working:

![image](https://github.com/user-attachments/assets/dea85d1d-474f-4084-bef9-c088beec2534)

**Comment by kijai** [comment]
>  RuntimeError: Sizes of tensors must match except in dimension 2. Expected size 14 but got size 13 for tensor number 1 in the 

Actually this could be if your video doesn't have the 49 frames, the frame count still needs to match what the model can do.

**Comment by mrdrprofuroboros** [comment]
> Can't reproduce this issue, this is not any useful result, but just to check it's working:

The one you're providing works with the original THUDM/CogVideoX-5b model but fails due to channel mismatch when switching to Fun-V1.1-5b-Control

```
!!! Exception during processing !!! Given groups=1, weight of size [3072, 32, 2, 2], expected input[18, 16, 64, 64] to have 32 channels, but got 16 channels instead
Traceback (most recent call last):
  File "/home/ubuntu/ComfyUI/execution.py", line 328, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "/home/ubuntu/ComfyUI/execution.py", line 203, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "/home/ubuntu/ComfyUI/execution.py", line 174, in _map_node_over_list
    process_inputs(input_dict, i)
  File "/home/ubuntu/ComfyUI/execution.py", line 163, in process_inputs
    results.append(getattr(obj, func)(**inputs))
  File "/home/ubuntu/ComfyUI/custom_nodes/ComfyUI-CogVideoXWrapper/nodes.py", line 722, in process
    latents = model["pipe"](
  File "/home/ubuntu/ComfyUI/.venv/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "/home/ubuntu/ComfyUI/custom_nodes/ComfyUI-CogVideoXWrapper/pipeline_cogvideox.py", line 778, in __call__
    noise_pred = self.transformer(
  File "/home/ubuntu/ComfyUI/.venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/ubuntu/ComfyUI/.venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/ubuntu/ComfyUI/custom_nodes/ComfyUI-CogVideoXWrapper/custom_cogvideox_transformer_3d.py", line 582, in forward
    hidden_states = self.patch_embed(encoder_hidden_states, hidden_states)
  File "/home/ubuntu/ComfyUI/.venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/ubuntu/ComfyUI/.venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/ubuntu/ComfyUI/custom_nodes/ComfyUI-CogVideoXWrapper/embeddings.py", line 93, in forward
    image_embeds = self.proj(image_embeds)
  File "/home/ubuntu/ComfyUI/.venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/ubuntu/ComfyUI/.venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/ubuntu/ComfyUI/.venv/lib/python3.10/site-packages/torch/nn/modules/conv.py", line 554, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/home/ubuntu/ComfyUI/.venv/lib/python3.10/site-packages/torch/nn/modules/conv.py", line 549, in _conv_forward
    return F.conv2d(
RuntimeError: Given groups=1, weight of size [3072, 32, 2, 2], expected input[18, 16, 64, 64] to have 32 channels, but got 16 channels instead
```

Would you mind taking a look?

**Comment by kijai** [comment]
> > Can't reproduce this issue, this is not any useful result, but just to check it's working:
> 
> The one you're providing works with the original THUDM/CogVideoX-5b model but fails due to some shape mismatch when switching to Fun-V1.1-5b-Control
> 
> ```
> !!! Exception during processing !!! Given groups=1, weight of size [3072, 32, 2, 2], expected input[18, 16, 64, 64] to have 32 channels, but got 16 channels instead
> Traceback (most recent call last):
>   File "/home/ubuntu/ComfyUI/execution.py", line 328, in execute
>     output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
>   File "/home/ubuntu/ComfyUI/execution.py", line 203, in get_output_data
>     return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
>   File "/home/ubuntu/ComfyUI/execution.py", line 174, in _map_node_over_list
>     process_inputs(input_dict, i)
>   File "/home/ubuntu/ComfyUI/execution.py", line 163, in process_inputs
>     results.append(getattr(obj, func)(**inputs))
>   File "/home/ubuntu/ComfyUI/custom_nodes/ComfyUI-CogVideoXWrapper/nodes.py", line 722, in process
>     latents = model["pipe"](
>   File "/home/ubuntu/ComfyUI/.venv/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
>     return func(*args, **kwargs)
>   File "/home/ubuntu/ComfyUI/custom_nodes/ComfyUI-CogVideoXWrapper/pipeline_cogvideox.py", line 778, in __call__
>     noise_pred = self.transformer(
>   File "/home/ubuntu/ComfyUI/.venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
>     return self._call_impl(*args, **kwargs)
>   File "/home/ubuntu/ComfyUI/.venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
>     return forward_call(*args, **kwargs)
>   File "/home/ubuntu/ComfyUI/custom_nodes/ComfyUI-CogVideoXWrapper/custom_cogvideox_transformer_3d.py", line 582, in forward
>     hidden_states = self.patch_embed(encoder_hidden_states, hidden_states)
>   File "/home/ubuntu/ComfyUI/.venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
>     return self._call_impl(*args, **kwargs)
>   File "/home/ubuntu/ComfyUI/.venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
>     return forward_call(*args, **kwargs)
>   File "/home/ubuntu/ComfyUI/custom_nodes/ComfyUI-CogVideoXWrapper/embeddings.py", line 93, in forward
>     image_embeds = self.proj(image_embeds)
>   File "/home/ubuntu/ComfyUI/.venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
>     return self._call_impl(*args, **kwargs)
>   File "/home/ubuntu/ComfyUI/.venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
>     return forward_call(*args, **kwargs)
>   File "/home/ubuntu/ComfyUI/.venv/lib/python3.10/site-packages/torch/nn/modules/conv.py", line 554, in forward
>     return self._conv_forward(input, self.weight, self.bias)
>   File "/home/ubuntu/ComfyUI/.venv/lib/python3.10/site-packages/torch/nn/modules/conv.py", line 549, in _conv_forward
>     return F.conv2d(
> RuntimeError: Given groups=1, weight of size [3072, 32, 2, 2], expected input[18, 16, 64, 64] to have 32 channels, but got 16 channels instead
> ```
> 
> Would you mind taking a look?

It's not compatible with the Fun models.
