### ISSUE TITLE
cannot import ComfyUI-CogVideoXWrapper

### ISSUE THREAD

**Issue by wwwkll** [kijai/ComfyUI-CogVideoXWrapper#337]
Traceback (most recent call last):
  File "D:\ComfyUI-aki-v1.5\ComfyUI-aki-v1.5\nodes.py", line 2026, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\ComfyUI-aki-v1.5\ComfyUI-aki-v1.5\custom_nodes\ComfyUI-CogVideoXWrapper\__init__.py", line 2, in <module>
    from .model_loading import NODE_CLASS_MAPPINGS as MODEL_CLASS, NODE_DISPLAY_NAME_MAPPINGS as MODEL_DISPLAY
  File "D:\ComfyUI-aki-v1.5\ComfyUI-aki-v1.5\custom_nodes\ComfyUI-CogVideoXWrapper\model_loading.py", line 8, in <module>
    from diffusers.models import AutoencoderKLCogVideoX
  File "<frozen importlib._bootstrap>", line 1075, in _handle_fromlist
  File "D:\ComfyUI-aki-v1.5\ComfyUI-aki-v1.5\python\lib\site-packages\diffusers\utils\import_utils.py", line 843, in __getattr__
    module = self._get_module(self._class_to_module[name])
  File "D:\ComfyUI-aki-v1.5\ComfyUI-aki-v1.5\python\lib\site-packages\diffusers\utils\import_utils.py", line 855, in _get_module
    raise RuntimeError(
RuntimeError: Failed to import diffusers.models.autoencoders.autoencoder_kl_cogvideox because of the following error (look up to see its traceback):
Failed to import diffusers.loaders.unet because of the following error (look up to see its traceback):
cannot import name 'EncoderDecoderCache' from 'transformers' (D:\ComfyUI-aki-v1.5\ComfyUI-aki-v1.5\python\lib\site-packages\transformers\__init__.py)

Cannot import D:\ComfyUI-aki-v1.5\ComfyUI-aki-v1.5\custom_nodes\ComfyUI-CogVideoXWrapper module for custom nodes: Failed to import diffusers.models.autoencoders.autoencoder_kl_cogvideox because of the following error (look up to see its traceback):
Failed to import diffusers.loaders.unet because of the following error (look up to see its traceback):
cannot import name 'EncoderDecoderCache' from 'transformers' (D:\ComfyUI-aki-v1.5\ComfyUI-aki-v1.5\python\lib\site-packages\transformers\__init__.py)
[Crystools [0;32mINFO[0m] Crystools version: 1.21.0
[Crystools [0;32mINFO[0m] CPU: Intel(R) Core(TM) i7-14700F - Arch: AMD64 - OS: Windows 10
[Crystools [0;32mINFO[0m] Pynvml (Nvidia) initialized.
[Crystools [0;32mINFO[0m] GPU/s:
[Crystools [0;32mINFO[0m] 0) NVIDIA GeForce RTX 4070 Ti SUPER
[Crystools [0;32mINFO[0m] NVIDIA Driver: 560.94
### Loading: ComfyUI-Impact-Pack (Subpack: V0.6)
[WARN] ComfyUI-Impact-Pack: custom_wildcards path not found: C:\aki\AAPACKING\ComfyUI-aki-v1.4\custom_nodes\ComfyUI-Impact-Pack\modules\impact\..\..\custom_wildcards. Using default path.
[Impact Pack] Wildcards loading done.

tried update transformers to 4.47.1  still cannot import

**Comment by kijai** [comment]
Update diffusers to latest 0.31.0

**Comment by wwwkll** [comment]
> Update diffusers to latest 0.31.0

tried,it seems the log has a little changed,but the question is still



Traceback (most recent call last):
  File "D:\ComfyUI-aki-v1.5\ComfyUI-aki-v1.5\nodes.py", line 2026, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\ComfyUI-aki-v1.5\ComfyUI-aki-v1.5\custom_nodes\ComfyUI-CogVideoXWrapper\__init__.py", line 2, in <module>
    from .model_loading import NODE_CLASS_MAPPINGS as MODEL_CLASS, NODE_DISPLAY_NAME_MAPPINGS as MODEL_DISPLAY
  File "D:\ComfyUI-aki-v1.5\ComfyUI-aki-v1.5\custom_nodes\ComfyUI-CogVideoXWrapper\model_loading.py", line 40, in <module>
    from diffusers.models import AutoencoderKLCogVideoX
  File "<frozen importlib._bootstrap>", line 1075, in _handle_fromlist
  File "D:\ComfyUI-aki-v1.5\ComfyUI-aki-v1.5\python\lib\site-packages\diffusers\utils\import_utils.py", line 843, in __getattr__
    module = self._get_module(self._class_to_module[name])
  File "D:\ComfyUI-aki-v1.5\ComfyUI-aki-v1.5\python\lib\site-packages\diffusers\utils\import_utils.py", line 855, in _get_module
    raise RuntimeError(
RuntimeError: Failed to import diffusers.models.autoencoders.autoencoder_kl_cogvideox because of the following error (look up to see its traceback):
Failed to import diffusers.loaders.unet because of the following error (look up to see its traceback):
cannot import name 'EncoderDecoderCache' from 'transformers' (D:\ComfyUI-aki-v1.5\ComfyUI-aki-v1.5\python\lib\site-packages\transformers\__init__.py)

Cannot import D:\ComfyUI-aki-v1.5\ComfyUI-aki-v1.5\custom_nodes\ComfyUI-CogVideoXWrapper module for custom nodes: Failed to import diffusers.models.autoencoders.autoencoder_kl_cogvideox because of the following error (look up to see its traceback):
Failed to import diffusers.loaders.unet because of the following error (look up to see its traceback):
cannot import name 'EncoderDecoderCache' from 'transformers' (D:\ComfyUI-aki-v1.5\ComfyUI-aki-v1.5\python\lib\site-packages\transformers\__init__.py)
[Crystools [0;32mINFO[0m] Crystools version: 1.21.0
[Crystools [0;32mINFO[0m] CPU: Intel(R) Core(TM) i7-14700F - Arch: AMD64 - OS: Windows 10
[Crystools [0;32mINFO[0m] Pynvml (Nvidia) initialized.
[Crystools [0;32mINFO[0m] GPU/s:
[Crystools [0;32mINFO[0m] 0) NVIDIA GeForce RTX 4070 Ti SUPER
[Crystools [0;32mINFO[0m] NVIDIA Driver: 560.94
### Loading: ComfyUI-Inspire-Pack (V1.7)

Total VRAM 16376 MB, total RAM 32515 MB
pytorch version: 2.5.1+cu124
xformers version: 0.0.28.post3
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 4070 Ti SUPER : cudaMallocAsync
### Loading: ComfyUI-Manager (V2.52)
### ComfyUI Revision: 2852 [bc6be6c1] | Released on '2024-11-22'
(pysssss:WD14Tagger) [DEBUG] Available ORT providers: TensorrtExecutionProvider, CUDAExecutionProvider, CPUExecutionProvider
(pysssss:WD14Tagger) [DEBUG] Using ORT providers: CUDAExecutionProvider, CPUExecutionProvider

**Comment by kijai** [comment]
Are you sure your transformers is updated properly? How did you update it?

**Comment by wwwkll** [comment]
> Are you sure your transformers is updated properly? How did you update it?

checked,i have installed  transformers 4.47.1

update it with:

pip uninstall transformers
pip install transformers
