### ISSUE TITLE
Cannot import D:\ComfyUI-aki-v1.4\custom_nodes\ComfyUI-CogVideoXWrapper module for custom nodes

### ISSUE THREAD

**Issue by Kylin412** [kijai/ComfyUI-CogVideoXWrapper#339]
Starting server

To see the GUI go to: http://127.0.0.1:8188
FETCH DATA from: D:\ComfyUI-aki-v1.4\custom_nodes\ComfyUI-Manager\extension-node-map.json [DONE]
[START] Security scan
[DONE] Security scan
## ComfyUI-Manager: installing dependencies done.
** ComfyUI startup time: 2024-12-24 21:35:23.200714
** Platform: Windows
** Python version: 3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]
** Python executable: D:\ComfyUI-aki-v1.4\python\python.exe
** ComfyUI Path: D:\ComfyUI-aki-v1.4
** Log path: D:\ComfyUI-aki-v1.4\comfyui.log

Prestartup times for custom nodes:
   0.0 seconds: D:\ComfyUI-aki-v1.4\custom_nodes\rgthree-comfy
   0.0 seconds: D:\ComfyUI-aki-v1.4\custom_nodes\ComfyUI-Marigold
   0.0 seconds: D:\ComfyUI-aki-v1.4\custom_nodes\ComfyUI-Easy-Use
   0.0 seconds: D:\ComfyUI-aki-v1.4\custom_nodes\ComfyUI-Easy-Use-main
  18.5 seconds: D:\ComfyUI-aki-v1.4\custom_nodes\ComfyUI-Manager

Total VRAM 8188 MB, total RAM 16011 MB
pytorch version: 2.3.1+cu121
xformers version: 0.0.27
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 4060 Laptop GPU : cudaMallocAsync
Using xformers attention
[Prompt Server] web root: D:\ComfyUI-aki-v1.4\web
[AnimateDiffEvo] - ERROR - No motion models found. Please download one and place in: ['D:\\ComfyUI-aki-v1.4\\custom_nodes\\ComfyUI-AnimateDiff-Evolved\\models', 'D:\\ComfyUI-aki-v1.4\\models\\animatediff_models']
Traceback (most recent call last):
  File "D:\ComfyUI-aki-v1.4\python\lib\site-packages\diffusers\utils\import_utils.py", line 920, in _get_module
    return importlib.import_module("." + module_name, self.__name__)
  File "D:\ComfyUI-aki-v1.4\python\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\ComfyUI-aki-v1.4\python\lib\site-packages\diffusers\loaders\peft.py", line 40, in <module>
    from .lora_base import _fetch_state_dict
  File "D:\ComfyUI-aki-v1.4\python\lib\site-packages\diffusers\loaders\lora_base.py", line 47, in <module>
    from peft.tuners.tuners_utils import BaseTunerLayer
  File "D:\ComfyUI-aki-v1.4\python\lib\site-packages\peft\__init__.py", line 22, in <module>
    from .auto import (
  File "D:\ComfyUI-aki-v1.4\python\lib\site-packages\peft\auto.py", line 32, in <module>
    from .mapping import MODEL_TYPE_TO_PEFT_MODEL_MAPPING
  File "D:\ComfyUI-aki-v1.4\python\lib\site-packages\peft\mapping.py", line 25, in <module>
    from .mixed_model import PeftMixedModel
  File "D:\ComfyUI-aki-v1.4\python\lib\site-packages\peft\mixed_model.py", line 29, in <module>
    from .peft_model import PeftModel
  File "D:\ComfyUI-aki-v1.4\python\lib\site-packages\peft\peft_model.py", line 37, in <module>
    from transformers import Cache, DynamicCache, EncoderDecoderCache, PreTrainedModel
ImportError: cannot import name 'EncoderDecoderCache' from 'transformers' (D:\ComfyUI-aki-v1.4\python\lib\site-packages\transformers\__init__.py)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\ComfyUI-aki-v1.4\python\lib\site-packages\diffusers\utils\import_utils.py", line 920, in _get_module
    return importlib.import_module("." + module_name, self.__name__)
  File "D:\ComfyUI-aki-v1.4\python\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\ComfyUI-aki-v1.4\python\lib\site-packages\diffusers\models\autoencoders\__init__.py", line 1, in <module>
    from .autoencoder_asym_kl import AsymmetricAutoencoderKL
  File "D:\ComfyUI-aki-v1.4\python\lib\site-packages\diffusers\models\autoencoders\autoencoder_asym_kl.py", line 23, in <module>
    from .vae import DecoderOutput, DiagonalGaussianDistribution, Encoder, MaskConditionDecoder
  File "D:\ComfyUI-aki-v1.4\python\lib\site-packages\diffusers\models\autoencoders\vae.py", line 25, in <module>
    from ..unets.unet_2d_blocks import (
  File "D:\ComfyUI-aki-v1.4\python\lib\site-packages\diffusers\models\unets\__init__.py", line 6, in <module>
    from .unet_2d import UNet2DModel
  File "D:\ComfyUI-aki-v1.4\python\lib\site-packages\diffusers\models\unets\unet_2d.py", line 24, in <module>
    from .unet_2d_blocks import UNetMidBlock2D, get_down_block, get_up_block
  File "D:\ComfyUI-aki-v1.4\python\lib\site-packages\diffusers\models\unets\unet_2d_blocks.py", line 36, in <module>
    from ..transformers.dual_transformer_2d import DualTransformer2DModel
  File "D:\ComfyUI-aki-v1.4\python\lib\site-packages\diffusers\models\transformers\__init__.py", line 6, in <module>
    from .cogvideox_transformer_3d import CogVideoXTransformer3DModel
  File "D:\ComfyUI-aki-v1.4\python\lib\site-packages\diffusers\models\transformers\cogvideox_transformer_3d.py", line 22, in <module>
    from ...loaders import PeftAdapterMixin
  File "<frozen importlib._bootstrap>", line 1075, in _handle_fromlist
  File "D:\ComfyUI-aki-v1.4\python\lib\site-packages\diffusers\utils\import_utils.py", line 910, in __getattr__
    module = self._get_module(self._class_to_module[name])
  File "D:\ComfyUI-aki-v1.4\python\lib\site-packages\diffusers\utils\import_utils.py", line 922, in _get_module
    raise RuntimeError(
RuntimeError: Failed to import diffusers.loaders.peft because of the following error (look up to see its traceback):
cannot import name 'EncoderDecoderCache' from 'transformers' (D:\ComfyUI-aki-v1.4\python\lib\site-packages\transformers\__init__.py)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\ComfyUI-aki-v1.4\nodes.py", line 2073, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\ComfyUI-aki-v1.4\custom_nodes\ComfyUI-CogVideoXWrapper\__init__.py", line 2, in <module>
    from .model_loading import NODE_CLASS_MAPPINGS as MODEL_CLASS, NODE_DISPLAY_NAME_MAPPINGS as MODEL_DISPLAY
  File "D:\ComfyUI-aki-v1.4\custom_nodes\ComfyUI-CogVideoXWrapper\model_loading.py", line 40, in <module>
    from diffusers.models import AutoencoderKLCogVideoX
  File "<frozen importlib._bootstrap>", line 1075, in _handle_fromlist
  File "D:\ComfyUI-aki-v1.4\python\lib\site-packages\diffusers\utils\import_utils.py", line 910, in __getattr__
    module = self._get_module(self._class_to_module[name])
  File "D:\ComfyUI-aki-v1.4\python\lib\site-packages\diffusers\utils\import_utils.py", line 922, in _get_module
    raise RuntimeError(
RuntimeError: Failed to import diffusers.models.autoencoders.autoencoder_kl_cogvideox because of the following error (look up to see its traceback):
Failed to import diffusers.loaders.peft because of the following error (look up to see its traceback):
cannot import name 'EncoderDecoderCache' from 'transformers' (D:\ComfyUI-aki-v1.4\python\lib\site-packages\transformers\__init__.py)

Cannot import D:\ComfyUI-aki-v1.4\custom_nodes\ComfyUI-CogVideoXWrapper module for custom nodes: Failed to import diffusers.models.autoencoders.autoencoder_kl_cogvideox because of the following error (look up to see its traceback):
Failed to import diffusers.loaders.peft because of the following error (look up to see its traceback):
cannot import name 'EncoderDecoderCache' from 'transformers' (D:\ComfyUI-aki-v1.4\python\lib\site-packages\transformers\__init__.py)

**Comment by Kylin412** [comment]
![7a3a7c6b-29c9-4927-97a9-d8e85d728fe6](https://github.com/user-attachments/assets/4115d55f-1037-4474-b105-66b0b9a172f9)
I have tried every methods mentioned in other issues
QWQ

**Comment by kijai** [comment]
Your transformers and/or peft packages need to be updated.

**Comment by Kylin412** [comment]
I tried that ,but no use  :(

**Comment by kijai** [comment]
Tried it how? The issue is clear from your error, those packages just are not up to date.

Your pytorch version is also quite old and should be updated.

**Comment by Kylin412** [comment]
Thanks to you, I tried again, this time I changed the location of the installation and it was fine to import, but I came across Allocation on device

**Comment by MrBlindshot** [comment]
How do you do that i had same problem?
