### ISSUE TITLE
Error: DownloadAndLoadCogVideoModel "check_uniform_bounds" not implemented for 'Float8_e4m3fn'

### ISSUE THREAD

**Issue by tonetxo** [kijai/ComfyUI-CogVideoXWrapper#37]
Hi, after the last update the following error appears and it does not work (I use exactly the same parameters). It does work with fp32:

# ComfyUI Error Report
## Error Details
- **Node Type:** DownloadAndLoadCogVideoModel
- **Exception Type:** RuntimeError
- **Exception Message:** "check_uniform_bounds" not implemented for 'Float8_e4m3fn'
## Stack Trace
```
  File "/workspace/StableSwarmUI/dlbackend/ComfyUI/execution.py", line 317, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)

  File "/workspace/StableSwarmUI/dlbackend/ComfyUI/execution.py", line 192, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)

  File "/workspace/StableSwarmUI/dlbackend/ComfyUI/execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)

  File "/workspace/StableSwarmUI/dlbackend/ComfyUI/execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))

  File "/workspace/StableSwarmUI/dlbackend/ComfyUI/custom_nodes/ComfyUI-CogVideoXWrapper/nodes.py", line 90, in loadmodel
    pipe = compile_pipe(

  File "/workspace/venv/lib/python3.10/site-packages/onediffx/compilers/diffusion_pipeline_compiler.py", line 66, in compile_pipe
    pipe = fuse_qkv_projections_in_pipe(pipe)

  File "/workspace/venv/lib/python3.10/site-packages/onediffx/compilers/diffusion_pipeline_compiler.py", line 111, in fuse_qkv_projections_in_pipe
    pipe.fuse_qkv_projections()

  File "/workspace/StableSwarmUI/dlbackend/ComfyUI/custom_nodes/ComfyUI-CogVideoXWrapper/pipeline_cogvideox.py", line 256, in fuse_qkv_projections
    self.transformer.fuse_qkv_projections()

  File "/workspace/venv/lib/python3.10/site-packages/diffusers/models/transformers/cogvideox_transformer_3d.py", line 384, in fuse_qkv_projections
    module.fuse_projections(fuse=True)

  File "/workspace/venv/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)

  File "/workspace/venv/lib/python3.10/site-packages/diffusers/models/attention_processor.py", line 677, in fuse_projections
    self.to_qkv = nn.Linear(in_features, out_features, bias=self.use_bias, device=device, dtype=dtype)

  File "/workspace/venv/lib/python3.10/site-packages/torch/nn/modules/linear.py", line 104, in __init__
    self.reset_parameters()

  File "/workspace/venv/lib/python3.10/site-packages/torch/nn/modules/linear.py", line 110, in reset_parameters
    init.kaiming_uniform_(self.weight, a=math.sqrt(5))

  File "/workspace/venv/lib/python3.10/site-packages/torch/nn/init.py", line 460, in kaiming_uniform_
    return tensor.uniform_(-bound, bound, generator=generator)

```
## System Information
- **ComfyUI Version:** v0.2.0
- **Arguments:** main.py --front-end-version Comfy-Org/ComfyUI_frontend@latest --port 7821 --extra-model-paths-config /workspace/StableSwarmUI/Data/comfy-auto-model.yaml
- **OS:** posix
- **Python Version:** 3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0]
- **Embedded Python:** false
- **PyTorch Version:** 2.4.0+cu121
## Devices

- **Name:** cuda:0 NVIDIA L40S : cudaMallocAsync
  - **Type:** cuda
  - **VRAM Total:** 47803596800
  - **VRAM Free:** 29434052608
  - **Torch VRAM Total:** 0
  - **Torch VRAM Free:** 0

## Logs
```
2024-09-02 08:27:11,253 - root - INFO - Total VRAM 45589 MB, total RAM 515793 MB
2024-09-02 08:27:11,253 - root - INFO - pytorch version: 2.4.0+cu121
2024-09-02 08:27:15,022 - root - INFO - xformers version: 0.0.27.post2
2024-09-02 08:27:15,023 - root - INFO - Set vram state to: NORMAL_VRAM
2024-09-02 08:27:15,023 - root - INFO - Device: cuda:0 NVIDIA L40S : cudaMallocAsync
2024-09-02 08:27:15,491 - root - INFO - Using xformers cross attention
2024-09-02 08:27:17,442 - root - INFO - [Prompt Server] web root: /workspace/StableSwarmUI/dlbackend/ComfyUI/web_custom_versions/Comfy-Org_ComfyUI_frontend/1.2.43
2024-09-02 08:27:17,450 - root - INFO - Adding extra search path checkpoints /workspace/StableSwarmUI/Models/Stable-Diffusion
2024-09-02 08:27:17,450 - root - INFO - Adding extra search path vae /workspace/StableSwarmUI/Models/VAE
2024-09-02 08:27:17,450 - root - INFO - Adding extra search path vae /workspace/StableSwarmUI/Models/VAE
2024-09-02 08:27:17,451 - root - INFO - Adding extra search path loras /workspace/StableSwarmUI/Models/Lora
2024-09-02 08:27:17,451 - root - INFO - Adding extra search path loras /workspace/StableSwarmUI/Models/Lora
2024-09-02 08:27:17,451 - root - INFO - Adding extra search path loras /workspace/StableSwarmUI/Models/LyCORIS
2024-09-02 08:27:17,452 - root - INFO - Adding extra search path upscale_models /workspace/StableSwarmUI/Models/ESRGAN
2024-09-02 08:27:17,452 - root - INFO - Adding extra search path upscale_models /workspace/StableSwarmUI/Models/RealESRGAN
2024-09-02 08:27:17,452 - root - INFO - Adding extra search path upscale_models /workspace/StableSwarmUI/Models/SwinIR
2024-09-02 08:27:17,452 - root - INFO - Adding extra search path upscale_models /workspace/StableSwarmUI/Models/upscale-models
2024-09-02 08:27:17,453 - root - INFO - Adding extra search path upscale_models /workspace/StableSwarmUI/Models/upscale_models
2024-09-02 08:27:17,453 - root - INFO - Adding extra search path embeddings /workspace/StableSwarmUI/Models/Embeddings
2024-09-02 08:27:17,453 - root - INFO - Adding extra search path embeddings /workspace/StableSwarmUI/Models/embeddings
2024-09-02 08:27:17,453 - root - INFO - Adding extra search path hypernetworks /workspace/StableSwarmUI/Models/hypernetworks
2024-09-02 08:27:17,454 - root - INFO - Adding extra search path controlnet /workspace/StableSwarmUI/Models/controlnet
2024-09-02 08:27:17,454 - root - INFO - Adding extra search path controlnet /workspace/StableSwarmUI/Models/ControlNet
2024-09-02 08:27:17,454 - root - INFO - Adding extra search path clip_vision /workspace/StableSwarmUI/Models/clip_vision
2024-09-02 08:27:17,454 - root - INFO - Adding extra search path clip_vision /workspace/StableSwarmUI/Models/clip_vision
2024-09-02 08:27:17,455 - root - INFO - Adding extra search path custom_nodes /workspace/StableSwarmUI/src/BuiltinExtensions/ComfyUIBackend/DLNodes
2024-09-02 08:27:17,455 - root - INFO - Adding extra search path custom_nodes /workspace/StableSwarmUI/src/BuiltinExtensions/ComfyUIBackend/ExtraNodes
2024-09-02 08:27:17,455 - root - INFO - Adding extra search path clip /workspace/StableSwarmUI/Models/clip
2024-09-02 08:27:17,455 - root - INFO - Adding extra search path unet /workspace/StableSwarmUI/Models/unet
2024-09-02 08:27:17,456 - root - INFO - Adding extra search path diffusion_models /workspace/StableSwarmUI/Models/diffusion_models
2024-09-02 08:27:17,456 - root - INFO - Adding extra search path gligen /workspace/StableSwarmUI/Models/gligen
2024-09-02 08:27:17,456 - root - INFO - Adding extra search path ipadapter /workspace/StableSwarmUI/Models/ipadapter
2024-09-02 08:27:17,456 - root - INFO - Adding extra search path yolov8 /workspace/StableSwarmUI/Models/yolov8
2024-09-02 08:27:17,457 - root - INFO - Adding extra search path tensorrt /workspace/StableSwarmUI/Models/tensorrt
2024-09-02 08:27:17,457 - root - INFO - Adding extra search path clipseg /workspace/StableSwarmUI/Models/clipseg
2024-09-02 08:27:17,874 - root - INFO - Successfully imported spandrel_extra_arches: support for non commercial upscale models.
2024-09-02 08:27:19,112 - root - INFO - Total VRAM 45589 MB, total RAM 515793 MB
2024-09-02 08:27:19,113 - root - INFO - pytorch version: 2.4.0+cu121
2024-09-02 08:27:19,113 - root - INFO - xformers version: 0.0.27.post2
2024-09-02 08:27:19,113 - root - INFO - Set vram state to: NORMAL_VRAM
2024-09-02 08:27:19,113 - root - INFO - Device: cuda:0 NVIDIA L40S : cudaMallocAsync
2024-09-02 08:27:22,959 - root - WARNING - Traceback (most recent call last):
  File "/workspace/StableSwarmUI/dlbackend/ComfyUI/nodes.py", line 1993, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1016, in get_code
  File "<frozen importlib._bootstrap_external>", line 1073, in get_data
FileNotFoundError: [Errno 2] No such file or directory: '/workspace/StableSwarmUI/dlbackend/ComfyUI/custom_nodes/.ipynb_checkpoints/__init__.py'

2024-09-02 08:27:22,959 - root - WARNING - Cannot import /workspace/StableSwarmUI/dlbackend/ComfyUI/custom_nodes/.ipynb_checkpoints module for custom nodes: [Errno 2] No such file or directory: '/workspace/StableSwarmUI/dlbackend/ComfyUI/custom_nodes/.ipynb_checkpoints/__init__.py'
2024-09-02 08:27:36,207 - root - INFO - 
Import times for custom nodes:
2024-09-02 08:27:36,207 - root - INFO -    0.0 seconds: /workspace/StableSwarmUI/dlbackend/ComfyUI/custom_nodes/websocket_image_save.py
2024-09-02 08:27:36,207 - root - INFO -    0.0 seconds (IMPORT FAILED): /workspace/StableSwarmUI/dlbackend/ComfyUI/custom_nodes/.ipynb_checkpoints
2024-09-02 08:27:36,207 - root - INFO -    0.0 seconds: /workspace/StableSwarmUI/dlbackend/ComfyUI/custom_nodes/ComfyUI_StableAudio_Open
2024-09-02 08:27:36,207 - root - INFO -    0.0 seconds: /workspace/StableSwarmUI/dlbackend/ComfyUI/custom_nodes/ComfyUI-Universal-Styler
2024-09-02 08:27:36,207 - root - INFO -    0.0 seconds: /workspace/StableSwarmUI/dlbackend/ComfyUI/custom_nodes/cg-image-picker
2024-09-02 08:27:36,207 - root - INFO -    0.0 seconds: /workspace/StableSwarmUI/src/BuiltinExtensions/ComfyUIBackend/DLNodes/sd-dynamic-thresholding
2024-09-02 08:27:36,208 - root - INFO -    0.0 seconds: /workspace/StableSwarmUI/src/BuiltinExtensions/ComfyUIBackend/DLNodes/ComfyUI-SAI_API
2024-09-02 08:27:36,208 - root - INFO -    0.0 seconds: /workspace/StableSwarmUI/dlbackend/ComfyUI/custom_nodes/ComfyUI-AutomaticCFG
2024-09-02 08:27:36,208 - root - INFO -    0.0 seconds: /workspace/StableSwarmUI/src/BuiltinExtensions/ComfyUIBackend/ExtraNodes/SwarmComfyExtra
2024-09-02 08:27:36,208 - root - INFO -    0.0 seconds: /workspace/StableSwarmUI/dlbackend/ComfyUI/custom_nodes/mikey_nodes
2024-09-02 08:27:36,208 - root - INFO -    0.0 seconds: /workspace/StableSwarmUI/src/BuiltinExtensions/ComfyUIBackend/DLNodes/ComfyUI_IPAdapter_plus
2024-09-02 08:27:36,208 - root - INFO -    0.0 seconds: /workspace/StableSwarmUI/dlbackend/ComfyUI/custom_nodes/ComfyUI_essentials
2024-09-02 08:27:36,208 - root - INFO -    0.0 seconds: /workspace/StableSwarmUI/dlbackend/ComfyUI/custom_nodes/ComfyUI-GGUF
2024-09-02 08:27:36,208 - root - INFO -    0.0 seconds: /workspace/StableSwarmUI/dlbackend/ComfyUI/custom_nodes/ComfyUI-Custom-Scripts
2024-09-02 08:27:36,208 - root - INFO -    0.0 seconds: /workspace/StableSwarmUI/dlbackend/ComfyUI/custom_nodes/ComfyUI_UltimateSDUpscale
2024-09-02 08:27:36,209 - root - INFO -    0.0 seconds: /workspace/StableSwarmUI/dlbackend/ComfyUI/custom_nodes/x-flux-comfyui
2024-09-02 08:27:36,209 - root - INFO -    0.0 seconds: /workspace/StableSwarmUI/src/BuiltinExtensions/ComfyUIBackend/DLNodes/ComfyUI-Frame-Interpolation
2024-09-02 08:27:36,209 - root - INFO -    0.0 seconds: /workspace/StableSwarmUI/src/BuiltinExtensions/ComfyUIBackend/ExtraNodes/SwarmComfyCommon
2024-09-02 08:27:36,209 - root - INFO -    0.0 seconds: /workspace/StableSwarmUI/dlbackend/ComfyUI/custom_nodes/rgthree-comfy
2024-09-02 08:27:36,209 - root - INFO -    0.1 seconds: /workspace/StableSwarmUI/src/BuiltinExtensions/ComfyUIBackend/DLNodes/ComfyUI-segment-anything-2
2024-09-02 08:27:36,209 - root - INFO -    0.1 seconds: /workspace/StableSwarmUI/dlbackend/ComfyUI/custom_nodes/ComfyUI_Comfyroll_CustomNodes
2024-09-02 08:27:36,209 - root - INFO -    0.1 seconds: /workspace/StableSwarmUI/dlbackend/ComfyUI/custom_nodes/ComfyUI-Impact-Pack
2024-09-02 08:27:36,210 - root - INFO -    0.1 seconds: /workspace/StableSwarmUI/dlbackend/ComfyUI/custom_nodes/ComfyUI-VideoHelperSuite
2024-09-02 08:27:36,210 - root - INFO -    0.1 seconds: /workspace/StableSwarmUI/dlbackend/ComfyUI/custom_nodes/facerestore_cf
2024-09-02 08:27:36,210 - root - INFO -    0.1 seconds: /workspace/StableSwarmUI/dlbackend/ComfyUI/custom_nodes/ComfyUI-Manager
2024-09-02 08:27:36,210 - root - INFO -    0.2 seconds: /workspace/StableSwarmUI/dlbackend/ComfyUI/custom_nodes/ComfyUI-KJNodes
2024-09-02 08:27:36,210 - root - INFO -    0.2 seconds: /workspace/StableSwarmUI/dlbackend/ComfyUI/custom_nodes/ComfyUI-Crystools
2024-09-02 08:27:36,210 - root - INFO -    0.2 seconds: /workspace/StableSwarmUI/dlbackend/ComfyUI/custom_nodes/comfyui-dynamicprompts
2024-09-02 08:27:36,210 - root - INFO -    0.2 seconds: /workspace/StableSwarmUI/dlbackend/ComfyUI/custom_nodes/ComfyUI-YOLO
2024-09-02 08:27:36,211 - root - INFO -    0.2 seconds: /workspace/StableSwarmUI/dlbackend/ComfyUI/custom_nodes/comfyui-reactor-node
2024-09-02 08:27:36,211 - root - INFO -    0.2 seconds: /workspace/StableSwarmUI/src/BuiltinExtensions/ComfyUIBackend/DLNodes/ComfyUI_bitsandbytes_NF4
2024-09-02 08:27:36,211 - root - INFO -    0.4 seconds: /workspace/StableSwarmUI/dlbackend/ComfyUI/custom_nodes/ComfyUI_ExtraModels
2024-09-02 08:27:36,211 - root - INFO -    0.5 seconds: /workspace/StableSwarmUI/dlbackend/ComfyUI/custom_nodes/ComfyUI-Easy-Use
2024-09-02 08:27:36,211 - root - INFO -    0.8 seconds: /workspace/StableSwarmUI/dlbackend/ComfyUI/custom_nodes/comfy_mtb
2024-09-02 08:27:36,211 - root - INFO -    0.8 seconds: /workspace/StableSwarmUI/dlbackend/ComfyUI/custom_nodes/ComfyUI_VLM_nodes
2024-09-02 08:27:36,211 - root - INFO -    1.0 seconds: /workspace/StableSwarmUI/dlbackend/ComfyUI/custom_nodes/ComfyUI-CogVideoXWrapper
2024-09-02 08:27:36,211 - root - INFO -    1.1 seconds: /workspace/StableSwarmUI/dlbackend/ComfyUI/custom_nodes/AudioConvert.py
2024-09-02 08:27:36,212 - root - INFO -    1.1 seconds: /workspace/StableSwarmUI/dlbackend/ComfyUI/custom_nodes/comfyui_controlnet_aux
2024-09-02 08:27:36,212 - root - INFO -    1.3 seconds: /workspace/StableSwarmUI/dlbackend/ComfyUI/custom_nodes/comfyui-sound-lab
2024-09-02 08:27:36,212 - root - INFO -    7.9 seconds: /workspace/StableSwarmUI/dlbackend/ComfyUI/custom_nodes/ComfyUI-StableAudioSampler
2024-09-02 08:27:36,212 - root - INFO - 
2024-09-02 08:27:36,239 - root - INFO - Starting server

2024-09-02 08:27:36,239 - root - INFO - To see the GUI go to: http://127.0.0.1:7821
2024-09-02 08:29:12,441 - root - INFO - got prompt
2024-09-02 08:29:29,481 - root - ERROR - !!! Exception during processing !!! "check_uniform_bounds" not implemented for 'Float8_e4m3fn'
2024-09-02 08:29:29,500 - root - ERROR - Traceback (most recent call last):
  File "/workspace/StableSwarmUI/dlbackend/ComfyUI/execution.py", line 317, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "/workspace/StableSwarmUI/dlbackend/ComfyUI/execution.py", line 192, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "/workspace/StableSwarmUI/dlbackend/ComfyUI/execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "/workspace/StableSwarmUI/dlbackend/ComfyUI/execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
  File "/workspace/StableSwarmUI/dlbackend/ComfyUI/custom_nodes/ComfyUI-CogVideoXWrapper/nodes.py", line 90, in loadmodel
    pipe = compile_pipe(
  File "/workspace/venv/lib/python3.10/site-packages/onediffx/compilers/diffusion_pipeline_compiler.py", line 66, in compile_pipe
    pipe = fuse_qkv_projections_in_pipe(pipe)
  File "/workspace/venv/lib/python3.10/site-packages/onediffx/compilers/diffusion_pipeline_compiler.py", line 111, in fuse_qkv_projections_in_pipe
    pipe.fuse_qkv_projections()
  File "/workspace/StableSwarmUI/dlbackend/ComfyUI/custom_nodes/ComfyUI-CogVideoXWrapper/pipeline_cogvideox.py", line 256, in fuse_qkv_projections
    self.transformer.fuse_qkv_projections()
  File "/workspace/venv/lib/python3.10/site-packages/diffusers/models/transformers/cogvideox_transformer_3d.py", line 384, in fuse_qkv_projections
    module.fuse_projections(fuse=True)
  File "/workspace/venv/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "/workspace/venv/lib/python3.10/site-packages/diffusers/models/attention_processor.py", line 677, in fuse_projections
    self.to_qkv = nn.Linear(in_features, out_features, bias=self.use_bias, device=device, dtype=dtype)
  File "/workspace/venv/lib/python3.10/site-packages/torch/nn/modules/linear.py", line 104, in __init__
    self.reset_parameters()
  File "/workspace/venv/lib/python3.10/site-packages/torch/nn/modules/linear.py", line 110, in reset_parameters
    init.kaiming_uniform_(self.weight, a=math.sqrt(5))
  File "/workspace/venv/lib/python3.10/site-packages/torch/nn/init.py", line 460, in kaiming_uniform_
    return tensor.uniform_(-bound, bound, generator=generator)
RuntimeError: "check_uniform_bounds" not implemented for 'Float8_e4m3fn'

2024-09-02 08:29:29,502 - root - INFO - Prompt executed in 16.51 seconds
2024-09-02 08:33:38,803 - root - INFO - got prompt
2024-09-02 08:33:46,677 - root - ERROR - !!! Exception during processing !!! "check_uniform_bounds" not implemented for 'Float8_e4m3fn'
2024-09-02 08:33:46,684 - root - ERROR - Traceback (most recent call last):
  File "/workspace/StableSwarmUI/dlbackend/ComfyUI/execution.py", line 317, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "/workspace/StableSwarmUI/dlbackend/ComfyUI/execution.py", line 192, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "/workspace/StableSwarmUI/dlbackend/ComfyUI/execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "/workspace/StableSwarmUI/dlbackend/ComfyUI/execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
  File "/workspace/StableSwarmUI/dlbackend/ComfyUI/custom_nodes/ComfyUI-CogVideoXWrapper/nodes.py", line 90, in loadmodel
    pipe = compile_pipe(
  File "/workspace/venv/lib/python3.10/site-packages/onediffx/compilers/diffusion_pipeline_compiler.py", line 66, in compile_pipe
    pipe = fuse_qkv_projections_in_pipe(pipe)
  File "/workspace/venv/lib/python3.10/site-packages/onediffx/compilers/diffusion_pipeline_compiler.py", line 111, in fuse_qkv_projections_in_pipe
    pipe.fuse_qkv_projections()
  File "/workspace/StableSwarmUI/dlbackend/ComfyUI/custom_nodes/ComfyUI-CogVideoXWrapper/pipeline_cogvideox.py", line 256, in fuse_qkv_projections
    self.transformer.fuse_qkv_projections()
  File "/workspace/venv/lib/python3.10/site-packages/diffusers/models/transformers/cogvideox_transformer_3d.py", line 384, in fuse_qkv_projections
    module.fuse_projections(fuse=True)
  File "/workspace/venv/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "/workspace/venv/lib/python3.10/site-packages/diffusers/models/attention_processor.py", line 677, in fuse_projections
    self.to_qkv = nn.Linear(in_features, out_features, bias=self.use_bias, device=device, dtype=dtype)
  File "/workspace/venv/lib/python3.10/site-packages/torch/nn/modules/linear.py", line 104, in __init__
    self.reset_parameters()
  File "/workspace/venv/lib/python3.10/site-packages/torch/nn/modules/linear.py", line 110, in reset_parameters
    init.kaiming_uniform_(self.weight, a=math.sqrt(5))
  File "/workspace/venv/lib/python3.10/site-packages/torch/nn/init.py", line 460, in kaiming_uniform_
    return tensor.uniform_(-bound, bound, generator=generator)
RuntimeError: "check_uniform_bounds" not implemented for 'Float8_e4m3fn'

2024-09-02 08:33:46,687 - root - INFO - Prompt executed in 7.35 seconds
2024-09-02 08:34:04,070 - root - INFO - got prompt
2024-09-02 08:34:11,776 - root - ERROR - !!! Exception during processing !!! "check_uniform_bounds" not implemented for 'Float8_e4m3fn'
2024-09-02 08:34:11,784 - root - ERROR - Traceback (most recent call last):
  File "/workspace/StableSwarmUI/dlbackend/ComfyUI/execution.py", line 317, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "/workspace/StableSwarmUI/dlbackend/ComfyUI/execution.py", line 192, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "/workspace/StableSwarmUI/dlbackend/ComfyUI/execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "/workspace/StableSwarmUI/dlbackend/ComfyUI/execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
  File "/workspace/StableSwarmUI/dlbackend/ComfyUI/custom_nodes/ComfyUI-CogVideoXWrapper/nodes.py", line 90, in loadmodel
    pipe = compile_pipe(
  File "/workspace/venv/lib/python3.10/site-packages/onediffx/compilers/diffusion_pipeline_compiler.py", line 66, in compile_pipe
    pipe = fuse_qkv_projections_in_pipe(pipe)
  File "/workspace/venv/lib/python3.10/site-packages/onediffx/compilers/diffusion_pipeline_compiler.py", line 111, in fuse_qkv_projections_in_pipe
    pipe.fuse_qkv_projections()
  File "/workspace/StableSwarmUI/dlbackend/ComfyUI/custom_nodes/ComfyUI-CogVideoXWrapper/pipeline_cogvideox.py", line 256, in fuse_qkv_projections
    self.transformer.fuse_qkv_projections()
  File "/workspace/venv/lib/python3.10/site-packages/diffusers/models/transformers/cogvideox_transformer_3d.py", line 384, in fuse_qkv_projections
    module.fuse_projections(fuse=True)
  File "/workspace/venv/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "/workspace/venv/lib/python3.10/site-packages/diffusers/models/attention_processor.py", line 677, in fuse_projections
    self.to_qkv = nn.Linear(in_features, out_features, bias=self.use_bias, device=device, dtype=dtype)
  File "/workspace/venv/lib/python3.10/site-packages/torch/nn/modules/linear.py", line 104, in __init__
    self.reset_parameters()
  File "/workspace/venv/lib/python3.10/site-packages/torch/nn/modules/linear.py", line 110, in reset_parameters
    init.kaiming_uniform_(self.weight, a=math.sqrt(5))
  File "/workspace/venv/lib/python3.10/site-packages/torch/nn/init.py", line 460, in kaiming_uniform_
    return tensor.uniform_(-bound, bound, generator=generator)
RuntimeError: "check_uniform_bounds" not implemented for 'Float8_e4m3fn'

2024-09-02 08:34:11,787 - root - INFO - Prompt executed in 7.18 seconds
```
## Attached Workflow
Please make sure that workflow does not contain any sensitive information such as API keys or passwords.
```
{"last_node_id":39,"last_link_id":75,"nodes":[{"id":20,"type":"CLIPLoader","pos":{"0":-26,"1":400,"2":0,"3":0,"4":0,"5":0,"6":0,"7":0,"8":0,"9":0},"size":{"0":451.30548095703125,"1":82},"flags":{},"order":0,"mode":0,"inputs":[],"outputs":[{"name":"CLIP","type":"CLIP","links":[54,56],"slot_index":0,"shape":3}],"properties":{"Node name for S&R":"CLIPLoader"},"widgets_values":["stableDiffusion3SD3_textEncoderT5XXLFP16.safetensors","sd3"]},{"id":1,"type":"DownloadAndLoadCogVideoModel","pos":{"0":649,"1":182,"2":0,"3":0,"4":0,"5":0,"6":0,"7":0,"8":0,"9":0},"size":{"0":315,"1":154},"flags":{},"order":1,"mode":0,"inputs":[],"outputs":[{"name":"cogvideo_pipe","type":"COGVIDEOPIPE","links":[60],"slot_index":0,"shape":3}],"properties":{"Node name for S&R":"DownloadAndLoadCogVideoModel"},"widgets_values":["THUDM/CogVideoX-5b","bf16",false,"onediff",false]},{"id":34,"type":"CogVideoSampler","pos":{"0":1041,"1":342,"2":0,"3":0,"4":0,"5":0,"6":0,"7":0,"8":0,"9":0},"size":{"0":315.8404846191406,"1":358},"flags":{},"order":4,"mode":0,"inputs":[{"name":"pipeline","type":"COGVIDEOPIPE","link":60},{"name":"positive","type":"CONDITIONING","link":61},{"name":"negative","type":"CONDITIONING","link":62},{"name":"samples","type":"LATENT","link":null}],"outputs":[{"name":"cogvideo_pipe","type":"COGVIDEOPIPE","links":[63],"shape":3},{"name":"samples","type":"LATENT","links":[64],"shape":3}],"properties":{"Node name for S&R":"CogVideoSampler"},"widgets_values":[480,720,49,50,6,291712220140718,"randomize","DPM",49,12,1]},{"id":31,"type":"CogVideoTextEncode","pos":{"0":510,"1":630,"2":0,"3":0,"4":0,"5":0,"6":0,"7":0,"8":0,"9":0},"size":{"0":463.01251220703125,"1":98.10446166992188},"flags":{},"order":3,"mode":0,"inputs":[{"name":"clip","type":"CLIP","link":56}],"outputs":[{"name":"conditioning","type":"CONDITIONING","links":[62],"slot_index":0,"shape":3}],"properties":{"Node name for S&R":"CogVideoTextEncode"},"widgets_values":["cartoon, 3d, anime, sketch, drawing, blur, ugly, watermark"]},{"id":39,"type":"FILM VFI","pos":{"0":1050,"1":105,"2":0,"3":0,"4":0,"5":0,"6":0,"7":0,"8":0,"9":0},"size":{"0":443.4000244140625,"1":126},"flags":{},"order":6,"mode":0,"inputs":[{"name":"frames","type":"IMAGE","link":74},{"name":"optional_interpolation_states","type":"INTERPOLATION_STATES","link":null}],"outputs":[{"name":"IMAGE","type":"IMAGE","links":[75],"slot_index":0,"shape":3}],"properties":{"Node name for S&R":"FILM VFI"},"widgets_values":["film_net_fp32.pt",10,3]},{"id":33,"type":"VHS_VideoCombine","pos":{"0":1575,"1":105,"2":0,"3":0,"4":0,"5":0,"6":0,"7":0,"8":0,"9":0},"size":[690,765],"flags":{},"order":7,"mode":0,"inputs":[{"name":"images","type":"IMAGE","link":75},{"name":"audio","type":"AUDIO","link":null},{"name":"meta_batch","type":"VHS_BatchManager","link":null},{"name":"vae","type":"VAE","link":null}],"outputs":[{"name":"Filenames","type":"VHS_FILENAMES","links":null,"shape":3}],"properties":{"Node name for S&R":"VHS_VideoCombine"},"widgets_values":{"frame_rate":12,"loop_count":0,"filename_prefix":"CogVideoX5B","format":"video/h265-mp4","pix_fmt":"yuv420p10le","crf":8,"save_metadata":true,"pingpong":false,"save_output":true,"videopreview":{"hidden":false,"paused":false,"params":{"filename":"CogVideoX5B_00083.mp4","subfolder":"","type":"output","format":"video/h265-mp4","frame_rate":12},"muted":false}}},{"id":11,"type":"CogVideoDecode","pos":{"0":1140,"1":783,"2":0,"3":0,"4":0,"5":0,"6":0,"7":0,"8":0,"9":0},"size":{"0":210,"1":198},"flags":{},"order":5,"mode":0,"inputs":[{"name":"pipeline","type":"COGVIDEOPIPE","link":63},{"name":"samples","type":"LATENT","link":64}],"outputs":[{"name":"images","type":"IMAGE","links":[74],"slot_index":0,"shape":3}],"properties":{"Node name for S&R":"CogVideoDecode"},"widgets_values":[false,96,96,0.083,0.083,true]},{"id":30,"type":"CogVideoTextEncode","pos":{"0":495,"1":405,"2":0,"3":0,"4":0,"5":0,"6":0,"7":0,"8":0,"9":0},"size":{"0":471.90142822265625,"1":168.08047485351562},"flags":{},"order":2,"mode":0,"inputs":[{"name":"clip","type":"CLIP","link":54}],"outputs":[{"name":"conditioning","type":"CONDITIONING","links":[61],"slot_index":0,"shape":3}],"properties":{"Node name for S&R":"CogVideoTextEncode"},"widgets_values":["A fast-paced scene of a speedboat maneuvering in a narrow Galician estuary, being pursued by a helicopter, illuminated by the bright sunlight piercing through the cloudy sky. Sailboats and beaches can be seen on the periphery, creating a sense of urgency and excitement. The vivid colors and contrasting elements create an immersive visual experience. High-quality footage with professional editing.\n"]}],"links":[[54,20,0,30,0,"CLIP"],[56,20,0,31,0,"CLIP"],[60,1,0,34,0,"COGVIDEOPIPE"],[61,30,0,34,1,"CONDITIONING"],[62,31,0,34,2,"CONDITIONING"],[63,34,0,11,0,"COGVIDEOPIPE"],[64,34,1,11,1,"LATENT"],[74,11,0,39,0,"IMAGE"],[75,39,0,33,0,"IMAGE"]],"groups":[],"config":{},"extra":{"ds":{"scale":0.9090909090909091,"offset":[-277.41334351434034,17.046228889964304]}},"version":0.4}
```

## Additional Context
(Please add any additional context or steps to reproduce the error here)

**Comment by kijai** [comment]
The model loader node was updated with new features, you'll have to re-set the fp8_transformer mode to 'disabled' as it doesn't seem to be supported for your system: 

![image](https://github.com/user-attachments/assets/e72bcd6c-d1ab-40c1-9d8a-895041e7db56)
