### ISSUE TITLE
“list”对象没有属性“shape”

### ISSUE THREAD

**Issue by 1hua-hua** [kijai/ComfyUI-CogVideoXWrapper#47]
'list' object has no attribute 'shape'

**Comment by ikcikoR** [comment]
Getting the same error, log is:

```
!!! Exception during processing !!! 'list' object has no attribute 'shape'
Traceback (most recent call last):
  File "/home/ikcikor/software/ComfyUI/execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ikcikor/software/ComfyUI/execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ikcikor/software/ComfyUI/execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "/home/ikcikor/software/ComfyUI/execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ikcikor/software/ComfyUI/custom_nodes/ComfyUI-CogVideoXWrapper/nodes.py", line 314, in process
    if negative.shape[1] < positive.shape[1]:
       ^^^^^^^^^^^^^^
AttributeError: 'list' object has no attribute 'shape'
```

**Comment by ikcikoR** [comment]
Also here is a screenshot
![image](https://github.com/user-attachments/assets/41f752f4-c818-401d-b0fc-8ed32aaa84ff)

**Comment by ikcikoR** [comment]
Had same issue with a few other clip models I tried, I guess maybe I'm using an incorrect one?

**Comment by kijai** [comment]
You can't use the default text encode nodes, please check the example workflows included for the proper setup.

**Comment by ikcikoR** [comment]
> You can't use the default text encode nodes, please check the example workflows included for the proper setup.

Ahhhh my bad, they looked very similar and I missed the fact that they're different nodes

**Comment by chenxiuqi2** [comment]
I made the same mistake as you, bro.
