### ISSUE TITLE
Import Failed and missing nodes

### ISSUE THREAD

**Issue by Gyramuur** [kijai/ComfyUI-CogVideoXWrapper#5]
Tried to use the example_01.json but it didn't import correctly and is missing a bunch of nodes. Here's the full console log:

```
Z:\webui\ComfyUI_windows_portable>.\python_embeded\python.exe -s ComfyUI\main.py --windows-standalone-build --gpu-only
[START] Security scan
[DONE] Security scan
## ComfyUI-Manager: installing dependencies done.
** ComfyUI startup time: 2024-08-08 23:13:09.890191
** Platform: Windows
** Python version: 3.11.6 (tags/v3.11.6:8b6ee5b, Oct  2 2023, 14:57:12) [MSC v.1935 64 bit (AMD64)]
** Python executable: Z:\webui\ComfyUI_windows_portable\python_embeded\python.exe
** ComfyUI Path: Z:\webui\ComfyUI_windows_portable\ComfyUI
** Log path: Z:\webui\ComfyUI_windows_portable\comfyui.log

Prestartup times for custom nodes:
   0.0 seconds: Z:\webui\ComfyUI_windows_portable\ComfyUI\custom_nodes\rgthree-comfy
   1.5 seconds: Z:\webui\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager-main

Total VRAM 24576 MB, total RAM 32694 MB
pytorch version: 2.4.0+cu121
Set vram state to: HIGH_VRAM
Device: cuda:0 NVIDIA GeForce RTX 3090 : cudaMallocAsync
Using pytorch cross attention
[Prompt Server] web root: Z:\webui\ComfyUI_windows_portable\ComfyUI\web
Z:\webui\ComfyUI_windows_portable\python_embeded\Lib\site-packages\kornia\feature\lightglue.py:44: FutureWarning: `torch.cuda.amp.custom_fwd(args...)` is deprecated. Please use `torch.amp.custom_fwd(args..., device_type='cuda')` instead.
  @torch.cuda.amp.custom_fwd(cast_inputs=torch.float32)
Traceback (most recent call last):
  File "Z:\webui\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1941, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "Z:\webui\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-CogVideoXWrapper-main\__init__.py", line 1, in <module>
    from .nodes import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "Z:\webui\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-CogVideoXWrapper-main\nodes.py", line 6, in <module>
    from diffusers.schedulers import CogVideoXDDIMScheduler, CogVideoXDPMScheduler
ImportError: cannot import name 'CogVideoXDDIMScheduler' from 'diffusers.schedulers' (Z:\webui\ComfyUI_windows_portable\python_embeded\Lib\site-packages\diffusers\schedulers\__init__.py)

Cannot import Z:\webui\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-CogVideoXWrapper-main module for custom nodes: cannot import name 'CogVideoXDDIMScheduler' from 'diffusers.schedulers' (Z:\webui\ComfyUI_windows_portable\python_embeded\Lib\site-packages\diffusers\schedulers\__init__.py)
### Loading: ComfyUI-Manager (V2.48.4)
### ComfyUI Revision: 2489 [8115d8cc] | Released on '2024-08-07'
Failed to auto update `Quality of Life Suit`
QualityOfLifeSuit_Omar92_DIR: Z:\webui\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-QualityOfLifeSuit_Omar92
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/alter-list.json[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/model-list.json[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/github-stats.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json

[rgthree] Loaded 20 exciting nodes.
[rgthree] Optimizing ComfyUI recursive execution. If queueing and/or re-queueing seems broken, change "patch_recursive_execution" to false in rgthree_config.json


Import times for custom nodes:
   0.0 seconds: Z:\webui\ComfyUI_windows_portable\ComfyUI\custom_nodes\websocket_image_save.py
   0.0 seconds: Z:\webui\ComfyUI_windows_portable\ComfyUI\custom_nodes\prompt_injection.py
   0.0 seconds: Z:\webui\ComfyUI_windows_portable\ComfyUI\custom_nodes\sdxl_prompt_styler
   0.0 seconds: Z:\webui\ComfyUI_windows_portable\ComfyUI\custom_nodes\prompt_injection-main
   0.0 seconds: Z:\webui\ComfyUI_windows_portable\ComfyUI\custom_nodes\ELLA
   0.0 seconds: Z:\webui\ComfyUI_windows_portable\ComfyUI\custom_nodes\StableZero123-comfyui
   0.0 seconds: Z:\webui\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyMath
   0.0 seconds: Z:\webui\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-QualityOfLifeSuit_Omar92
   0.0 seconds: Z:\webui\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Frame-Interpolation
   0.0 seconds: Z:\webui\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Shinsplat-main
   0.0 seconds: Z:\webui\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-DareMerge-master
   0.0 seconds: Z:\webui\ComfyUI_windows_portable\ComfyUI\custom_nodes\rgthree-comfy
   0.0 seconds: Z:\webui\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_essentials
   0.0 seconds: Z:\webui\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_ExtraModels
   0.0 seconds: Z:\webui\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Flowty-TripoSR
   0.0 seconds: Z:\webui\ComfyUI_windows_portable\ComfyUI\custom_nodes\Derfuu_ComfyUI_ModdedNodes
   0.0 seconds (IMPORT FAILED): Z:\webui\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-CogVideoXWrapper-main
   0.0 seconds: Z:\webui\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-VideoHelperSuite
   0.2 seconds: Z:\webui\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-ELLA-wrapper
   0.3 seconds: Z:\webui\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager-main
   0.4 seconds: Z:\webui\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-DareMerge
   0.4 seconds: Z:\webui\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Flowty-CRM

Starting server

To see the GUI go to: http://127.0.0.1:8188
FETCH DATA from: Z:\webui\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager-main\extension-node-map.json [DONE]
Error: OpenAI API key is invalid OpenAI features wont work for you
QualityOfLifeSuit_Omar92::NSP ready
```

**Comment by kijai** [comment]
`ImportError: cannot import name 'CogVideoXDDIMScheduler' from 'diffusers.schedulers'`

Means you have to update to diffusers 0.30.0, it came out yesterday and added official support for CogVideoX.

**Comment by Gyramuur** [comment]
> `ImportError: cannot import name 'CogVideoXDDIMScheduler' from 'diffusers.schedulers'`
> 
> Means you have to update to diffusers 0.30.0, it came out yesterday and added official support for CogVideoX.

Is there a way to get it to recognise that I already have it? I installed diffusers 0.30.0 earlier when setting up the cli_demo from the official repo. When I navigate into "ComfyUI-CogVideoXWrapper-main" and run "pip install -r requirements.txt", it doesn't install anything because it says the requirements are already satisfied:

```
Z:\webui\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-CogVideoXWrapper-main>pip install -r requirements.txt
Requirement already satisfied: huggingface_hub in c:\users\gyramuur\appdata\local\programs\python\python310\lib\site-packages (from -r requirements.txt (line 1)) (0.24.5)
Requirement already satisfied: diffusers>=0.30.0 in c:\users\gyramuur\appdata\local\programs\python\python310\lib\site-packages (from -r requirements.txt (line 2)) (0.30.0)
Requirement already satisfied: filelock in c:\users\gyramuur\appdata\local\programs\python\python310\lib\site-packages (from huggingface_hub->-r requirements.txt (line 1)) (3.12.2)
Requirement already satisfied: fsspec>=2023.5.0 in c:\users\gyramuur\appdata\local\programs\python\python310\lib\site-packages (from huggingface_hub->-r requirements.txt (line 1)) (2023.6.0)
Requirement already satisfied: packaging>=20.9 in c:\users\gyramuur\appdata\local\programs\python\python310\lib\site-packages (from huggingface_hub->-r requirements.txt (line 1)) (24.0)
Requirement already satisfied: pyyaml>=5.1 in c:\users\gyramuur\appdata\local\programs\python\python310\lib\site-packages (from huggingface_hub->-r requirements.txt (line 1)) (6.0.1)
Requirement already satisfied: requests in c:\users\gyramuur\appdata\local\programs\python\python310\lib\site-packages (from huggingface_hub->-r requirements.txt (line 1)) (2.31.0)
Requirement already satisfied: tqdm>=4.42.1 in c:\users\gyramuur\appdata\local\programs\python\python310\lib\site-packages (from huggingface_hub->-r requirements.txt (line 1)) (4.66.1)
Requirement already satisfied: typing-extensions>=3.7.4.3 in c:\users\gyramuur\appdata\local\programs\python\python310\lib\site-packages (from huggingface_hub->-r requirements.txt (line 1)) (4.8.0)
Requirement already satisfied: importlib-metadata in c:\users\gyramuur\appdata\local\programs\python\python310\lib\site-packages (from diffusers>=0.30.0->-r requirements.txt (line 2)) (6.8.0)
Requirement already satisfied: numpy in c:\users\gyramuur\appdata\local\programs\python\python310\lib\site-packages (from diffusers>=0.30.0->-r requirements.txt (line 2)) (1.23.5)
Requirement already satisfied: regex!=2019.12.17 in c:\users\gyramuur\appdata\local\programs\python\python310\lib\site-packages (from diffusers>=0.30.0->-r requirements.txt (line 2)) (2023.8.8)
Requirement already satisfied: safetensors>=0.3.1 in c:\users\gyramuur\appdata\local\programs\python\python310\lib\site-packages (from diffusers>=0.30.0->-r requirements.txt (line 2)) (0.4.4)
Requirement already satisfied: Pillow in c:\users\gyramuur\appdata\local\programs\python\python310\lib\site-packages (from diffusers>=0.30.0->-r requirements.txt (line 2)) (10.1.0)
Requirement already satisfied: colorama in c:\users\gyramuur\appdata\local\programs\python\python310\lib\site-packages (from tqdm>=4.42.1->huggingface_hub->-r requirements.txt (line 1)) (0.4.3)
Requirement already satisfied: zipp>=0.5 in c:\users\gyramuur\appdata\local\programs\python\python310\lib\site-packages (from importlib-metadata->diffusers>=0.30.0->-r requirements.txt (line 2)) (3.16.2)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\gyramuur\appdata\local\programs\python\python310\lib\site-packages (from requests->huggingface_hub->-r requirements.txt (line 1)) (2.0.12)
Requirement already satisfied: idna<4,>=2.5 in c:\users\gyramuur\appdata\local\programs\python\python310\lib\site-packages (from requests->huggingface_hub->-r requirements.txt (line 1)) (3.3)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\gyramuur\appdata\local\programs\python\python310\lib\site-packages (from requests->huggingface_hub->-r requirements.txt (line 1)) (1.26.15)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\gyramuur\appdata\local\programs\python\python310\lib\site-packages (from requests->huggingface_hub->-r requirements.txt (line 1)) (2023.7.22)

Z:\webui\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-CogVideoXWrapper-main>
```

**Comment by kijai** [comment]
You are using a portable ComfyUI install, which means it has it's own python environment, and you have installed the requirements to your system python environment, which is the default when doing just `pip install `

To install dependencies to the portable ComfUI installation, you have to use it's own python.exe located in it's `python_embeded ` folder, like so:

run this in ComfyUI_windows_portable -folder:

`python_embeded\python.exe -m pip install -r ComfyUI\custom_nodes\ComfyUI-CogVideoXWrapper-main\requirements.txt`

**Comment by Gyramuur** [comment]
> You are using a portable ComfyUI install, which means it has it's own python environment, and you have installed the requirements to your system python environment, which is the default when doing just `pip install `
> 
> To install dependencies to the portable ComfUI installation, you have to use it's own python.exe located in it's `python_embeded ` folder, like so:
> 
> run this in ComfyUI_windows_portable -folder:
> 
> `python_embeded\python.exe -m pip install -r ComfyUI\custom_nodes\ComfyUI-CogVideoXWrapper-main\requirements.txt`

That worked, thank you. :D
