### ISSUE TITLE
DownloadAndLoadCogVideoModel -- Error no file named diffusion_pytorch_model.bin

### ISSUE THREAD

**Issue by drgumshoe** [kijai/ComfyUI-CogVideoXWrapper#55]
The issue looks like a missing file but I'm no programmer. I included the workflow towards the end. 

# ComfyUI Error Report
## Error Details
- **Node Type:** DownloadAndLoadCogVideoModel
- **Exception Type:** OSError
- **Exception Message:** Error no file named diffusion_pytorch_model.bin found in directory C:\Users\mwall\Downloads\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\models\CogVideo\CogVideoX-5b.
## Stack Trace
```
  File "C:\Users\mwall\Downloads\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "C:\Users\mwall\Downloads\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "C:\Users\mwall\Downloads\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)

  File "C:\Users\mwall\Downloads\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "C:\Users\mwall\Downloads\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-CogVideoXWrapper\nodes.py", line 82, in loadmodel
    vae = AutoencoderKLCogVideoX.from_pretrained(base_path, subfolder="vae").to(dtype).to(offload_device)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "C:\Users\mwall\Downloads\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\python_embeded\Lib\site-packages\huggingface_hub\utils\_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^

  File "C:\Users\mwall\Downloads\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\python_embeded\Lib\site-packages\diffusers\models\modeling_utils.py", line 713, in from_pretrained
    model_file = _get_model_file(
                 ^^^^^^^^^^^^^^^^

  File "C:\Users\mwall\Downloads\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\python_embeded\Lib\site-packages\huggingface_hub\utils\_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^

  File "C:\Users\mwall\Downloads\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\python_embeded\Lib\site-packages\diffusers\utils\hub_utils.py", line 310, in _get_model_file
    raise EnvironmentError(

```
## System Information
- **ComfyUI Version:** v0.2.2-41-gca08597
- **Arguments:** ComfyUI\main.py --windows-standalone-build
- **OS:** nt
- **Python Version:** 3.11.9 (tags/v3.11.9:de54cf5, Apr  2 2024, 10:12:12) [MSC v.1938 64 bit (AMD64)]
- **Embedded Python:** true
- **PyTorch Version:** 2.4.1+cu124
## Devices

- **Name:** cuda:0 NVIDIA RTX 3000 Ada Generation Laptop GPU : cudaMallocAsync
  - **Type:** cuda
  - **VRAM Total:** 8585216000
  - **VRAM Free:** 7348289536
  - **Torch VRAM Total:** 33554432
  - **Torch VRAM Free:** 25034752

## Logs
```
2024-09-15 07:39:33,179 - root - INFO - Total VRAM 8188 MB, total RAM 64969 MB
2024-09-15 07:39:33,179 - root - INFO - pytorch version: 2.4.1+cu124
2024-09-15 07:39:33,180 - root - INFO - Set vram state to: NORMAL_VRAM
2024-09-15 07:39:33,180 - root - INFO - Device: cuda:0 NVIDIA RTX 3000 Ada Generation Laptop GPU : cudaMallocAsync
2024-09-15 07:39:35,126 - root - INFO - Using pytorch cross attention
2024-09-15 07:39:38,497 - root - INFO - [Prompt Server] web root: C:\Users\mwall\Downloads\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\web
2024-09-15 07:39:42,535 - root - INFO - Total VRAM 8188 MB, total RAM 64969 MB
2024-09-15 07:39:42,535 - root - INFO - pytorch version: 2.4.1+cu124
2024-09-15 07:39:42,536 - root - INFO - Set vram state to: NORMAL_VRAM
2024-09-15 07:39:42,536 - root - INFO - Device: cuda:0 NVIDIA RTX 3000 Ada Generation Laptop GPU : cudaMallocAsync
2024-09-15 07:39:45,837 - root - INFO - 
Import times for custom nodes:
2024-09-15 07:39:45,837 - root - INFO -    0.0 seconds: C:\Users\mwall\Downloads\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\websocket_image_save.py
2024-09-15 07:39:45,837 - root - INFO -    0.0 seconds: C:\Users\mwall\Downloads\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\Stable-Diffusion-temperature-settings
2024-09-15 07:39:45,837 - root - INFO -    0.0 seconds: C:\Users\mwall\Downloads\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus
2024-09-15 07:39:45,837 - root - INFO -    0.0 seconds: C:\Users\mwall\Downloads\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Advanced-ControlNet
2024-09-15 07:39:45,837 - root - INFO -    0.0 seconds: C:\Users\mwall\Downloads\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Frame-Interpolation
2024-09-15 07:39:45,838 - root - INFO -    0.0 seconds: C:\Users\mwall\Downloads\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_essentials
2024-09-15 07:39:45,838 - root - INFO -    0.0 seconds: C:\Users\mwall\Downloads\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-AnimateDiff-Evolved
2024-09-15 07:39:45,838 - root - INFO -    0.1 seconds: C:\Users\mwall\Downloads\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_smZNodes
2024-09-15 07:39:45,838 - root - INFO -    0.1 seconds: C:\Users\mwall\Downloads\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-KJNodes
2024-09-15 07:39:45,838 - root - INFO -    0.3 seconds: C:\Users\mwall\Downloads\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager
2024-09-15 07:39:45,838 - root - INFO -    0.3 seconds: C:\Users\mwall\Downloads\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-CogVideoXWrapper
2024-09-15 07:39:45,839 - root - INFO -    0.5 seconds: C:\Users\mwall\Downloads\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-VideoHelperSuite
2024-09-15 07:39:45,839 - root - INFO -    2.3 seconds: C:\Users\mwall\Downloads\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfy_mtb
2024-09-15 07:39:45,839 - root - INFO - 
2024-09-15 07:39:45,845 - root - INFO - Starting server

2024-09-15 07:39:45,845 - root - INFO - To see the GUI go to: http://127.0.0.1:8188
2024-09-15 07:40:40,134 - root - INFO - got prompt
2024-09-15 07:40:43,828 - root - INFO - Requested to load SD3ClipModel_
2024-09-15 07:40:43,829 - root - INFO - Loading 1 new model
2024-09-15 07:40:43,833 - root - INFO - loaded partially 1083.1066368103027 1077.693359375 0
2024-09-15 07:40:46,022 - root - INFO - loaded partially 2124.674996185303 2117.693359375 0
2024-09-15 07:40:58,281 - root - ERROR - !!! Exception during processing !!! Error no file named diffusion_pytorch_model.bin found in directory C:\Users\mwall\Downloads\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\models\CogVideo\CogVideoX-5b.
2024-09-15 07:40:58,324 - root - ERROR - Traceback (most recent call last):
  File "C:\Users\mwall\Downloads\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mwall\Downloads\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mwall\Downloads\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "C:\Users\mwall\Downloads\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mwall\Downloads\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-CogVideoXWrapper\nodes.py", line 82, in loadmodel
    vae = AutoencoderKLCogVideoX.from_pretrained(base_path, subfolder="vae").to(dtype).to(offload_device)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mwall\Downloads\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\python_embeded\Lib\site-packages\huggingface_hub\utils\_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mwall\Downloads\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\python_embeded\Lib\site-packages\diffusers\models\modeling_utils.py", line 713, in from_pretrained
    model_file = _get_model_file(
                 ^^^^^^^^^^^^^^^^
  File "C:\Users\mwall\Downloads\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\python_embeded\Lib\site-packages\huggingface_hub\utils\_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mwall\Downloads\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\python_embeded\Lib\site-packages\diffusers\utils\hub_utils.py", line 310, in _get_model_file
    raise EnvironmentError(
OSError: Error no file named diffusion_pytorch_model.bin found in directory C:\Users\mwall\Downloads\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\models\CogVideo\CogVideoX-5b.

2024-09-15 07:40:58,326 - root - INFO - Prompt executed in 18.17 seconds
2024-09-15 07:43:26,216 - root - INFO - got prompt
2024-09-15 07:43:35,225 - root - ERROR - !!! Exception during processing !!! Error no file named diffusion_pytorch_model.bin found in directory C:\Users\mwall\Downloads\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\models\CogVideo\CogVideoX-5b.
2024-09-15 07:43:35,226 - root - ERROR - Traceback (most recent call last):
  File "C:\Users\mwall\Downloads\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mwall\Downloads\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mwall\Downloads\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "C:\Users\mwall\Downloads\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mwall\Downloads\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-CogVideoXWrapper\nodes.py", line 82, in loadmodel
    vae = AutoencoderKLCogVideoX.from_pretrained(base_path, subfolder="vae").to(dtype).to(offload_device)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mwall\Downloads\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\python_embeded\Lib\site-packages\huggingface_hub\utils\_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mwall\Downloads\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\python_embeded\Lib\site-packages\diffusers\models\modeling_utils.py", line 713, in from_pretrained
    model_file = _get_model_file(
                 ^^^^^^^^^^^^^^^^
  File "C:\Users\mwall\Downloads\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\python_embeded\Lib\site-packages\huggingface_hub\utils\_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mwall\Downloads\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\python_embeded\Lib\site-packages\diffusers\utils\hub_utils.py", line 310, in _get_model_file
    raise EnvironmentError(
OSError: Error no file named diffusion_pytorch_model.bin found in directory C:\Users\mwall\Downloads\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\models\CogVideo\CogVideoX-5b.

2024-09-15 07:43:35,227 - root - INFO - Prompt executed in 8.99 seconds
```
## Attached Workflow
Please make sure that workflow does not contain any sensitive information such as API keys or passwords.
```
{"last_node_id":33,"last_link_id":60,"nodes":[{"id":30,"type":"CogVideoTextEncode","pos":{"0":350,"1":100},"size":{"0":474.8450012207031,"1":164.7423553466797},"flags":{},"order":2,"mode":0,"inputs":[{"name":"clip","type":"CLIP","link":54}],"outputs":[{"name":"conditioning","type":"CONDITIONING","links":[55],"slot_index":0,"shape":3}],"properties":{"Node name for S&R":"CogVideoTextEncode"},"widgets_values":["A panda, dressed in a small, red jacket and a tiny hat, sits on a wooden stool in a serene bamboo forest. The panda's fluffy paws strum a miniature\nacoustic guitar, producing soft, melodic tunes. Nearby, a few other pandas gather, watching curiously and some clapping in rhythm. Sunlight filters\nthrough the tall bamboo, casting a gentle glow on the scene. The panda's face is expressive, showing concentration and joy as it plays. The\nbackground includes a small, flowing stream and vibrant green foliage, enhancing the peaceful and magical atmosphere of this unique musical\nperformance."]},{"id":32,"type":"VHS_VideoCombine","pos":{"0":1770,"1":196},"size":[563.3333740234375,310],"flags":{},"order":7,"mode":0,"inputs":[{"name":"images","type":"IMAGE","link":60,"slot_index":0},{"name":"audio","type":"VHS_AUDIO","link":null},{"name":"meta_batch","type":"VHS_BatchManager","link":null},{"name":"vae","type":"VAE","link":null}],"outputs":[{"name":"Filenames","type":"VHS_FILENAMES","links":null,"shape":3}],"properties":{"Node name for S&R":"VHS_VideoCombine"},"widgets_values":{"frame_rate":8,"loop_count":0,"filename_prefix":"CogVideo2B_long","format":"video/h264-mp4","pix_fmt":"yuv420p","crf":19,"save_metadata":true,"pingpong":false,"save_output":false,"videopreview":{"hidden":false,"paused":false,"params":{"filename":"AnimateDiff_00001.mp4","subfolder":"","type":"temp","format":"video/h264-mp4","frame_rate":8}}}},{"id":33,"type":"GetImageSizeAndCount","pos":{"0":1523,"1":196},"size":{"0":210,"1":86},"flags":{},"order":6,"mode":0,"inputs":[{"name":"image","type":"IMAGE","link":59}],"outputs":[{"name":"image","type":"IMAGE","links":[60],"slot_index":0,"shape":3},{"name":"720 width","type":"INT","links":null,"shape":3},{"name":"480 height","type":"INT","links":null,"shape":3},{"name":"32 count","type":"INT","links":null,"shape":3}],"properties":{"Node name for S&R":"GetImageSizeAndCount"}},{"id":11,"type":"CogVideoDecode","pos":{"0":1270,"1":196},"size":{"0":210,"1":198},"flags":{},"order":5,"mode":0,"inputs":[{"name":"pipeline","type":"COGVIDEOPIPE","link":37},{"name":"samples","type":"LATENT","link":38}],"outputs":[{"name":"images","type":"IMAGE","links":[59],"slot_index":0,"shape":3}],"properties":{"Node name for S&R":"CogVideoDecode"},"widgets_values":[false,96,96,0.083,0.083,true]},{"id":22,"type":"CogVideoSampler","pos":{"0":926,"1":196},"size":{"0":315,"1":382},"flags":{},"order":4,"mode":0,"inputs":[{"name":"pipeline","type":"COGVIDEOPIPE","link":36},{"name":"positive","type":"CONDITIONING","link":55,"slot_index":1},{"name":"negative","type":"CONDITIONING","link":57},{"name":"samples","type":"LATENT","link":null}],"outputs":[{"name":"cogvideo_pipe","type":"COGVIDEOPIPE","links":[37],"shape":3},{"name":"samples","type":"LATENT","links":[38],"shape":3}],"properties":{"Node name for S&R":"CogVideoSampler"},"widgets_values":[480,720,96,25,6,6,806286757407563,"DDIM",48,8,1]},{"id":20,"type":"CLIPLoader","pos":{"0":-69,"1":216},"size":{"0":318.91986083984375,"1":82},"flags":{},"order":0,"mode":0,"inputs":[],"outputs":[{"name":"CLIP","type":"CLIP","links":[54,56],"slot_index":0,"shape":3}],"properties":{"Node name for S&R":"CLIPLoader"},"widgets_values":["t5xxl_fp8_e4m3fn.safetensors","sd3"]},{"id":31,"type":"CogVideoTextEncode","pos":{"0":497,"1":371},"size":{"0":468.02996826171875,"1":93.28540802001953},"flags":{"collapsed":true},"order":3,"mode":0,"inputs":[{"name":"clip","type":"CLIP","link":56}],"outputs":[{"name":"conditioning","type":"CONDITIONING","links":[57],"slot_index":0,"shape":3}],"properties":{"Node name for S&R":"CogVideoTextEncode"},"widgets_values":[""]},{"id":1,"type":"DownloadAndLoadCogVideoModel","pos":{"0":502,"1":-87},"size":{"0":315,"1":154},"flags":{},"order":1,"mode":0,"inputs":[],"outputs":[{"name":"cogvideo_pipe","type":"COGVIDEOPIPE","links":[36],"slot_index":0,"shape":3}],"properties":{"Node name for S&R":"DownloadAndLoadCogVideoModel"},"widgets_values":["THUDM/CogVideoX-5b","fp16","fastmode","disabled",false]}],"links":[[36,1,0,22,0,"COGVIDEOPIPE"],[37,22,0,11,0,"COGVIDEOPIPE"],[38,22,1,11,1,"LATENT"],[54,20,0,30,0,"CLIP"],[55,30,0,22,1,"CONDITIONING"],[56,20,0,31,0,"CLIP"],[57,31,0,22,2,"CONDITIONING"],[59,11,0,33,0,"IMAGE"],[60,33,0,32,0,"IMAGE"]],"groups":[],"config":{},"extra":{"ds":{"scale":1.1000000000000008,"offset":[-80.90911310369373,204.18181956898033]}},"version":0.4}
```

## Workflow##
{
  "last_node_id": 33,
  "last_link_id": 60,
  "nodes": [
    {
      "id": 30,
      "type": "CogVideoTextEncode",
      "pos": {
        "0": 350,
        "1": 100
      },
      "size": {
        "0": 474.8450012207031,
        "1": 164.7423553466797
      },
      "flags": {},
      "order": 2,
      "mode": 0,
      "inputs": [
        {
          "name": "clip",
          "type": "CLIP",
          "link": 54
        }
      ],
      "outputs": [
        {
          "name": "conditioning",
          "type": "CONDITIONING",
          "links": [
            55
          ],
          "slot_index": 0,
          "shape": 3
        }
      ],
      "properties": {
        "Node name for S&R": "CogVideoTextEncode"
      },
      "widgets_values": [
        "A panda, dressed in a small, red jacket and a tiny hat, sits on a wooden stool in a serene bamboo forest. The panda's fluffy paws strum a miniature\nacoustic guitar, producing soft, melodic tunes. Nearby, a few other pandas gather, watching curiously and some clapping in rhythm. Sunlight filters\nthrough the tall bamboo, casting a gentle glow on the scene. The panda's face is expressive, showing concentration and joy as it plays. The\nbackground includes a small, flowing stream and vibrant green foliage, enhancing the peaceful and magical atmosphere of this unique musical\nperformance."
      ]
    },
    {
      "id": 32,
      "type": "VHS_VideoCombine",
      "pos": {
        "0": 1770,
        "1": 196
      },
      "size": [
        563.3333740234375,
        310
      ],
      "flags": {},
      "order": 7,
      "mode": 0,
      "inputs": [
        {
          "name": "images",
          "type": "IMAGE",
          "link": 60,
          "slot_index": 0
        },
        {
          "name": "audio",
          "type": "VHS_AUDIO",
          "link": null
        },
        {
          "name": "meta_batch",
          "type": "VHS_BatchManager",
          "link": null
        },
        {
          "name": "vae",
          "type": "VAE",
          "link": null
        }
      ],
      "outputs": [
        {
          "name": "Filenames",
          "type": "VHS_FILENAMES",
          "links": null,
          "shape": 3
        }
      ],
      "properties": {
        "Node name for S&R": "VHS_VideoCombine"
      },
      "widgets_values": {
        "frame_rate": 8,
        "loop_count": 0,
        "filename_prefix": "CogVideo2B_long",
        "format": "video/h264-mp4",
        "pix_fmt": "yuv420p",
        "crf": 19,
        "save_metadata": true,
        "pingpong": false,
        "save_output": false,
        "videopreview": {
          "hidden": false,
          "paused": false,
          "params": {
            "filename": "AnimateDiff_00001.mp4",
            "subfolder": "",
            "type": "temp",
            "format": "video/h264-mp4",
            "frame_rate": 8
          }
        }
      }
    },
    {
      "id": 33,
      "type": "GetImageSizeAndCount",
      "pos": {
        "0": 1523,
        "1": 196
      },
      "size": {
        "0": 210,
        "1": 86
      },
      "flags": {},
      "order": 6,
      "mode": 0,
      "inputs": [
        {
          "name": "image",
          "type": "IMAGE",
          "link": 59
        }
      ],
      "outputs": [
        {
          "name": "image",
          "type": "IMAGE",
          "links": [
            60
          ],
          "slot_index": 0,
          "shape": 3
        },
        {
          "name": "720 width",
          "type": "INT",
          "links": null,
          "shape": 3
        },
        {
          "name": "480 height",
          "type": "INT",
          "links": null,
          "shape": 3
        },
        {
          "name": "32 count",
          "type": "INT",
          "links": null,
          "shape": 3
        }
      ],
      "properties": {
        "Node name for S&R": "GetImageSizeAndCount"
      }
    },
    {
      "id": 11,
      "type": "CogVideoDecode",
      "pos": {
        "0": 1270,
        "1": 196
      },
      "size": {
        "0": 210,
        "1": 198
      },
      "flags": {},
      "order": 5,
      "mode": 0,
      "inputs": [
        {
          "name": "pipeline",
          "type": "COGVIDEOPIPE",
          "link": 37
        },
        {
          "name": "samples",
          "type": "LATENT",
          "link": 38
        }
      ],
      "outputs": [
        {
          "name": "images",
          "type": "IMAGE",
          "links": [
            59
          ],
          "slot_index": 0,
          "shape": 3
        }
      ],
      "properties": {
        "Node name for S&R": "CogVideoDecode"
      },
      "widgets_values": [
        false,
        96,
        96,
        0.083,
        0.083,
        true
      ]
    },
    {
      "id": 22,
      "type": "CogVideoSampler",
      "pos": {
        "0": 926,
        "1": 196
      },
      "size": {
        "0": 315,
        "1": 382
      },
      "flags": {},
      "order": 4,
      "mode": 0,
      "inputs": [
        {
          "name": "pipeline",
          "type": "COGVIDEOPIPE",
          "link": 36
        },
        {
          "name": "positive",
          "type": "CONDITIONING",
          "link": 55,
          "slot_index": 1
        },
        {
          "name": "negative",
          "type": "CONDITIONING",
          "link": 57
        },
        {
          "name": "samples",
          "type": "LATENT",
          "link": null
        }
      ],
      "outputs": [
        {
          "name": "cogvideo_pipe",
          "type": "COGVIDEOPIPE",
          "links": [
            37
          ],
          "shape": 3
        },
        {
          "name": "samples",
          "type": "LATENT",
          "links": [
            38
          ],
          "shape": 3
        }
      ],
      "properties": {
        "Node name for S&R": "CogVideoSampler"
      },
      "widgets_values": [
        480,
        720,
        96,
        25,
        6,
        6,
        806286757407563,
        "DDIM",
        48,
        8,
        1
      ]
    },
    {
      "id": 20,
      "type": "CLIPLoader",
      "pos": {
        "0": -69,
        "1": 216
      },
      "size": {
        "0": 318.91986083984375,
        "1": 82
      },
      "flags": {},
      "order": 0,
      "mode": 0,
      "inputs": [],
      "outputs": [
        {
          "name": "CLIP",
          "type": "CLIP",
          "links": [
            54,
            56
          ],
          "slot_index": 0,
          "shape": 3
        }
      ],
      "properties": {
        "Node name for S&R": "CLIPLoader"
      },
      "widgets_values": [
        "t5xxl_fp8_e4m3fn.safetensors",
        "sd3"
      ]
    },
    {
      "id": 31,
      "type": "CogVideoTextEncode",
      "pos": {
        "0": 497,
        "1": 371
      },
      "size": {
        "0": 468.02996826171875,
        "1": 93.28540802001953
      },
      "flags": {
        "collapsed": true
      },
      "order": 3,
      "mode": 0,
      "inputs": [
        {
          "name": "clip",
          "type": "CLIP",
          "link": 56
        }
      ],
      "outputs": [
        {
          "name": "conditioning",
          "type": "CONDITIONING",
          "links": [
            57
          ],
          "slot_index": 0,
          "shape": 3
        }
      ],
      "properties": {
        "Node name for S&R": "CogVideoTextEncode"
      },
      "widgets_values": [
        ""
      ]
    },
    {
      "id": 1,
      "type": "DownloadAndLoadCogVideoModel",
      "pos": {
        "0": 502,
        "1": -87
      },
      "size": {
        "0": 315,
        "1": 154
      },
      "flags": {},
      "order": 1,
      "mode": 0,
      "inputs": [],
      "outputs": [
        {
          "name": "cogvideo_pipe",
          "type": "COGVIDEOPIPE",
          "links": [
            36
          ],
          "slot_index": 0,
          "shape": 3
        }
      ],
      "properties": {
        "Node name for S&R": "DownloadAndLoadCogVideoModel"
      },
      "widgets_values": [
        "THUDM/CogVideoX-5b",
        "fp16",
        "fastmode",
        "disabled",
        false
      ]
    }
  ],
  "links": [
    [
      36,
      1,
      0,
      22,
      0,
      "COGVIDEOPIPE"
    ],
    [
      37,
      22,
      0,
      11,
      0,
      "COGVIDEOPIPE"
    ],
    [
      38,
      22,
      1,
      11,
      1,
      "LATENT"
    ],
    [
      54,
      20,
      0,
      30,
      0,
      "CLIP"
    ],
    [
      55,
      30,
      0,
      22,
      1,
      "CONDITIONING"
    ],
    [
      56,
      20,
      0,
      31,
      0,
      "CLIP"
    ],
    [
      57,
      31,
      0,
      22,
      2,
      "CONDITIONING"
    ],
    [
      59,
      11,
      0,
      33,
      0,
      "IMAGE"
    ],
    [
      60,
      33,
      0,
      32,
      0,
      "IMAGE"
    ]
  ],
  "groups": [],
  "config": {},
  "extra": {
    "ds": {
      "scale": 0.9090909090909094,
      "offset": [
        -288.6996733731509,
        167.3370362187946
      ]
    }
  },
  "version": 0.4
}

**Comment by KrakeyMTL** [comment]
I fixed this issue this morning on one of my servers by just re-cloning via git the entire I2V repo into the proper folder, refresh comfy and it should work (did for me)

**Comment by zatt** [comment]
I had this error too. Mine was because I was missing the VAE file. The VAE and the safetensors file are both called "diffusion_pytorch_model.safetensors" but are in different folders.

If you don't want to troubleshoot and manually download and place the files, just delete and restart like KrakeyMTL mentions above.

**Comment by AndrewGleason1234** [comment]
> I had this error too. Mine was because I was missing the VAE file. The VAE and the safetensors file are both called "diffusion_pytorch_model.safetensors" but are in different folders.
> 
> If you don't want to troubleshoot and manually download and place the files, just delete and restart like KrakeyMTL mentions above.

Do you have a link to the file so i can manually download it? I can't seem to find it.

**Comment by antoineprobst** [comment]
"Do you have a link to the file so i can manually download it? I can't seem to find it."
https://huggingface.co/THUDM/CogVideoX-5b/tree/main/vae
I think for you it's this file that you are looking for. (the safetensors one)

I personnally had the same error but for the I2V model, and installing this one solved it :
https://huggingface.co/THUDM/CogVideoX-5b-I2V/tree/main/vae
I had to put it in ComfyUI\models\CogVideo\CogVideoX-5b-I2V\vae
Probably gonna be a similar path for you, but not the same since you're not using the same model.

**Comment by KrakeyMTL** [comment]
I missed the comment sorry, all you need to do on github is go to the repo you want, there are 3 dots to the right, click that and a link will be there to clone the repo on your machine.

Usually when someone says this it means go use GIT, get a bash window open, get to the dir you want, and type this : 

git clone https://huggingface.co/THUDM/CogVideoX-5b-I2V

That will background download into the folder all it needs from the repo.
Also if git isn't being used - you must learn it. Basic requirement IMO for this ai stuff!
