### ISSUE TITLE
Cannot import name 'CogVideoXDDIMScheduler'

### ISSUE THREAD

**Issue by nyukers** [kijai/ComfyUI-CogVideoXWrapper#56]
Python version: 3.10.9 (tags/v3.10.9:1dd9be6, Dec  6 2022, 20:01:21) [MSC v.1934 64 bit (AMD64)]

Traceback (most recent call last):
  File "d:\SDComfyUI\ComfyUI\nodes.py", line 1994, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\SDComfyUI\ComfyUI\custom_nodes\ComfyUI-CogVideoXWrapper\__init__.py", line 1, in <module>
    from .nodes import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "D:\SDComfyUI\ComfyUI\custom_nodes\ComfyUI-CogVideoXWrapper\nodes.py", line 6, in <module>
    from diffusers.schedulers import CogVideoXDDIMScheduler, CogVideoXDPMScheduler
ImportError: cannot import name 'CogVideoXDDIMScheduler' from 'diffusers.schedulers' (d:\SDComfyUI\python_embeded\lib\site-packages\diffusers\schedulers\__init__.py)

Please, help me to resolve it. Thanks.

**Comment by nyukers** [comment]
..\python_embeded\python.exe -m pip install diffusers==0.30.1
