### ISSUE TITLE
No module named nexfort

### ISSUE THREAD

**Issue by DuckersMcQuack** [kijai/ComfyUI-CogVideoXWrapper#57]
Tried to compile with nexfort to speed it up, but it can't find it even if installed.

```
(venv) (base) D:\Stablediff\Comfyuimanual\ComfyUI>pip install nexfort
Requirement already satisfied: nexfort in d:\stablediff\comfyuimanual\comfyui\venv\lib\site-packages (0.0.1.dev0)
Requirement already satisfied: peppercorn in d:\stablediff\comfyuimanual\comfyui\venv\lib\site-packages (from nexfort) (0.6)
```

```
2024-09-18 10:44:01,793 - root - INFO - Prompt executed in 11.95 seconds
2024-09-18 10:45:07,168 - root - INFO - got prompt
2024-09-18 10:45:07,534 - root - INFO - Requested to load SD3ClipModel_
2024-09-18 10:45:07,534 - root - INFO - Loading 1 new model
2024-09-18 10:45:07,539 - root - INFO - loaded completely 0.0 4541.693359375 True
2024-09-18 10:45:15,744 - root - ERROR - !!! Exception during processing !!! No module named 'nexfort'
2024-09-18 10:45:15,745 - root - ERROR - Traceback (most recent call last):
  File "D:\Stablediff\Comfyuimanual\ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "D:\Stablediff\Comfyuimanual\ComfyUI\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "D:\Stablediff\Comfyuimanual\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "D:\Stablediff\Comfyuimanual\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
  File "D:\Stablediff\Comfyuimanual\ComfyUI\custom_nodes\ComfyUI-CogVideoXWrapper\nodes.py", line 98, in loadmodel
    pipe = compile_pipe(
  File "D:\Stablediff\Comfyuimanual\ComfyUI\venv\lib\site-packages\onediffx\compilers\diffusion_pipeline_compiler.py", line 75, in compile_pipe
    pipe = convert_pipe_to_memory_format(
  File "D:\Stablediff\Comfyuimanual\ComfyUI\venv\lib\site-packages\onediffx\compilers\diffusion_pipeline_compiler.py", line 120, in convert_pipe_to_memory_format
    from nexfort.utils.attributes import multi_recursive_apply
ModuleNotFoundError: No module named 'nexfort'
```

**Comment by kijai** [comment]
It won't work in Windows anyway.

**Comment by kijai** [comment]
> > It won't work in Windows anyway.
> 
> Gotcha, thanks for noting that :) it only works for debian, right? Or ubuntu specifically?

Should work with any Linux distro, I've been using with with Debian and PopOS so far.

**Comment by tavyscrolls** [comment]
It was working for me before xformers made py 3.12 wheels available where I upgraded comfyui/manager/transformers/diffusers/torch/etc and now I'm getting same error. On Debian 13

```
got prompt
!!! Exception during processing !!! No module named 'nexfort'
Traceback (most recent call last):
  File "/home/USER/NAME/ComfyUI/execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/USER/NAME/ComfyUI/execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/USER/NAME/ComfyUI/execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "/home/USER/NAME/ComfyUI/execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/USER/NAME/ComfyUI/custom_nodes/ComfyUI-CogVideoXWrapper/nodes.py", line 130, in loadmodel
    pipe = compile_pipe(
           ^^^^^^^^^^^^^
  File "/home/USER/NAME/ComfyUI/venv/lib/python3.12/site-packages/onediffx/compilers/diffusion_pipeline_compiler.py", line 75, in compile_pipe
    pipe = convert_pipe_to_memory_format(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/USER/NAME/ComfyUI/venv/lib/python3.12/site-packages/onediffx/compilers/diffusion_pipeline_compiler.py", line 120, in convert_pipe_to_memory_format
    from nexfort.utils.attributes import multi_recursive_apply
ModuleNotFoundError: No module named 'nexfort'

Prompt executed in 36.34 seconds
^C
Stopped server
(venv) (base) USER@NAME:~/Desktop/ComfyUI$ pip install nexfort
Requirement already satisfied: nexfort in ./venv/lib/python3.12/site-packages (0.0.1.dev0)

```

There's an open issue on onediff that may be related.
