### ISSUE TITLE
Trying out CogVideoX-Fun Sampler: AttributeError: 'list' object has no attribute 'to'

### ISSUE THREAD

**Issue by phr00t** [kijai/ComfyUI-CogVideoXWrapper#63]
![image](https://github.com/user-attachments/assets/da310f93-da85-408d-973e-47f5ffc94468)

```Loading 1 new model
loaded completely 0.0 4541.693359375 True
!!! Exception during processing !!! 'list' object has no attribute 'to'
Traceback (most recent call last):
  File "D:\ComfyUI_windows_portable\ComfyUI\execution.py", line 317, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI_windows_portable\ComfyUI\execution.py", line 192, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI_windows_portable\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "D:\ComfyUI_windows_portable\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-CogVideoXWrapper\nodes.py", line 530, in process
    prompt_embeds=positive.to(dtype).to(device),
                  ^^^^^^^^^^^
AttributeError: 'list' object has no attribute 'to'

Prompt executed in 8.53 seconds```

**Comment by phr00t** [comment]
![image](https://github.com/user-attachments/assets/6c940cdf-628c-45b6-b411-09d12c5857b6)

Not sure why, but your example workflow works fine... I did try fixing fp16 to bf16 (and back), and both worked on your workflow. Still not sure what is wrong with my original workflow, but I'll just start with yours!

**Comment by phr00t** [comment]
OHHHHHHHHHHHH There are specific CogVideo Text Encoders, the normal ClipTextEncode doesn't work!
