### ISSUE TITLE
Error occurred when executing DownloadAndLoadCogVideoModel

### ISSUE THREAD

**Issue by TryingToDoBetter25** [kijai/ComfyUI-CogVideoXWrapper#77]
When I tried CogVideoX-5b-I2V, I encountered this problem. Does anyone know how to solve it？
![Uploading PixPin_2024-09-21_00-55-09.jpg…]()

**Comment by TryingToDoBetter25** [comment]
Traceback (most recent call last):
  File "F:\1AI\1\ComfyUI_CogVideoX-\ComfyUI\execution.py", line 152, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\1AI\1\ComfyUI_CogVideoX-\ComfyUI\execution.py", line 82, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\1AI\1\ComfyUI_CogVideoX-\ComfyUI\execution.py", line 75, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\1AI\1\ComfyUI_CogVideoX-\ComfyUI\custom_nodes\ComfyUI-CogVideoXWrapper\nodes.py", line 98, in loadmodel
    transformer = CogVideoXTransformer3DModel.from_pretrained(base_path, subfolder="transformer")
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\1AI\1\ComfyUI_CogVideoX-\python_embeded\Lib\site-packages\huggingface_hub\utils\_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "F:\1AI\1\ComfyUI_CogVideoX-\python_embeded\Lib\site-packages\diffusers\models\modeling_utils.py", line 774, in from_pretrained
    accelerate.load_checkpoint_and_dispatch(
  File "F:\1AI\1\ComfyUI_CogVideoX-\python_embeded\Lib\site-packages\accelerate\big_modeling.py", line 613, in load_checkpoint_and_dispatch
    load_checkpoint_in_model(
  File "F:\1AI\1\ComfyUI_CogVideoX-\python_embeded\Lib\site-packages\accelerate\utils\modeling.py", line 1821, in load_checkpoint_in_model
    set_module_tensor_to_device(
  File "F:\1AI\1\ComfyUI_CogVideoX-\python_embeded\Lib\site-packages\accelerate\utils\modeling.py", line 341, in set_module_tensor_to_device
    raise ValueError(f"{module} does not have a parameter or a buffer named {tensor_name}.")
ValueError: CogVideoXPatchEmbed(
  (proj): Conv2d(32, 3072, kernel_size=(2, 2), stride=(2, 2))
  (text_proj): Linear(in_features=4096, out_features=3072, bias=True)
) does not have a parameter or a buffer named pos_embedding.

**Comment by kijai** [comment]
Did you update diffusers to 0.30.3?

**Comment by TryingToDoBetter25** [comment]
> Did you update diffusers to 0.30.3?

I reinstalled it and it ran successfully. Thank you very much
