### ISSUE TITLE
6GB VRAM running base 5B OK but OOM with 2B-fun

### ISSUE THREAD

**Issue by realisticdreamer114514** [kijai/ComfyUI-CogVideoXWrapper#82]
I use your suggested workflow to get base 5B running on my 6GB VRAM card
![workflow](https://github.com/user-attachments/assets/3a2cfbdd-999f-48ad-b584-a0dc6ecb5fd5)
But once I modify it to do Fun-2B with Euler A sampler it OOMs
![image](https://github.com/user-attachments/assets/7201a2e8-585e-4abf-9fb4-022c71b64ec8)
(the video output here is from the previous successful test so it isn't from this time)
```
got prompt
The config attributes {'mid_block_add_attention': True, 'sample_size': 256} were passed to AutoencoderKLCogVideoX, but are not expected and will be ignored. Please verify your config.json configuration file.
Closest size: 608x416
C:\Users\USER\anaconda3\envs\cogvideo\Lib\site-packages\diffusers\configuration_utils.py:140: FutureWarning: Accessing config attribute `vae_latent_channels` directly via 'VaeImageProcessor' object attribute is deprecated. Please access 'vae_latent_channels' over 'VaeImageProcessor's config object instead, e.g. 'scheduler.config.vae_latent_channels'.
  deprecate("direct config name access", "1.0.0", deprecation_message, standard_warn=False)
!!! Exception during processing !!! Allocation on device
Traceback (most recent call last):
  File "D:\webui-forge\ComfyUI_windows_portable\ComfyUI\execution.py", line 317, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\webui-forge\ComfyUI_windows_portable\ComfyUI\execution.py", line 192, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\webui-forge\ComfyUI_windows_portable\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "D:\webui-forge\ComfyUI_windows_portable\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\webui-forge\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-CogVideoXWrapper\nodes.py", line 786, in process
    latents = pipe(
              ^^^^^
  File "C:\Users\USER\anaconda3\envs\cogvideo\Lib\site-packages\torch\utils\_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\webui-forge\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-CogVideoXWrapper\cogvideox_fun\pipeline_cogvideox_inpaint.py", line 718, in __call__
    _, masked_video_latents = self.prepare_mask_latents(
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\webui-forge\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-CogVideoXWrapper\cogvideox_fun\pipeline_cogvideox_inpaint.py", line 339, in prepare_mask_latents
    mask_pixel_values_bs = self.vae.encode(mask_pixel_values_bs)[0]
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\USER\anaconda3\envs\cogvideo\Lib\site-packages\diffusers\utils\accelerate_utils.py", line 46, in wrapper
    return method(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\webui-forge\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-CogVideoXWrapper\cogvideox_fun\autoencoder_magvit.py", line 1114, in encode
    z_intermediate = self.encoder(z_intermediate)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\USER\anaconda3\envs\cogvideo\Lib\site-packages\torch\nn\modules\module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\USER\anaconda3\envs\cogvideo\Lib\site-packages\torch\nn\modules\module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\webui-forge\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-CogVideoXWrapper\cogvideox_fun\autoencoder_magvit.py", line 733, in forward
    hidden_states = down_block(hidden_states, temb, None)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\USER\anaconda3\envs\cogvideo\Lib\site-packages\torch\nn\modules\module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\USER\anaconda3\envs\cogvideo\Lib\site-packages\torch\nn\modules\module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\webui-forge\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-CogVideoXWrapper\cogvideox_fun\autoencoder_magvit.py", line 409, in forward
    hidden_states = resnet(hidden_states, temb, zq)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\USER\anaconda3\envs\cogvideo\Lib\site-packages\torch\nn\modules\module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\USER\anaconda3\envs\cogvideo\Lib\site-packages\torch\nn\modules\module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\webui-forge\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-CogVideoXWrapper\cogvideox_fun\autoencoder_magvit.py", line 291, in forward
    hidden_states = self.conv1(hidden_states)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\USER\anaconda3\envs\cogvideo\Lib\site-packages\torch\nn\modules\module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\USER\anaconda3\envs\cogvideo\Lib\site-packages\torch\nn\modules\module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\webui-forge\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-CogVideoXWrapper\cogvideox_fun\autoencoder_magvit.py", line 142, in forward
    inputs = F.pad(inputs, padding_2d, mode="constant", value=0)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\USER\anaconda3\envs\cogvideo\Lib\site-packages\torch\nn\functional.py", line 4552, in pad
    return torch._C._nn.pad(input, pad, mode, value)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
torch.OutOfMemoryError: Allocation on device

Got an OOM, unloading all loaded models.
Prompt executed in 79.35 seconds
```
I don't think Fun-2B should take more VRAM to run than base 5B with the same VRAM minimization (enable_sequential_cpu_offload) on.

**Comment by cheezecrisp** [comment]
hmmm...i think it's a miracle for 6G vram to run cogvideox5b_i2v model successfully. in my case it takes 17G to run. wondering what magic power you used to achieve such miracle?

**Comment by kijai** [comment]
This is probably because I was using enable_model_cpu_offload by default in the "Fun" -pipeline, try updating now to see if it's fixed.

**Comment by kijai** [comment]
> hmmm...i think it's a miracle for 6G vram to run cogvideox5b_i2v model successfully. in my case it takes 17G to run. wondering what magic power you used to achieve such miracle?

They are using the sequential_cpu_offloading, which is very slow but drops VRAM requirements a lot. The I2V model shouldn't take 17GB though, in fp8 mode it uses around ~13GB for me. The VAE decoding is the heavier part and using the tiled VAE helps there.

**Comment by cheezecrisp** [comment]
> > hmmm...i think it's a miracle for 6G vram to run cogvideox5b_i2v model successfully. in my case it takes 17G to run. wondering what magic power you used to achieve such miracle?
> 
> They are using the sequential_cpu_offloading, which is very slow but drops VRAM requirements a lot. The I2V model shouldn't take 17GB though, in fp8 mode it uses around ~13GB for me. The VAE decoding is the heavier part and using the tiled VAE helps there.

i see, enable fp8 actually works, now it takes only 12G

**Comment by realisticdreamer114514** [comment]
Now I got a different error
```
Traceback (most recent call last):
  File "D:\webui-forge\ComfyUI_windows_portable\ComfyUI\execution.py", line 317, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\webui-forge\ComfyUI_windows_portable\ComfyUI\execution.py", line 192, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\webui-forge\ComfyUI_windows_portable\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "D:\webui-forge\ComfyUI_windows_portable\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\webui-forge\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-CogVideoXWrapper\nodes.py", line 787, in process
    latents = pipe(
              ^^^^^
  File "C:\Users\USER\anaconda3\envs\cogvideo\Lib\site-packages\torch\utils\_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\webui-forge\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-CogVideoXWrapper\cogvideox_fun\pipeline_cogvideox_inpaint.py", line 634, in __call__
    self.vae.to(device)
  File "C:\Users\USER\anaconda3\envs\cogvideo\Lib\site-packages\torch\nn\modules\module.py", line 1174, in to
    return self._apply(convert)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\USER\anaconda3\envs\cogvideo\Lib\site-packages\torch\nn\modules\module.py", line 780, in _apply
    module._apply(fn)
  File "C:\Users\USER\anaconda3\envs\cogvideo\Lib\site-packages\torch\nn\modules\module.py", line 780, in _apply
    module._apply(fn)
  File "C:\Users\USER\anaconda3\envs\cogvideo\Lib\site-packages\torch\nn\modules\module.py", line 780, in _apply
    module._apply(fn)
  File "C:\Users\USER\anaconda3\envs\cogvideo\Lib\site-packages\torch\nn\modules\module.py", line 805, in _apply
    param_applied = fn(param)
                    ^^^^^^^^^
  File "C:\Users\USER\anaconda3\envs\cogvideo\Lib\site-packages\torch\nn\modules\module.py", line 1167, in convert
    raise NotImplementedError(
NotImplementedError: Cannot copy out of meta tensor; no data! Please use torch.nn.Module.to_empty() instead of torch.nn.Module.to() when moving module from meta to a different device.
```

**Comment by kijai** [comment]
> Now I got a different error
> 
> ```
> Traceback (most recent call last):
>   File "D:\webui-forge\ComfyUI_windows_portable\ComfyUI\execution.py", line 317, in execute
>     output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
>                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "D:\webui-forge\ComfyUI_windows_portable\ComfyUI\execution.py", line 192, in get_output_data
>     return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
>                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "D:\webui-forge\ComfyUI_windows_portable\ComfyUI\execution.py", line 169, in _map_node_over_list
>     process_inputs(input_dict, i)
>   File "D:\webui-forge\ComfyUI_windows_portable\ComfyUI\execution.py", line 158, in process_inputs
>     results.append(getattr(obj, func)(**inputs))
>                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "D:\webui-forge\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-CogVideoXWrapper\nodes.py", line 787, in process
>     latents = pipe(
>               ^^^^^
>   File "C:\Users\USER\anaconda3\envs\cogvideo\Lib\site-packages\torch\utils\_contextlib.py", line 116, in decorate_context
>     return func(*args, **kwargs)
>            ^^^^^^^^^^^^^^^^^^^^^
>   File "D:\webui-forge\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-CogVideoXWrapper\cogvideox_fun\pipeline_cogvideox_inpaint.py", line 634, in __call__
>     self.vae.to(device)
>   File "C:\Users\USER\anaconda3\envs\cogvideo\Lib\site-packages\torch\nn\modules\module.py", line 1174, in to
>     return self._apply(convert)
>            ^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\USER\anaconda3\envs\cogvideo\Lib\site-packages\torch\nn\modules\module.py", line 780, in _apply
>     module._apply(fn)
>   File "C:\Users\USER\anaconda3\envs\cogvideo\Lib\site-packages\torch\nn\modules\module.py", line 780, in _apply
>     module._apply(fn)
>   File "C:\Users\USER\anaconda3\envs\cogvideo\Lib\site-packages\torch\nn\modules\module.py", line 780, in _apply
>     module._apply(fn)
>   File "C:\Users\USER\anaconda3\envs\cogvideo\Lib\site-packages\torch\nn\modules\module.py", line 805, in _apply
>     param_applied = fn(param)
>                     ^^^^^^^^^
>   File "C:\Users\USER\anaconda3\envs\cogvideo\Lib\site-packages\torch\nn\modules\module.py", line 1167, in convert
>     raise NotImplementedError(
> NotImplementedError: Cannot copy out of meta tensor; no data! Please use torch.nn.Module.to_empty() instead of torch.nn.Module.to() when moving module from meta to a different device.
> ```

Ok reproduced this error and fixed it.

**Comment by realisticdreamer114514** [comment]
All good.

**Comment by realisticdreamer114514** [comment]
I switched to this https://github.com/MinusZoneAI/ComfyUI-CogVideoX-MZ GGUF loader and strangely the exact same bug comes up again
![image](https://github.com/user-attachments/assets/07b4eec5-8e7c-4025-af94-c96695812f59)

**Comment by kijai** [comment]
> I switched to this https://github.com/MinusZoneAI/ComfyUI-CogVideoX-MZ GGUF loader and strangely the exact same final bug `Cannot copy out of meta tensor; no data!` comes up again ![image](https://private-user-images.githubusercontent.com/96880303/369692837-07b4eec5-8e7c-4025-af94-c96695812f59.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcwMTY0OTksIm5iZiI6MTcyNzAxNjE5OSwicGF0aCI6Ii85Njg4MDMwMy8zNjk2OTI4MzctMDdiNGVlYzUtOGU3Yy00MDI1LWFmOTQtYzk2Njk1ODEyZjU5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTIyVDE0NDMxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY3ZTI3ZDA0ZjgxYmNmZjI4MGViNmFjYjgxNjIwYTNhMGIzYTg3NjY3M2UxMjNlODBkNmQ4Zjc4ZjA3NDY5MGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0._rhuYm9nctcPj7xdL8qVBsPG_mRMZQt0c3KAFrHl6Mw)

I don't think their loader even should work with my nodes though, I have my own GGUF loader that should be used.

**Comment by realisticdreamer114514** [comment]
Misread something you said, sorry.
