### ISSUE TITLE
Got error when using mask with cogvideox5b_i2v

### ISSUE THREAD

**Issue by cheezecrisp** [kijai/ComfyUI-CogVideoXWrapper#83]
want to apply motion mask to keep some regions static, i used the mask node of cogvideo imageencoder, but got following error

`
got prompt
final latents:  torch.Size([1, 1, 16, 60, 90])
latents torch.Size([1, 13, 16, 60, 90])
self.original_mask:  torch.Size([1, 480, 720])
latents:  torch.Size([1, 13, 16, 60, 90])
mask:  torch.Size([1, 13, 16, 60, 90])
Temporal tiling disabled
latents.shape torch.Size([1, 13, 16, 60, 90])
  0%|                                                                                           | 0/20 [00:15<?, ?it/s]
!!! Exception during processing !!! 'NoneType' object has no attribute 'device'
Traceback (most recent call last):
  File "D:\AI\ComfyUI_windows_portable\ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\AI\ComfyUI_windows_portable\ComfyUI\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\AI\ComfyUI_windows_portable\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "D:\AI\ComfyUI_windows_portable\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-CogVideoXWrapper\nodes.py", line 598, in process
    latents = pipeline["pipe"](
              ^^^^^^^^^^^^^^^^^
  File "D:\AI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-CogVideoXWrapper\pipeline_cogvideox.py", line 642, in __call__
    image_latent = self.scheduler.add_noise(original_image_latents, noise, torch.tensor([noise_timestep])
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\AI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\diffusers\schedulers\scheduling_dpm_cogvideox.py", line 451, in add_noise
    self.alphas_cumprod = self.alphas_cumprod.to(device=original_samples.device)
                                                        ^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'device'

Prompt executed in 16.18 seconds
`

BTW, is it possible to apply mask on cogvideox-fun models? didn't find mask on such nodes

**Comment by kijai** [comment]
The masking is very experimental and I haven't tried it with the img2vid models yet, it mostly somewhat worked with the normal text2vid model when doing vid2vid.

**Comment by cheezecrisp** [comment]
> The masking is very experimental and I haven't tried it with the img2vid models yet, it mostly somewhat worked with the normal text2vid model when doing vid2vid.

ok, got it
