### ISSUE TITLE
CogVideoImageEncode reports cuda error

### ISSUE THREAD

**Issue by Jypope** [kijai/ComfyUI-CogVideoXWrapper#87]
I am using cogvideox_I2V_example_01.json and my VRAM is 32GB. I get the following error when I run it:

#######################################################################
!!! Exception during processing !!! CUDA error: too many resources requested for launch
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

Traceback (most recent call last):
  File "/mnt/jingyunpeng/ComfyUI/execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "/mnt/jingyunpeng/ComfyUI/execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "/mnt/jingyunpeng/ComfyUI/execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "/mnt/jingyunpeng/ComfyUI/execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
  File "/mnt/jingyunpeng/ComfyUI/custom_nodes/ComfyUI-CogVideoXWrapper/nodes.py", line 368, in encode
    latents = vae.encode(image_chunk)
  File "/root/anaconda3/envs/sd3/lib/python3.10/site-packages/diffusers/utils/accelerate_utils.py", line 46, in wrapper
    return method(self, *args, **kwargs)
  File "/root/anaconda3/envs/sd3/lib/python3.10/site-packages/diffusers/models/autoencoders/autoencoder_kl_cogvideox.py", line 1130, in encode
    h = self._encode(x)
  File "/root/anaconda3/envs/sd3/lib/python3.10/site-packages/diffusers/models/autoencoders/autoencoder_kl_cogvideox.py", line 1100, in _encode
    x_intermediate = self.encoder(x_intermediate)
  File "/root/anaconda3/envs/sd3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/root/anaconda3/envs/sd3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/anaconda3/envs/sd3/lib/python3.10/site-packages/diffusers/models/autoencoders/autoencoder_kl_cogvideox.py", line 710, in forward
    hidden_states = self.conv_in(sample)
  File "/root/anaconda3/envs/sd3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/root/anaconda3/envs/sd3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/anaconda3/envs/sd3/lib/python3.10/site-packages/diffusers/models/autoencoders/autoencoder_kl_cogvideox.py", line 144, in forward
    output = self.conv(inputs)
  File "/root/anaconda3/envs/sd3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/root/anaconda3/envs/sd3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/anaconda3/envs/sd3/lib/python3.10/site-packages/diffusers/models/autoencoders/autoencoder_kl_cogvideox.py", line 64, in forward
    return super().forward(input)
  File "/root/anaconda3/envs/sd3/lib/python3.10/site-packages/torch/nn/modules/conv.py", line 608, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/root/anaconda3/envs/sd3/lib/python3.10/site-packages/torch/nn/modules/conv.py", line 603, in _conv_forward
    return F.conv3d(
RuntimeError: CUDA error: too many resources requested for launch
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
#############################################################################

ps: I tried turning on fp8_transformer and loading a low-resolution image, but it had no effect

**Comment by kijai** [comment]
What GPU is that? Torch version? Not seen that error with CogVideoX before.

**Comment by tdw-hyn** [comment]
> 那是什么 GPU？Torch 版本？之前没有见过 CogVideoX 出现这种错误。

我也遇到同样错误。GPU是V100（32G）.torch                             2.4.0+cu121
torch-audiomentations             0.11.1
torch-optimizer                   0.1.0
torch-pitch-shift                 1.2.4
torch-stoi                        0.2.1
torchaudio                        2.4.0+cu121
torchdiffeq                       0.2.4
torchmetrics                      0.11.4
torchscale                        0.3.0
torchsde                          0.2.6
torchseg                          0.0.1a4
torchtyping                       0.1.5
torchvision                       0.19.0+cu121

**Comment by kijai** [comment]
Does the "fun" model version workflow `cogvidex_fun_i2v_example_01.json`report same?

**Comment by tdw-hyn** [comment]
> “有趣”的模型版本工作流程`cogvidex_fun_i2v_example_01.json`报告是否相同？

我用的是“cogvideox_I2V_example_01.json”

**Comment by kijai** [comment]
> > “有趣”的模型版本工作流程`cogvidex_fun_i2v_example_01.json`报告是否相同？
> 
> 我用的是“cogvideox_I2V_example_01.json”

Yes but I'm asking if the other one works, so I can pinpoint the possible problem.

**Comment by tdw-hyn** [comment]
> > > “有趣”的模型版本工作流程`cogvidex_fun_i2v_example_01.json`报告是否相同？
> > 
> > 
> > 我用的是“cogvideox_I2V_example_01.json”
> 
> Yes but I'm asking if the other one works, so I can pinpoint the possible problem.

cogvidex_fun_i2v_example_01.json这个工作流不报这个错误。

**Comment by Jypope** [comment]
> > > > > “有趣”的模型版本工作流程`cogvidex_fun_i2v_example_01.json`报告是否相同？
> > > > 
> > > > 
> > > > 我用的是“cogvideox_I2V_example_01.json”
> > > 
> > > 
> > > Yes but I'm asking if the other one works, so I can pinpoint the possible problem.
> > 
> > 
> > cogvidex_fun_i2v_example_01.json这个工作流不报这个错误。
> 
> 我使用cogvidex_fun_i2v_example_01.json工作流在其他地方报错。我减小video_length到17，然后是9，都是同样的错误。
> 
> got prompt Closest size: 608x416 100%|██████████| 30/30 [00:47<00:00, 1.57s/it] torch.Size([1, 3, 16, 52, 76]) !!! Exception during processing !!! CUDA error: too many resources requested for launch CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect. For debugging consider passing CUDA_LAUNCH_BLOCKING=1 Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
> 
> Traceback (most recent call last): File "/root/ComfyUI/execution.py", line 323, in execute output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/root/ComfyUI/execution.py", line 198, in get_output_data return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/root/ComfyUI/execution.py", line 169, in _map_node_over_list process_inputs(input_dict, i) File "/root/ComfyUI/execution.py", line 158, in process_inputs results.append(getattr(obj, func)(**inputs)) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/root/ComfyUI/custom_nodes/ComfyUI-CogVideoXWrapper/nodes.py", line 857, in decode frames = vae.decode(latents).sample ^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.11/site-packages/diffusers/utils/accelerate_utils.py", line 46, in wrapper return method(self, *args, **kwargs) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/root/ComfyUI/custom_nodes/ComfyUI-CogVideoXWrapper/cogvideox_fun/autoencoder_magvit.py", line 1178, in decode decoded = self._decode(z).sample ^^^^^^^^^^^^^^^ File "/root/ComfyUI/custom_nodes/ComfyUI-CogVideoXWrapper/cogvideox_fun/autoencoder_magvit.py", line 1148, in _decode z_intermediate = self.decoder(z_intermediate) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib64/python3.11/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl return self._call_impl(*args, **kwargs) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib64/python3.11/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl return forward_call(*args, **kwargs) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/root/ComfyUI/custom_nodes/ComfyUI-CogVideoXWrapper/cogvideox_fun/autoencoder_magvit.py", line 851, in forward hidden_states = self.conv_in(sample) ^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib64/python3.11/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl return self._call_impl(*args, **kwargs) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib64/python3.11/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl return forward_call(*args, **kwargs) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/root/ComfyUI/custom_nodes/ComfyUI-CogVideoXWrapper/cogvideox_fun/autoencoder_magvit.py", line 144, in forward output = self.conv(inputs) ^^^^^^^^^^^^^^^^^ File "/usr/local/lib64/python3.11/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl return self._call_impl(*args, **kwargs) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib64/python3.11/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl return forward_call(*args, **kwargs) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/root/ComfyUI/custom_nodes/ComfyUI-CogVideoXWrapper/cogvideox_fun/autoencoder_magvit.py", line 64, in forward return super().forward(input) ^^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib64/python3.11/site-packages/torch/nn/modules/conv.py", line 608, in forward return self._conv_forward(input, self.weight, self.bias) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib64/python3.11/site-packages/torch/nn/modules/conv.py", line 603, in _conv_forward return F.conv3d( ^^^^^^^^^ RuntimeError: CUDA error: too many resources requested for launch CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect. For debugging consider passing CUDA_LAUNCH_BLOCKING=1 Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
> 
> Prompt executed in 55.77 seconds

I have the same problem, and it doesn't work after turning on vae_tile

**Comment by tatookan** [comment]
ME TOO
