### ISSUE TITLE
OneDiff Support

### ISSUE THREAD

**Issue by sandor-lisn** [kijai/ComfyUI-CogVideoXWrapper#95]
Hello! 
I was running all sample workflows on my system (Linux, PyTorch 2.4, onediff, RTX 4090). 
They all work, but onediff is not being used. 

What do I need to trigger it? 

Thank you!

**Comment by kijai** [comment]
You have enabled onediff as the compile option in the model loader node? Note that onediff doesn't work with GGUF so it's only available in the normal model loader node.

**Comment by sandor-lisn** [comment]
Hello, 
thank you very much for your lightning fast answer! 
My bad, I should have seen this option myself...

When I enable it, I get a python error. The stacktrace is at the botton of this message. 

I followed the instructions on your main project page. My conda environment contains: 
- torch 2.4.0.dev20240324+cu121
- nexfort 0.1.dev271
- onediff 1.2.1.dev24
- onediffx 1.2.1.dev24

Do you have a suggestion? Thank you!

========
Unable to load nexfort.{extension} module. Is it compatible with your PyTorch installation?
!!! Exception during processing !!! /home/sandor/anaconda3/envs/comfy-flux/lib/python3.10/site-packages/nexfort/_C.cpython-310-x86_64-linux-gnu.so: undefined symbol: _ZNK3c105Error4whatEv
Traceback (most recent call last):
  File "/home/sandor/workspace/ComfyUI-flux/execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "/home/sandor/workspace/ComfyUI-flux/execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "/home/sandor/workspace/ComfyUI-flux/execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "/home/sandor/workspace/ComfyUI-flux/execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
  File "/home/sandor/workspace/ComfyUI-flux/custom_nodes/ComfyUI-CogVideoXWrapper/nodes.py", line 176, in loadmodel
    pipe = compile_pipe(
  File "/home/sandor/anaconda3/envs/comfy-flux/lib/python3.10/site-packages/onediffx/compilers/diffusion_pipeline_compiler.py", line 75, in compile_pipe
    pipe = convert_pipe_to_memory_format(
  File "/home/sandor/anaconda3/envs/comfy-flux/lib/python3.10/site-packages/onediffx/compilers/diffusion_pipeline_compiler.py", line 120, in convert_pipe_to_memory_format
    from nexfort.utils.attributes import multi_recursive_apply
  File "/home/sandor/anaconda3/envs/comfy-flux/lib/python3.10/site-packages/nexfort/__init__.py", line 22, in <module>
    exec(f"import nexfort.{extension} as {extension}")
  File "<string>", line 1, in <module>
ImportError: /home/sandor/anaconda3/envs/comfy-flux/lib/python3.10/site-packages/nexfort/_C.cpython-310-x86_64-linux-gnu.so: undefined symbol: _ZNK3c105Error4whatEv

**Comment by kijai** [comment]
Some issue with nexfort install, not seen that one before. Torch 2.4.1 is on stable release now so I'd suggest installing that, as it works for me using it.

**Comment by sandor-lisn** [comment]
Updating to Torch 2.4.1 did the trick. Thanks so much for your great volunteer efforts!
